begin;
delete from public.cc_questions where id like 'ssiap1-hc-%';
insert into public.cc_questions
  (id, module_id, type, title, question, scenario, situation, explanation,
   correct_answer, correct_answers, correct_order, correct_blanks, correct_path,
   word_bank, sentence, image_key, image_desc, tags, display_order)
values
('ssiap1-hc-b1-q1', 'ssiap1-partie1', 'scenario', 'Odeur suspecte',
  'Quelle est votre PREMIÈRE action ?', 'Lors d''une ronde de nuit, vous sentez une forte odeur de brûlé dans le couloir du 2ème étage. Vous approchez d''une porte et constatez qu''elle est chaude au toucher. Aucune fumée visible.', null, 'Porte chaude = feu violent possible derrière. On ne l''ouvre JAMAIS. On déclenche l''alarme en priorité puis on alerte le PC.',
  1, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack']::text[],
  (select coalesce(max(display_order), -1) + 1 + 0 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie1')),
('ssiap1-hc-b1-q2', 'ssiap1-partie1', 'quiz', 'Tétraèdre du feu',
  'Quels sont les 4 éléments du tétraèdre du feu ?', null, null, 'Tétraèdre = combustible + comburant (O2) + énergie d''activation + réaction en chaîne. Supprimer l''un des 4 éteint le feu.',
  0, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack']::text[],
  (select coalesce(max(display_order), -1) + 1 + 0 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie1')),
('ssiap1-hc-b1-q3', 'ssiap1-partie1', 'multiple-select', 'Facteurs de propagation',
  'Quels facteurs ACCÉLÈRENT la propagation d''un incendie ? (plusieurs réponses)', null, null, 'Charge calorifique ✅, courants d''air ✅, géométrie ✅, air sec ✅. La couleur des murs n''a aucun impact sur la propagation ❌.',
  null, array[0,2,3,4]::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack']::text[],
  (select coalesce(max(display_order), -1) + 1 + 0 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie1')),
('ssiap1-hc-b1-q4', 'ssiap1-partie1', 'find-intruder', 'Classe de feu inexistante',
  'Parmi ces classes de feu, laquelle N''EXISTE PAS dans la nomenclature européenne actuelle ?', null, null, 'La classe E n''existe plus depuis la révision européenne. Classes valides : A (solides), B (liquides), C (gaz), D (métaux), F (huiles cuisson).',
  2, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack']::text[],
  (select coalesce(max(display_order), -1) + 1 + 0 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie1')),
('ssiap1-hc-b1-q5', 'ssiap1-partie1', 'true-false', 'Fumée et mortalité',
  'La fumée est la principale cause de décès lors d''un incendie, avant les brûlures directes.', null, null, 'VRAI — 80% des victimes meurent d''intoxication aux fumées (CO, HCN, CO2...) avant d''être atteintes par les flammes. Les fumées désorientation et provoquent la perte de conscience.',
  0, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack']::text[],
  (select coalesce(max(display_order), -1) + 1 + 0 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie1')),
('ssiap1-hc-b1-q6', 'ssiap1-partie1', 'matching', 'Agents extincteurs',
  'Associez chaque agent extincteur à son mode d''action principal :', null, null, 'Eau = refroidit la base. CO2 = chasse l''oxygène. Poudre = interrompt la réaction en chaîne. Mousse = double action couvrant + refroidissant.',
  null, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack']::text[],
  (select coalesce(max(display_order), -1) + 1 + 0 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie1')),
('ssiap1-hc-b1-q7', 'ssiap1-partie1', 'sequence', 'Phases d''un incendie',
  'Remettez dans l''ordre chronologique les phases de développement d''un incendie :', null, null, 'Naissance → Développement → Flashover (500°C au plafond) → Décrescence. Le flashover est le point de non-retour : tous les matériaux s''enflamment simultanément.',
  null, null::integer[],
  array[0,1,2,3]::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack']::text[],
  (select coalesce(max(display_order), -1) + 1 + 0 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie1')),
('ssiap1-hc-b1-q8', 'ssiap1-partie1', 'fill-blank', 'Réaction et résistance',
  'Complétez ces deux notions fondamentales :', null, null, 'Réaction = comment le matériau se comporte face à une flamme (classement Euroclasses A à F). Résistance = durée en minutes/heures où la structure tient (REI 30, 60, 120...).',
  null, null::integer[],
  null::integer[], array['réaction au feu','résistance au feu']::text[],
  null::integer[], array['réaction au feu','résistance au feu','conductivité','inflammabilité','opacité','résistance mécanique']::text[],
  'La %1% d''un matériau évalue sa participation à la naissance et au développement du feu, tandis que la %2% évalue la durée pendant laquelle il conserve sa fonction.', null, null,
  array['handcrafted','starter-pack']::text[],
  (select coalesce(max(display_order), -1) + 1 + 0 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie1')),
('ssiap1-hc-b1-q9', 'ssiap1-partie1', 'ranking', 'Résistance des matériaux',
  'Classez ces matériaux du PLUS résistant au MOINS résistant face au feu :', null, null, 'Béton > Brique > Bois (carbonise mais reste porteur un moment) > Acier nu (perd 50% de sa résistance dès 400-600°C).',
  null, null::integer[],
  array[0,1,2,3]::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack']::text[],
  (select coalesce(max(display_order), -1) + 1 + 0 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie1')),
('ssiap1-hc-b1-q10', 'ssiap1-partie1', 'categories', 'Extincteur adapté',
  'Classez ces agents extincteurs selon leur utilisation sur un feu d''origine électrique :', null, null, 'CO2 ✅ et Poudre ✅ = non conducteurs. Eau jet plein ❌, eau pulvérisée conductrice ❌, mousse ❌ = risque d''électrocution grave.',
  null, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack']::text[],
  (select coalesce(max(display_order), -1) + 1 + 0 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie1')),
('ssiap1-hc-b1-q11', 'ssiap1-partie1', 'image-identify', 'Panneau triangulaire jaune',
  'Ce panneau triangulaire jaune signale :', null, null, 'Triangle jaune ISO 7010 W012 = AVERTISSEMENT danger électrique. Présence de tension dangereuse. Ne jamais intervenir sans habilitation électrique.',
  1, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, 'electrical-hazard', 'ISO 7010 — W012',
  array['handcrafted','starter-pack']::text[],
  (select coalesce(max(display_order), -1) + 1 + 0 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie1')),
('ssiap1-hc-b1-q12', 'ssiap1-partie1', 'decision', 'Découverte d''incendie',
  'Arbre de décision — étape par étape :', 'Vous êtes en patrouille. Vous découvrez de la fumée qui sort sous la porte d''un local technique. La porte est tiède. Vous êtes seul.', null, 'Alarme en 1er → Intervention si feu petit et sortie disponible → Abandon si le feu prend de l''ampleur. La vie prime sur les biens.',
  null, null::integer[],
  null::integer[], null::text[],
  array[1,1,1]::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack']::text[],
  (select coalesce(max(display_order), -1) + 1 + 0 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie1')),
('ssiap1-hc-b1-q13', 'ssiap1-partie1', 'true-false', 'Backdraft vs Flashover',
  'Le backdraft et le flashover sont deux noms différents pour désigner le même phénomène.', null, null, 'FAUX — Backdraft = explosion due à un apport soudain d''oxygène dans un local enfumé. Flashover = embrasement généralisé par montée en température (500°C au plafond). Deux phénomènes distincts et tous deux mortels.',
  1, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack']::text[],
  (select coalesce(max(display_order), -1) + 1 + 0 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie1')),
('ssiap1-hc-b1-q14', 'ssiap1-partie1', 'scenario', 'Choix de l''extincteur',
  'Quel extincteur utilisez-vous et pourquoi ?', 'Dans la salle serveur, un câble électrique prend feu. Vous disposez d''un extincteur à eau pulvérisée non additif et d''un extincteur CO2. Les flammes font 40 cm de haut.', null, 'CO2 = agent non conducteur, idéal pour les locaux électriques/informatiques. L''eau conduit l''électricité → risque d''électrocution. Exception : eau pulvérisée avec additif anti-électrostatique (vérifier le marquage "feux électriques").',
  1, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack']::text[],
  (select coalesce(max(display_order), -1) + 1 + 0 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie1')),
('ssiap1-hc-b2-q1', 'ssiap1-partie2', 'quiz', 'Classification ERP',
  'Un ERP est classé selon deux critères principaux. Lesquels ?', null, null, 'Type = lettre selon l''activité (M=magasin, R=enseignement, O=hôtel...). Catégorie = de 1 à 5 selon l''effectif. Ces deux critères déterminent toutes les obligations réglementaires.',
  1, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack']::text[],
  (select coalesce(max(display_order), -1) + 1 + 0 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie2')),
('ssiap1-hc-b2-q2', 'ssiap1-partie2', 'scenario', 'Travaux et SSI',
  'Quelle est la bonne conduite à tenir ?', 'Des travaux de rénovation prévoient d''ouvrir une trémie de 0,5m² dans un plancher coupe-feu 1h30 pour faire passer des câbles. Le chef de chantier dit que c''est "un petit percement sans importance".', null, 'Toute modification impactant la sécurité incendie (structure CF, SSI) nécessite une autorisation préalable de la commission. Le permis de feu est obligatoire pour les travaux par points chauds.',
  1, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack']::text[],
  (select coalesce(max(display_order), -1) + 1 + 0 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie2')),
('ssiap1-hc-b2-q3', 'ssiap1-partie2', 'find-intruder', 'Type ERP inexistant',
  'Parmi ces types d''ERP, lequel N''EXISTE PAS dans la réglementation française ?', null, null, 'Le type Z n''existe pas. Les vrais types vont de J à Y : J(personnes âgées), L(salles), M(magasins), N(restaurants), O(hôtels), P(dancings), R(enseignement), S(bibliothèques), T(expo), U(soins), V(culte), W(bureaux), X(sports), Y(musées).',
  2, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack']::text[],
  (select coalesce(max(display_order), -1) + 1 + 0 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie2')),
('ssiap1-hc-b2-q4', 'ssiap1-partie2', 'true-false', 'IGH habitation',
  'Un immeuble d''habitation est classé IGH dès que le plancher bas du dernier niveau habité dépasse 28 mètres.', null, null, 'FAUX — Seuil IGH habitation = 50 mètres. Le seuil de 28 m s''applique aux IGH à usage de bureaux, hôtels, établissements d''enseignement. Ces seuils conditionnent des exigences très renforcées.',
  1, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack']::text[],
  (select coalesce(max(display_order), -1) + 1 + 0 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie2')),
('ssiap1-hc-b2-q5', 'ssiap1-partie2', 'matching', 'Classes IGH',
  'Associez chaque sigle IGH à son usage :', null, null, 'GHA=habitation (>50m), GHO=hôtels, GHW=bureaux, GHU=sanitaire, GHR=enseignement, GHS=archives, GHZ=mixte. Le code GH + lettre = type d''usage.',
  null, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack']::text[],
  (select coalesce(max(display_order), -1) + 1 + 0 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie2')),
('ssiap1-hc-b2-q6', 'ssiap1-partie2', 'multiple-select', 'Obligations IGH',
  'Quelles obligations sont SPÉCIFIQUES aux IGH ? (plusieurs réponses)', null, null, 'SSIAP 24h/24 ✅, compartimentage ✅, SSI cat.A ✅, colonnes humides ✅. L''exercice trimestriel n''est pas une obligation spécifique IGH — 2 fois/an en ERP courant.',
  null, array[0,1,2,4]::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack']::text[],
  (select coalesce(max(display_order), -1) + 1 + 0 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie2')),
('ssiap1-hc-b2-q7', 'ssiap1-partie2', 'sequence', 'Instruction dossier ERP',
  'Remettez dans l''ordre les étapes d''instruction d''une demande d''ouverture d''ERP :', null, null, 'Sans avis FAVORABLE de la commission, le maire ne peut pas délivrer l''autorisation. Un avis défavorable = fermeture administrative possible.',
  null, null::integer[],
  array[0,1,2,3]::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack']::text[],
  (select coalesce(max(display_order), -1) + 1 + 0 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie2')),
('ssiap1-hc-b2-q8', 'ssiap1-partie2', 'fill-blank', 'Compartimentage IGH',
  'Complétez la règle de compartimentage des IGH :', null, null, 'Article GH 10 : 2 500 m² max et 3 niveaux max par compartiment. Les parois délimitatives doivent être CF 2h minimum.',
  null, null::integer[],
  null::integer[], array['2500','3']::text[],
  null::integer[], array['2500','3','5000','2','1000','4','1500','6']::text[],
  'Dans un IGH, chaque compartiment ne doit pas dépasser %1% m² de surface et %2% niveaux en superposition.', null, null,
  array['handcrafted','starter-pack']::text[],
  (select coalesce(max(display_order), -1) + 1 + 0 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie2')),
('ssiap1-hc-b2-q9', 'ssiap1-partie2', 'ranking', 'Fréquence des visites de commission',
  'Classez ces catégories d''ERP par fréquence de visite (de la plus fréquente à la moins fréquente) :', null, null, '1ère et 2ème cat. = annuelle. 3ème cat. = tous les 2 ans. 4ème cat. = tous les 3 ans. La 5ème catégorie est dispensée de passage en commission sauf lors de l''ouverture.',
  null, null::integer[],
  array[0,1,2,3]::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack']::text[],
  (select coalesce(max(display_order), -1) + 1 + 0 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie2')),
('ssiap1-hc-b2-q10', 'ssiap1-partie2', 'categories', 'Documents ERP',
  'Classez ces documents selon leur caractère obligatoire en ERP :', null, null, 'Registre ✅, Notice ✅, Plans ✅ = obligatoires. Les catalogues et revues ont une valeur documentaire mais ne sont pas des obligations réglementaires.',
  null, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack']::text[],
  (select coalesce(max(display_order), -1) + 1 + 0 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie2')),
('ssiap1-hc-b2-q11', 'ssiap1-partie2', 'image-identify', 'Panneau vert personnes',
  'Ce pictogramme vert représente :', null, null, 'ISO 7010 E007 = Point de rassemblement. Lieu où tous les occupants doivent se regrouper après évacuation pour permettre le comptage et informer les secours.',
  1, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, 'assembly', 'ISO 7010 — E007',
  array['handcrafted','starter-pack']::text[],
  (select coalesce(max(display_order), -1) + 1 + 0 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie2')),
('ssiap1-hc-b2-q12', 'ssiap1-partie2', 'decision', 'Registre non tenu',
  'Quelle est la marche à suivre ?', 'Vous prenez votre poste de SSIAP. En consultant le registre de sécurité, vous constatez qu''il n''a pas été rempli depuis 5 semaines et que plusieurs vérifications périodiques ne sont pas documentées.', null, 'Signaler → Rechercher les preuves existantes → Programmer les vérifications manquantes. La falsification de registre est une infraction pénale.',
  null, null::integer[],
  null::integer[], null::text[],
  array[1,1,0]::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack']::text[],
  (select coalesce(max(display_order), -1) + 1 + 0 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie2')),
('ssiap1-hc-b2-q13', 'ssiap1-partie2', 'true-false', 'Permis de feu',
  'Dans un ERP, le permis de feu peut être accordé verbalement si le responsable sécurité est présent.', null, null, 'FAUX — Le permis de feu (GN13) est TOUJOURS écrit, daté, signé des deux parties (donneur d''ordre + exécutant). Aucune exception. Un permis verbal n''a aucune valeur juridique.',
  1, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack']::text[],
  (select coalesce(max(display_order), -1) + 1 + 0 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie2')),
('ssiap1-hc-b2-q14', 'ssiap1-partie2', 'scenario', 'Commission de sécurité',
  'Le directeur a-t-il raison ?', 'La commission de sécurité émet un avis défavorable lors de la visite périodique d''un ERP de 1ère catégorie. Le directeur affirme que la commission "n''a pas le pouvoir de fermer".', null, 'La commission émet un avis (favorable ou défavorable). En cas d''avis défavorable, le maire PEUT prendre un arrêté de fermeture. C''est le maire qui décide, mais il engage sa responsabilité en maintenant ouvert un ERP dangereux.',
  1, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack']::text[],
  (select coalesce(max(display_order), -1) + 1 + 0 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie2')),
('ssiap1-hc-b2-q15', 'ssiap1-partie2', 'image-identify', 'Flèche verte personnage',
  'Ce panneau vert avec personnage et flèche indique :', null, null, 'ISO 7010 E003 = Direction vers une issue de secours. Ces panneaux jalonnent tout le cheminement d''évacuation. Ils doivent être visibles en permanence, de jour comme de nuit (rétro-éclairés ou luminescents).',
  1, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, 'exit-direction', 'ISO 7010 — E003',
  array['handcrafted','starter-pack']::text[],
  (select coalesce(max(display_order), -1) + 1 + 0 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie2')),
('ssiap1-hc-b3-q1', 'ssiap1-partie3', 'scenario', 'Alarme SSI — levée de doute',
  'Quelle est la procédure correcte ?', 'Le tableau de signalisation affiche "ALARME FEU — Zone 12 — Sous-sol parking" depuis 2 minutes. Vous regardez les caméras de surveillance : aucune fumée visible. Votre responsable vous demande de réarmer immédiatement "pour ne pas déranger".', null, 'Toute alarme = levée de doute obligatoire avant réarmement. Réarmer sans vérification = faute professionnelle grave pouvant engager la responsabilité pénale. L''ordre hiérarchique ne supplante pas la procédure réglementaire.',
  1, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack']::text[],
  (select coalesce(max(display_order), -1) + 1 + 0 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie3')),
('ssiap1-hc-b3-q2', 'ssiap1-partie3', 'quiz', 'Signification SSI',
  'Que désigne l''acronyme SSI ?', null, null, 'SSI = Système de Sécurité Incendie (norme NF S 61-931). Il comprend le SDI (Système de Détection Incendie) et le SMSI (Système de Mise en Sécurité Incendie).',
  1, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack']::text[],
  (select coalesce(max(display_order), -1) + 1 + 0 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie3')),
('ssiap1-hc-b3-q3', 'ssiap1-partie3', 'true-false', 'CO2 et feu de friture',
  'Un extincteur CO2 peut être utilisé sur un feu de friture (classe F) car il étouffe les flammes.', null, null, 'FAUX — Le CO2 est DANGEREUX sur les feux de classe F. La pression du jet peut projeter l''huile bouillante et provoquer un embrasement violent (explosion d''huile). Seuls les extincteurs homologués pour classe F (à eau avec additif) conviennent.',
  1, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack']::text[],
  (select coalesce(max(display_order), -1) + 1 + 0 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie3')),
('ssiap1-hc-b3-q4', 'ssiap1-partie3', 'find-intruder', 'Ce qui n''est pas un DAS',
  'Parmi ces équipements, lequel N''EST PAS un Dispositif Actionné de Sécurité (DAS) ?', null, null, 'Le DM (Déclencheur Manuel) est un dispositif d''ENTRÉE du SDI — il déclenche l''alarme. Les DAS sont des dispositifs de SORTIE du SMSI — ils agissent : portes CF, volets, clapets, exutoires de désenfumage.',
  2, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack']::text[],
  (select coalesce(max(display_order), -1) + 1 + 0 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie3')),
('ssiap1-hc-b3-q5', 'ssiap1-partie3', 'matching', 'Extincteur adapté au feu',
  'Associez chaque type de feu à l''extincteur le plus adapté :', null, null, 'Eau = refroidit les feux solides. CO2 = non conducteur pour l''électrique. Mousse = étouffement sur liquides. Poudre ABC = polyvalent mais salissant et dégrade le matériel électronique.',
  null, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack']::text[],
  (select coalesce(max(display_order), -1) + 1 + 0 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie3')),
('ssiap1-hc-b3-q6', 'ssiap1-partie3', 'sequence', 'Catégories de SSI',
  'Classez les catégories de SSI de la PLUS COMPLÈTE à la PLUS SIMPLE :', null, null, 'A (obligatoire IGH et ERP à sommeil important) → B → C → D (alarme + compartimentage partiel) → E (alarme seule). La catégorie A est la plus complète et la plus sûre.',
  null, null::integer[],
  array[0,1,2,3]::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack']::text[],
  (select coalesce(max(display_order), -1) + 1 + 0 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie3')),
('ssiap1-hc-b3-q7', 'ssiap1-partie3', 'multiple-select', 'Vérifications extincteurs',
  'Quelles vérifications sont OBLIGATOIRES pour les extincteurs portatifs ? (plusieurs réponses)', null, null, 'Contrôle visuel mensuel ✅, vérif. annuelle agréée ✅, plombage et pression ✅. L''épreuve hydraulique est tous les 10 ans ❌. Le remplacement systématique tous les 3 ans n''est pas une obligation réglementaire ❌.',
  null, array[0,1,4]::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack']::text[],
  (select coalesce(max(display_order), -1) + 1 + 0 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie3')),
('ssiap1-hc-b3-q8', 'ssiap1-partie3', 'fill-blank', 'Colonnes d''incendie',
  'Complétez la distinction fondamentale :', null, null, 'Colonne sèche : obligatoire dès 18m de hauteur de plancher bas. Colonne humide : obligatoire en IGH et grands ERP. La colonne humide offre une intervention immédiate sans attendre les pompiers.',
  null, null::integer[],
  null::integer[], array['colonne sèche','colonne humide']::text[],
  null::integer[], array['colonne sèche','colonne humide','colonne montante','RIA','sprinkler','tuyau d''attaque']::text[],
  'La %1% est une canalisation vide alimentée en eau par les pompiers à l''arrivée. La %2% est maintenue sous pression en permanence par des surpresseurs avec des RIA à chaque étage.', null, null,
  array['handcrafted','starter-pack']::text[],
  (select coalesce(max(display_order), -1) + 1 + 0 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie3')),
('ssiap1-hc-b3-q9', 'ssiap1-partie3', 'ranking', 'Ordre d''intervention extinction',
  'Classez ces moyens d''extinction par ordre d''intervention (du PREMIER déclenché au DERNIER) :', null, null, 'Sprinkler (automatique dès le départ de feu) → Extincteur (feu naissant) → RIA (feu développé) → Colonne (feu important avec sapeurs-pompiers). Chaque moyen correspond à une ampleur croissante du sinistre.',
  null, null::integer[],
  array[0,1,2,3]::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack']::text[],
  (select coalesce(max(display_order), -1) + 1 + 0 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie3')),
('ssiap1-hc-b3-q10', 'ssiap1-partie3', 'categories', 'SDI ou SMSI',
  'Classez ces équipements dans leur sous-système SSI :', null, null, 'SDI = Détecte et signale : détecteurs automatiques, DM, ECS, ECSAV. SMSI = Agit sur l''environnement : CMSI + tous les DAS (portes CF, volets, clapets, exutoires).',
  null, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack']::text[],
  (select coalesce(max(display_order), -1) + 1 + 0 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie3')),
('ssiap1-hc-b3-q11', 'ssiap1-partie3', 'image-identify', 'Panneau rouge extincteur',
  'Ce panneau carré rouge avec un extincteur blanc indique :', null, null, 'ISO 7010 F001 = Emplacement d''un extincteur. Carré rouge = matériel de lutte incendie. Il doit être visible à 15 mètres maximum. L''extincteur doit être accessible sans obstacle.',
  1, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, 'extinguisher', 'ISO 7010 — F001',
  array['handcrafted','starter-pack']::text[],
  (select coalesce(max(display_order), -1) + 1 + 0 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie3')),
('ssiap1-hc-b3-q12', 'ssiap1-partie3', 'decision', 'Anomalie sprinkler',
  'Procédure de gestion de la défaillance :', 'Une alarme "Manque de pression réseau sprinkler" s''affiche sur le tableau de bord du PC sécurité. Il est 23h00, l''établissement est ouvert avec 150 personnes.', null, 'Alerter → Mesures compensatoires (rondes) → Traçabilité complète (main courante + registre + transmission à la relève). Le sprinkler en panne = risque majeur → surveillance renforcée.',
  null, null::integer[],
  null::integer[], null::text[],
  array[1,1,0]::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack']::text[],
  (select coalesce(max(display_order), -1) + 1 + 0 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie3')),
('ssiap1-hc-b3-q13', 'ssiap1-partie3', 'quiz', 'Inhibition de zone SSI',
  'Qu''est-ce qu''une "inhibition de zone" dans un SSI ?', null, null, 'Inhibition = mise hors service temporaire d''une zone (travaux, maintenance). Nécessite un niveau d''accès 2 minimum, une documentation écrite et des mesures compensatoires (rondes, surveillance humaine renforcée).',
  1, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack']::text[],
  (select coalesce(max(display_order), -1) + 1 + 0 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie3')),
('ssiap1-hc-b3-q14', 'ssiap1-partie3', 'true-false', 'Test mensuel BAES',
  'Un BAES (Bloc Autonome d''Éclairage de Sécurité) doit obligatoirement être testé tous les mois par l''exploitant.', null, null, 'VRAI — Le test mensuel (appui sur le bouton "test" : vérification de l''allumage) est obligatoire. Un contrôle annuel approfondi (autonomie, état de la batterie) doit être réalisé par un technicien qualifié.',
  0, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack']::text[],
  (select coalesce(max(display_order), -1) + 1 + 0 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie3')),
('ssiap1-hc-b3-q15', 'ssiap1-partie3', 'image-identify', 'Panneau RIA',
  'Ce panneau rouge circulaire avec tuyau indique l''emplacement d''un :', null, null, 'RIA = Robinet d''Incendie Armé. Équipement de 2ème intervention composé d''un robinet, un dévidoir et un tuyau semi-rigide. Toujours en eau. Nécessite une formation avant utilisation. Portée 15-20 mètres.',
  1, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, 'ria', 'Panneau réglementaire RIA',
  array['handcrafted','starter-pack']::text[],
  (select coalesce(max(display_order), -1) + 1 + 0 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie3')),
('ssiap1-hc-b4-q1', 'ssiap1-partie4', 'scenario', 'Serre-file face à un récalcitrant',
  'Quelle est votre action correcte ?', 'Lors d''une évacuation déclenchée par l''alarme, vous êtes serre-file au 3ème étage. Un cadre supérieur refuse d''évacuer et dit : "Je suis en réunion importante, c''est encore une fausse alarme".', null, 'Le serre-file tente de convaincre fermement. Si refus persistant : noter son identité, localisation précise, et en informer immédiatement le responsable d''évacuation et les pompiers à l''arrivée. Ne jamais abandonner sans signaler.',
  1, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack']::text[],
  (select coalesce(max(display_order), -1) + 1 + 0 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie4')),
('ssiap1-hc-b4-q2', 'ssiap1-partie4', 'quiz', 'Unité de passage',
  'Quelle est la largeur d''une Unité de Passage (UP) réglementaire en ERP ?', null, null, '1 UP = 0,60 m. Les dégagements sont calculés en nombre d''UP selon l''effectif. Ex : une porte de 0,90 m = 1 UP. Une largeur de 1,40 m = 2 UP. Ces calculs garantissent un débit d''évacuation suffisant.',
  1, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack']::text[],
  (select coalesce(max(display_order), -1) + 1 + 0 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie4')),
('ssiap1-hc-b4-q3', 'ssiap1-partie4', 'find-intruder', 'Action correcte en évacuation',
  'Lequel de ces comportements est CORRECT lors d''une évacuation d''urgence ?', null, null, 'Se rendre calmement au point de rassemblement ✅. Ascenseur ❌ (risque de coupure). Retourner ❌ (risque mortel). Ouvrir les portes CF ❌ (laissent passer le feu et la fumée, elles doivent RESTER FERMÉES).',
  2, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack']::text[],
  (select coalesce(max(display_order), -1) + 1 + 0 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie4')),
('ssiap1-hc-b4-q4', 'ssiap1-partie4', 'true-false', 'Sens d''ouverture des portes',
  'Une porte de sortie desservant plus de 50 personnes doit obligatoirement s''ouvrir dans le sens de l''évacuation.', null, null, 'VRAI — Article CO 44 : dès 50 personnes, porte obligatoirement dans le sens de la sortie pour éviter l''effet de bouchon lors d''une bousculade. En dessous de 50, les deux sens sont autorisés.',
  0, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack']::text[],
  (select coalesce(max(display_order), -1) + 1 + 0 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie4')),
('ssiap1-hc-b4-q5', 'ssiap1-partie4', 'matching', 'Rôles lors de l''évacuation',
  'Associez chaque acteur à sa mission principale lors de l''évacuation :', null, null, 'Guide-file = en tête de groupe. Serre-file = en queue, dernier sorti, portes fermées. SSIAP = interface avec les pompiers (plans, clés). Responsable = autorité de décision.',
  null, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack']::text[],
  (select coalesce(max(display_order), -1) + 1 + 0 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie4')),
('ssiap1-hc-b4-q6', 'ssiap1-partie4', 'sequence', 'Procédure d''alerte',
  'Remettez dans l''ordre les étapes de la procédure d''alerte en cas d''incendie découvert :', null, null, 'Découverte → Alarme (pour évacuer tout le monde) → Alerte secours (18/112) → Accueil des pompiers avec plan, clés, informations. L''alarme AVANT l''alerte externe.',
  null, null::integer[],
  array[0,1,2,3]::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack']::text[],
  (select coalesce(max(display_order), -1) + 1 + 0 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie4')),
('ssiap1-hc-b4-q7', 'ssiap1-partie4', 'multiple-select', 'Éclairage de sécurité',
  'Quels équipements font partie du système d''éclairage de sécurité réglementaire ? (plusieurs réponses)', null, null, 'BAES ✅, éclairage d''ambiance/anti-panique ✅, source centralisée ✅. Néon secteur ❌ (s''éteint en coupure). BAAS ❌ = alarme sonore, pas éclairage.',
  null, array[0,2,3]::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack']::text[],
  (select coalesce(max(display_order), -1) + 1 + 0 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie4')),
('ssiap1-hc-b4-q8', 'ssiap1-partie4', 'fill-blank', 'Autonomie éclairage',
  'Complétez les exigences réglementaires sur l''éclairage de sécurité :', null, null, '1 heure minimum d''autonomie sur batteries intégrées (BAES). Allumage automatique dès coupure secteur. Permet l''évacuation en toute sécurité même lors d''une coupure électrique totale.',
  null, null::integer[],
  null::integer[], array['1','normale']::text[],
  null::integer[], array['1','normale','2','secours','3','principale']::text[],
  'L''éclairage de sécurité doit fonctionner au minimum %1% heure en cas de coupure et doit s''allumer automatiquement dès la perte de l''alimentation %2%.', null, null,
  array['handcrafted','starter-pack']::text[],
  (select coalesce(max(display_order), -1) + 1 + 0 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie4')),
('ssiap1-hc-b4-q9', 'ssiap1-partie4', 'ranking', 'Phases de l''évacuation',
  'Classez ces phases dans l''ordre chronologique correct d''une évacuation réussie :', null, null, 'Alarme → Évacuation ordonnée → Comptage (vérifier que personne ne manque) → Retour exclusivement après feu maître. Ne JAMAIS retourner sans autorisation des pompiers.',
  null, null::integer[],
  array[0,1,2,3]::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack']::text[],
  (select coalesce(max(display_order), -1) + 1 + 0 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie4')),
('ssiap1-hc-b4-q10', 'ssiap1-partie4', 'categories', 'Actions lors de l''évacuation',
  'Classez ces comportements lors de l''évacuation :', null, null, 'Déclencher le DM ✅, fermer les portes ✅ (ralentit le feu), rejoindre le point ✅. Ascenseur ❌, retour dans le bâtiment ❌ — ces deux comportements causent des décès chaque année.',
  null, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack']::text[],
  (select coalesce(max(display_order), -1) + 1 + 0 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie4')),
('ssiap1-hc-b4-q11', 'ssiap1-partie4', 'image-identify', 'Équipement vert lumineux',
  'Cet équipement avec pictogramme de sortie lumineux est un :', null, null, 'BAES = Bloc Autonome d''Éclairage de Sécurité. Batterie intégrée, autonomie 1h minimum. S''allume automatiquement sur coupure secteur. Test mensuel obligatoire par l''exploitant (bouton "test").',
  1, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, 'baes', 'BAES — Bloc Autonome Éclairage Sécurité',
  array['handcrafted','starter-pack']::text[],
  (select coalesce(max(display_order), -1) + 1 + 0 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie4')),
('ssiap1-hc-b4-q12', 'ssiap1-partie4', 'decision', 'Exercice d''évacuation décevant',
  'Comment gérez-vous le retour d''expérience ?', 'L''exercice d''évacuation annuel vient de se terminer : 14 minutes pour évacuer 180 personnes sur 3 étages. Le précédent exercice avait duré 7 minutes. Un goulot d''étranglement a été observé dans l''escalier B.', null, 'Débriefing immédiat → Analyse fine des causes → Compte-rendu complet au registre avec plan d''amélioration. L''exercice n''a de valeur que s''il génère des actions correctives.',
  null, null::integer[],
  null::integer[], null::text[],
  array[1,1,1]::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack']::text[],
  (select coalesce(max(display_order), -1) + 1 + 0 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie4')),
('ssiap1-hc-b4-q13', 'ssiap1-partie4', 'true-false', 'Rôle du serre-file',
  'Le serre-file doit laisser toutes les portes ouvertes derrière lui pour faciliter la circulation lors de l''évacuation.', null, null, 'FAUX — Le serre-file doit FERMER toutes les portes coupe-feu derrière lui. Une porte CF fermée ralentit la progression du feu et de la fumée de 30 à 120 minutes selon sa résistance. C''est une des actions les plus efficaces lors d''une évacuation.',
  1, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack']::text[],
  (select coalesce(max(display_order), -1) + 1 + 0 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie4')),
('ssiap1-hc-b4-q14', 'ssiap1-partie4', 'scenario', 'PMR coincée en hauteur',
  'Quelle est la procédure correcte ?', 'Lors de l''évacuation, vous croisez une collègue en fauteuil roulant au 4ème étage. L''ascenseur est neutralisé. Les escaliers sont inaccessibles pour elle.', null, 'EAS = Espace d''Attente Sécurisé, adjacent aux escaliers, protégé du feu. La PMR y attend les pompiers dans une zone sécurisée. Sa position DOIT être communiquée aux secours à l''arrivée. Porter une personne dans des escaliers peut blesser les deux parties.',
  2, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack']::text[],
  (select coalesce(max(display_order), -1) + 1 + 0 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie4'));
commit;
