begin;
insert into public.cc_question_options (question_id, option_index, option_text) values
('ssiap1-hc-b1-q1', 0, 'Ouvrir la porte pour vérifier l''intérieur'),
('ssiap1-hc-b1-q1', 1, 'Ne pas ouvrir — déclencher l''alarme et alerter le PC de sécurité'),
('ssiap1-hc-b1-q1', 2, 'Chercher un extincteur avant tout'),
('ssiap1-hc-b1-q1', 3, 'Appeler vos collègues pour confirmation'),
('ssiap1-hc-b1-q2', 0, 'Combustible, comburant, énergie d''activation, réaction en chaîne'),
('ssiap1-hc-b1-q2', 1, 'Eau, air, terre, feu'),
('ssiap1-hc-b1-q2', 2, 'Flamme, fumée, chaleur, gaz'),
('ssiap1-hc-b1-q2', 3, 'Bois, oxygène, chaleur, vent'),
('ssiap1-hc-b1-q3', 0, 'La charge calorifique élevée'),
('ssiap1-hc-b1-q3', 1, 'La couleur des murs'),
('ssiap1-hc-b1-q3', 2, 'Les courants d''air et la ventilation'),
('ssiap1-hc-b1-q3', 3, 'La géométrie et la hauteur du local'),
('ssiap1-hc-b1-q3', 4, 'L''humidité de l''air faible'),
('ssiap1-hc-b1-q4', 0, 'Classe A — feux de solides'),
('ssiap1-hc-b1-q4', 1, 'Classe B — feux de liquides'),
('ssiap1-hc-b1-q4', 2, 'Classe E — feux d''installations électriques'),
('ssiap1-hc-b1-q4', 3, 'Classe F — feux d''huiles de cuisson'),
('ssiap1-hc-b1-q5', 0, 'Vrai'),
('ssiap1-hc-b1-q5', 1, 'Faux'),
('ssiap1-hc-b1-q11', 0, 'Un moyen de lutte incendie à proximité'),
('ssiap1-hc-b1-q11', 1, 'Un danger électrique — zone à risque'),
('ssiap1-hc-b1-q11', 2, 'Un défibrillateur accessible'),
('ssiap1-hc-b1-q11', 3, 'Une coupure d''urgence électricité'),
('ssiap1-hc-b1-q13', 0, 'Vrai'),
('ssiap1-hc-b1-q13', 1, 'Faux'),
('ssiap1-hc-b1-q14', 0, 'L''eau pulvérisée — elle refroidit bien'),
('ssiap1-hc-b1-q14', 1, 'Le CO2 — non conducteur, adapté aux feux électriques'),
('ssiap1-hc-b1-q14', 2, 'Les deux ensemble pour plus d''efficacité'),
('ssiap1-hc-b1-q14', 3, 'Ni l''un ni l''autre — évacuer sans intervenir'),
('ssiap1-hc-b2-q1', 0, 'La hauteur des bâtiments et leur surface'),
('ssiap1-hc-b2-q1', 1, 'L''activité exercée (type) et l''effectif maximal accueilli (catégorie)'),
('ssiap1-hc-b2-q1', 2, 'La date de construction et le nombre d''étages'),
('ssiap1-hc-b2-q1', 3, 'La commune et la distance aux secours'),
('ssiap1-hc-b2-q2', 0, 'Accepter les travaux — c''est effectivement mineur'),
('ssiap1-hc-b2-q2', 1, 'Exiger un permis de feu et une demande d''autorisation à la commission de sécurité avant tout début'),
('ssiap1-hc-b2-q2', 2, 'Autoriser à condition de reboucher immédiatement après'),
('ssiap1-hc-b2-q2', 3, 'Appeler les pompiers pour avis verbal'),
('ssiap1-hc-b2-q3', 0, 'Type M — Magasins et centres commerciaux'),
('ssiap1-hc-b2-q3', 1, 'Type O — Hôtels et pensions de famille'),
('ssiap1-hc-b2-q3', 2, 'Type Z — Zones industrielles et entrepôts'),
('ssiap1-hc-b2-q3', 3, 'Type U — Établissements de soins'),
('ssiap1-hc-b2-q4', 0, 'Vrai'),
('ssiap1-hc-b2-q4', 1, 'Faux'),
('ssiap1-hc-b2-q6', 0, 'Service de sécurité SSIAP 24h/24 et 7j/7'),
('ssiap1-hc-b2-q6', 1, 'Compartimentage maximum 2 500 m² sur 3 niveaux'),
('ssiap1-hc-b2-q6', 2, 'SSI de catégorie A obligatoire'),
('ssiap1-hc-b2-q6', 3, 'Exercice d''évacuation trimestriel'),
('ssiap1-hc-b2-q6', 4, 'Colonnes en charge (humides) aux étages'),
('ssiap1-hc-b2-q11', 0, 'Une zone de repos pour le personnel'),
('ssiap1-hc-b2-q11', 1, 'Le point de rassemblement après évacuation'),
('ssiap1-hc-b2-q11', 2, 'Un vestiaire collectif'),
('ssiap1-hc-b2-q11', 3, 'Un accès réservé aux secours'),
('ssiap1-hc-b2-q13', 0, 'Vrai'),
('ssiap1-hc-b2-q13', 1, 'Faux'),
('ssiap1-hc-b2-q14', 0, 'Oui — la commission ne fait que des recommandations'),
('ssiap1-hc-b2-q14', 1, 'Non — un avis défavorable peut entraîner une fermeture administrative par le maire'),
('ssiap1-hc-b2-q14', 2, 'Oui — seuls les tribunaux peuvent fermer un ERP'),
('ssiap1-hc-b2-q14', 3, 'Non — c''est la préfecture qui décide directement'),
('ssiap1-hc-b2-q15', 0, 'Le sens de circulation habituel'),
('ssiap1-hc-b2-q15', 1, 'La direction vers une issue de secours'),
('ssiap1-hc-b2-q15', 2, 'Le poste de premiers secours'),
('ssiap1-hc-b2-q15', 3, 'L''accès au stationnement'),
('ssiap1-hc-b3-q1', 0, 'Réarmer comme demandé — c''est sûrement un défaut technique'),
('ssiap1-hc-b3-q1', 1, 'Refuser, effectuer une levée de doute physique et consigner l''événement'),
('ssiap1-hc-b3-q1', 2, 'Appeler les pompiers sans rien faire d''autre'),
('ssiap1-hc-b3-q1', 3, 'Inhiber la zone 12 pour éviter les fausses alarmes'),
('ssiap1-hc-b3-q2', 0, 'Service de Sécurité Incendie'),
('ssiap1-hc-b3-q2', 1, 'Système de Sécurité Incendie'),
('ssiap1-hc-b3-q2', 2, 'Surveillance et Sécurité des Installations'),
('ssiap1-hc-b3-q2', 3, 'Système de Signalisation Intégrée'),
('ssiap1-hc-b3-q3', 0, 'Vrai'),
('ssiap1-hc-b3-q3', 1, 'Faux'),
('ssiap1-hc-b3-q4', 0, 'Porte coupe-feu à fermeture automatique'),
('ssiap1-hc-b3-q4', 1, 'Volet de désenfumage motorisé'),
('ssiap1-hc-b3-q4', 2, 'Déclencheur Manuel d''alarme (boîtier rouge)'),
('ssiap1-hc-b3-q4', 3, 'Clapet coupe-feu dans une gaine de ventilation'),
('ssiap1-hc-b3-q7', 0, 'Contrôle visuel mensuel par l''exploitant'),
('ssiap1-hc-b3-q7', 1, 'Vérification technique annuelle par organisme agréé'),
('ssiap1-hc-b3-q7', 2, 'Épreuve hydraulique tous les 5 ans'),
('ssiap1-hc-b3-q7', 3, 'Remplacement automatique tous les 3 ans'),
('ssiap1-hc-b3-q7', 4, 'Vérification du plombage et de l''indicateur de pression'),
('ssiap1-hc-b3-q11', 0, 'Un local à risque d''incendie'),
('ssiap1-hc-b3-q11', 1, 'L''emplacement d''un extincteur portatif'),
('ssiap1-hc-b3-q11', 2, 'Un poste de premiers secours'),
('ssiap1-hc-b3-q11', 3, 'Une sortie de secours équipée'),
('ssiap1-hc-b3-q13', 0, 'Le déclenchement volontaire d''une alarme pour test'),
('ssiap1-hc-b3-q13', 1, 'La désactivation temporaire d''une zone de détection pour travaux'),
('ssiap1-hc-b3-q13', 2, 'La mise en service d''une nouvelle zone après installation'),
('ssiap1-hc-b3-q13', 3, 'La réinitialisation complète du système après alarme'),
('ssiap1-hc-b3-q14', 0, 'Vrai'),
('ssiap1-hc-b3-q14', 1, 'Faux'),
('ssiap1-hc-b3-q15', 0, 'Extincteur portatif'),
('ssiap1-hc-b3-q15', 1, 'Robinet d''Incendie Armé (RIA)'),
('ssiap1-hc-b3-q15', 2, 'Poste de premiers secours'),
('ssiap1-hc-b3-q15', 3, 'Point d''alimentation colonne sèche'),
('ssiap1-hc-b4-q1', 0, 'Le laisser — vous ne pouvez pas forcer un supérieur hiérarchique'),
('ssiap1-hc-b4-q1', 1, 'Tenter de le convaincre, si refus noter son identité et prévenir le responsable d''évacuation'),
('ssiap1-hc-b4-q1', 2, 'L''escorter physiquement de force'),
('ssiap1-hc-b4-q1', 3, 'Continuer sans lui — c''est son problème'),
('ssiap1-hc-b4-q2', 0, '0,40 m'),
('ssiap1-hc-b4-q2', 1, '0,60 m'),
('ssiap1-hc-b4-q2', 2, '0,80 m'),
('ssiap1-hc-b4-q2', 3, '1,00 m'),
('ssiap1-hc-b4-q3', 0, 'Prendre l''ascenseur pour gagner du temps'),
('ssiap1-hc-b4-q3', 1, 'Retourner chercher son manteau et son téléphone'),
('ssiap1-hc-b4-q3', 2, 'Se rendre calmement au point de rassemblement'),
('ssiap1-hc-b4-q3', 3, 'Ouvrir toutes les portes coupe-feu pour faciliter le passage'),
('ssiap1-hc-b4-q4', 0, 'Vrai'),
('ssiap1-hc-b4-q4', 1, 'Faux'),
('ssiap1-hc-b4-q7', 0, 'BAES (Bloc Autonome d''Éclairage de Sécurité)'),
('ssiap1-hc-b4-q7', 1, 'Néon fluorescent standard alimenté secteur'),
('ssiap1-hc-b4-q7', 2, 'Éclairage d''ambiance anti-panique'),
('ssiap1-hc-b4-q7', 3, 'Source centralisée sur batteries avec luminaires déportés'),
('ssiap1-hc-b4-q7', 4, 'BAAS (Bloc Autonome d''Alarme Sonore)'),
('ssiap1-hc-b4-q11', 0, 'Détecteur de fumée optique'),
('ssiap1-hc-b4-q11', 1, 'Bloc Autonome d''Éclairage de Sécurité (BAES)'),
('ssiap1-hc-b4-q11', 2, 'Déclencheur manuel d''alarme'),
('ssiap1-hc-b4-q11', 3, 'Diffuseur sonore d''alarme incendie'),
('ssiap1-hc-b4-q13', 0, 'Vrai'),
('ssiap1-hc-b4-q13', 1, 'Faux'),
('ssiap1-hc-b4-q14', 0, 'La porter seul dans les escaliers malgré le risque'),
('ssiap1-hc-b4-q14', 1, 'La laisser — les pompiers s''en chargeront'),
('ssiap1-hc-b4-q14', 2, 'La conduire dans l''Espace d''Attente Sécurisé (EAS) le plus proche et signaler sa position aux secours'),
('ssiap1-hc-b4-q14', 3, 'Lui demander d''attendre que la fumée se dissipe');
insert into public.cc_question_items (question_id, item_index, item_text) values
('ssiap1-hc-b1-q7', 0, 'Feu naissant (< 1m²)'),
('ssiap1-hc-b1-q7', 1, 'Phase de développement (flammes vives)'),
('ssiap1-hc-b1-q7', 2, 'Embrasement généralisé — flashover'),
('ssiap1-hc-b1-q7', 3, 'Phase de décrescence'),
('ssiap1-hc-b1-q9', 0, 'Béton armé avec protection'),
('ssiap1-hc-b1-q9', 1, 'Brique réfractaire pleine'),
('ssiap1-hc-b1-q9', 2, 'Bois lamellé collé (carbonisation lente)'),
('ssiap1-hc-b1-q9', 3, 'Acier nu sans protection'),
('ssiap1-hc-b2-q7', 0, 'Dépôt du dossier (notice sécurité + plans)'),
('ssiap1-hc-b2-q7', 1, 'Instruction technique par les services'),
('ssiap1-hc-b2-q7', 2, 'Visite et avis de la commission de sécurité'),
('ssiap1-hc-b2-q7', 3, 'Délivrance de l''autorisation d''ouverture par le maire'),
('ssiap1-hc-b2-q9', 0, '1ère catégorie — visite annuelle'),
('ssiap1-hc-b2-q9', 1, '2ème catégorie — visite annuelle'),
('ssiap1-hc-b2-q9', 2, '3ème catégorie — visite tous les 2 ans'),
('ssiap1-hc-b2-q9', 3, '4ème catégorie — visite tous les 3 ans'),
('ssiap1-hc-b3-q6', 0, 'Catégorie A : détection totale + toutes fonctions sécurité'),
('ssiap1-hc-b3-q6', 1, 'Catégorie B : détection partielle + toutes fonctions sécurité'),
('ssiap1-hc-b3-q6', 2, 'Catégorie C : alarme générale sans détection auto'),
('ssiap1-hc-b3-q6', 3, 'Catégorie E : alarme générale seule'),
('ssiap1-hc-b3-q9', 0, 'Sprinkler — déclenchement automatique dès 68°C'),
('ssiap1-hc-b3-q9', 1, 'Extincteur portatif — première intervention humaine'),
('ssiap1-hc-b3-q9', 2, 'RIA DN19/25 — deuxième intervention humaine'),
('ssiap1-hc-b3-q9', 3, 'Colonne sèche ou humide — intervention des sapeurs-pompiers'),
('ssiap1-hc-b4-q6', 0, 'Découvrir ou constater le sinistre'),
('ssiap1-hc-b4-q6', 1, 'Déclencher le Déclencheur Manuel d''alarme le plus proche'),
('ssiap1-hc-b4-q6', 2, 'Alerter les sapeurs-pompiers (18 ou 112)'),
('ssiap1-hc-b4-q6', 3, 'Accueillir et guider les secours à leur arrivée'),
('ssiap1-hc-b4-q9', 0, 'Déclenchement du signal d''alarme sonore'),
('ssiap1-hc-b4-q9', 1, 'Évacuation guidée des occupants par les guides-files'),
('ssiap1-hc-b4-q9', 2, 'Comptage et appel au point de rassemblement'),
('ssiap1-hc-b4-q9', 3, 'Retour autorisé uniquement par les sapeurs-pompiers');
insert into public.cc_question_pairs (question_id, pair_index, left_text, right_text) values
('ssiap1-hc-b1-q6', 0, 'Eau pulvérisée', 'Refroidissement'),
('ssiap1-hc-b1-q6', 1, 'CO2', 'Étouffement (chasse O2)'),
('ssiap1-hc-b1-q6', 2, 'Poudre ABC', 'Inhibition chimique'),
('ssiap1-hc-b1-q6', 3, 'Mousse', 'Étouffement + refroidissement'),
('ssiap1-hc-b2-q5', 0, 'GHA', 'Habitation'),
('ssiap1-hc-b2-q5', 1, 'GHO', 'Hôtels et résidences'),
('ssiap1-hc-b2-q5', 2, 'GHW', 'Bureaux'),
('ssiap1-hc-b2-q5', 3, 'GHU', 'Établissements sanitaires'),
('ssiap1-hc-b3-q5', 0, 'Feu de bois et papier (classe A)', 'Eau pulvérisée'),
('ssiap1-hc-b3-q5', 1, 'Feu d''installation électrique', 'CO2'),
('ssiap1-hc-b3-q5', 2, 'Feu de liquide (classe B)', 'Mousse'),
('ssiap1-hc-b3-q5', 3, 'Feu polyvalent A+B+C', 'Poudre ABC'),
('ssiap1-hc-b4-q5', 0, 'Guide-file', 'Ouvre la marche et guide vers la sortie'),
('ssiap1-hc-b4-q5', 1, 'Serre-file', 'Ferme la marche, vérifie les locaux, ferme les portes'),
('ssiap1-hc-b4-q5', 2, 'Agent SSIAP', 'Coordonne l''évacuation et accueille les secours'),
('ssiap1-hc-b4-q5', 3, 'Responsable d''évacuation', 'Décide et supervise l''ensemble du dispositif');
insert into public.cc_question_categories (question_id, category_index, category_id, category_label) values
('ssiap1-hc-b1-q10', 0, 'ok', '✅ Utilisable sur feu électrique'),
('ssiap1-hc-b1-q10', 1, 'nok', '❌ INTERDIT sur feu électrique'),
('ssiap1-hc-b2-q10', 0, 'obligatoire', '📌 Obligatoire réglementairement'),
('ssiap1-hc-b2-q10', 1, 'non', '💡 Utile mais non obligatoire'),
('ssiap1-hc-b3-q10', 0, 'sdi', '🔍 SDI — Système de Détection'),
('ssiap1-hc-b3-q10', 1, 'smsi', '⚡ SMSI — Mise en Sécurité'),
('ssiap1-hc-b4-q10', 0, 'ok', '✅ À faire impérativement'),
('ssiap1-hc-b4-q10', 1, 'nok', '🚫 Strictement interdit');
insert into public.cc_question_category_items (question_id, item_index, item_text, correct_category) values
('ssiap1-hc-b1-q10', 0, 'CO2', 'ok'),
('ssiap1-hc-b1-q10', 1, 'Poudre ABC (sèche)', 'ok'),
('ssiap1-hc-b1-q10', 2, 'Eau jet plein', 'nok'),
('ssiap1-hc-b1-q10', 3, 'Eau pulvérisée conductrice', 'nok'),
('ssiap1-hc-b1-q10', 4, 'Mousse', 'nok'),
('ssiap1-hc-b2-q10', 0, 'Registre de sécurité', 'obligatoire'),
('ssiap1-hc-b2-q10', 1, 'Notice descriptive de sécurité', 'obligatoire'),
('ssiap1-hc-b2-q10', 2, 'Plan de masse à jour', 'obligatoire'),
('ssiap1-hc-b2-q10', 3, 'Catalogue équipements', 'non'),
('ssiap1-hc-b2-q10', 4, 'Revue professionnelle incendie', 'non'),
('ssiap1-hc-b3-q10', 0, 'Détecteur optique de fumée', 'sdi'),
('ssiap1-hc-b3-q10', 1, 'Déclencheur Manuel (DM)', 'sdi'),
('ssiap1-hc-b3-q10', 2, 'CMSI (Centralisateur)', 'smsi'),
('ssiap1-hc-b3-q10', 3, 'Volet de désenfumage', 'smsi'),
('ssiap1-hc-b3-q10', 4, 'ECS (Équipement de Contrôle)', 'sdi'),
('ssiap1-hc-b3-q10', 5, 'Porte coupe-feu motorisée', 'smsi'),
('ssiap1-hc-b4-q10', 0, 'Déclencher le DM en quittant son poste', 'ok'),
('ssiap1-hc-b4-q10', 1, 'Fermer la porte de son bureau derrière soi', 'ok'),
('ssiap1-hc-b4-q10', 2, 'Prendre l''ascenseur pour les étages supérieurs', 'nok'),
('ssiap1-hc-b4-q10', 3, 'Rejoindre le point de rassemblement désigné', 'ok'),
('ssiap1-hc-b4-q10', 4, 'Retourner récupérer un document urgent', 'nok');
insert into public.cc_question_decision_steps (question_id, step_index, step_question, options) values
('ssiap1-hc-b1-q12', 0, 'ÉTAPE 1 — Que faites-vous en premier ?', '[{"text":"Ouvrir pour voir l''étendue du feu","nextStep":99},{"text":"Déclencher l''alarme et appeler le PC sécurité","nextStep":1},{"text":"Prendre un extincteur avant tout","nextStep":99}]'::jsonb),
('ssiap1-hc-b1-q12', 1, 'ÉTAPE 2 — La porte est tiède (pas chaude). Pouvez-vous intervenir ?', '[{"text":"Non, évacuer sans intervenir","nextStep":99},{"text":"Oui si feu naissant, sortie dans le dos, extincteur adapté","nextStep":2},{"text":"Oui toujours, c''est mon rôle","nextStep":99}]'::jsonb),
('ssiap1-hc-b1-q12', 2, 'ÉTAPE 3 — L''extincteur est vide après 15 secondes, le feu progresse. Que faites-vous ?', '[{"text":"Continuer avec les mains","nextStep":null},{"text":"Abandonner l''intervention, évacuer, fermer la porte","nextStep":null},{"text":"Attendre les pompiers sur place","nextStep":null}]'::jsonb),
('ssiap1-hc-b2-q12', 0, 'ÉTAPE 1 — Première action immédiate ?', '[{"text":"Remplir les dates manquantes rétrospectivement","nextStep":99},{"text":"Documenter l''état des lacunes et alerter la hiérarchie","nextStep":1},{"text":"Attendre la prochaine commission pour signaler","nextStep":99}]'::jsonb),
('ssiap1-hc-b2-q12', 1, 'ÉTAPE 2 — Les rapports de vérification technique (extincteurs, SSI) sont absents.', '[{"text":"Inventer des données vraisemblables","nextStep":99},{"text":"Contacter les entreprises de maintenance pour obtenir les copies","nextStep":2},{"text":"Signaler à la commission sans attendre","nextStep":99}]'::jsonb),
('ssiap1-hc-b2-q12', 2, 'ÉTAPE 3 — Une vérification annuelle d''extincteurs est dépassée de 2 mois.', '[{"text":"Programmer immédiatement la vérification et consigner dans le registre","nextStep":null},{"text":"Attendre que quelqu''un s''en aperçoive","nextStep":null},{"text":"Fermer l''établissement","nextStep":null}]'::jsonb),
('ssiap1-hc-b3-q12', 0, 'ÉTAPE 1 — Première action ?', '[{"text":"Réarmer l''alarme et attendre le matin","nextStep":99},{"text":"Alerter la hiérarchie et contacter l''astreinte technique","nextStep":1},{"text":"Évacuer immédiatement l''établissement","nextStep":99}]'::jsonb),
('ssiap1-hc-b3-q12', 1, 'ÉTAPE 2 — En attendant l''intervention technique (délai 30 min) ?', '[{"text":"Ne rien faire — 30 min c''est court","nextStep":99},{"text":"Mettre en place des rondes renforcées dans les zones concernées","nextStep":2},{"text":"Couper le réseau sprinkler pour éviter les faux déclenchements","nextStep":99}]'::jsonb),
('ssiap1-hc-b3-q12', 2, 'ÉTAPE 3 — L''anomalie est consignée. Que faire avant de quitter votre poste ?', '[{"text":"Consigner dans le registre de sécurité et la main courante, transmettre à la relève","nextStep":null},{"text":"Mettre seulement un post-it sur l''écran","nextStep":null},{"text":"Rien — la maintenance a géré","nextStep":null}]'::jsonb),
('ssiap1-hc-b4-q12', 0, 'ÉTAPE 1 — Après l''exercice, que faites-vous en premier ?', '[{"text":"Féliciter quand même tout le monde","nextStep":99},{"text":"Réunir les guides-files et serres-files pour un débriefing à chaud","nextStep":1},{"text":"Appeler les pompiers pour signaler un dysfonctionnement","nextStep":99}]'::jsonb),
('ssiap1-hc-b4-q12', 1, 'ÉTAPE 2 — Goulot d''étranglement dans l''escalier B : quelle analyse faites-vous ?', '[{"text":"C''est normal, les gens ne savent pas évacuer","nextStep":99},{"text":"Identifier la cause : largeur insuffisante, affectation de l''escalier C non communiquée, panique ?","nextStep":2},{"text":"Interdire cet escalier sans analyse","nextStep":99}]'::jsonb),
('ssiap1-hc-b4-q12', 2, 'ÉTAPE 3 — Que consignez-vous dans le registre de sécurité ?', '[{"text":"Le temps total uniquement","nextStep":null},{"text":"Compte-rendu complet : temps, effectif, anomalies, analyse des causes, plan d''amélioration et mesures correctives","nextStep":null},{"text":"Rien — c''était un exercice, pas un vrai sinistre","nextStep":null}]'::jsonb);
commit;
