begin;
delete from public.cc_questions where id like 'ssiap1-hc-p5-%';
insert into public.cc_questions
  (id, module_id, type, title, question, scenario, situation, explanation,
   correct_answer, correct_answers, correct_order, correct_blanks, correct_path,
   word_bank, sentence, image_key, image_desc, tags, pool, display_order)
values
('ssiap1-hc-p5-q1', 'ssiap1-partie5', 'quiz', 'Acronyme POI', 'Que signifie POI dans le contexte de la sécurité incendie ?',
  null, null, 'POI = Plan d''Opération Interne. Document organisant la réponse à un sinistre dans les établissements à risques (Seveso, IGH, gros ERP). Décrit qui fait quoi, où et avec quels moyens.',
  0, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack','partie5']::text[], 'challenge',
  (select coalesce(max(display_order), -1) + 1 + 0 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie5' and q2.id not like 'ssiap1-hc-p5-%')),
('ssiap1-hc-p5-q2', 'ssiap1-partie5', 'quiz', 'Recyclage SSIAP 1', 'Tous les combien de temps un agent SSIAP 1 doit-il faire son recyclage triennal ?',
  null, null, 'Recyclage triennal obligatoire — 14 heures (7h théorie + 7h pratique). Sans recyclage, le diplôme n''est plus valable et l''agent ne peut plus exercer.',
  2, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack','partie5']::text[], 'challenge',
  (select coalesce(max(display_order), -1) + 1 + 1 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie5' and q2.id not like 'ssiap1-hc-p5-%')),
('ssiap1-hc-p5-q3', 'ssiap1-partie5', 'quiz', 'Fréquence exercices évacuation ERP', 'Dans un ERP courant, à quelle fréquence MINIMALE les exercices d''évacuation doivent-ils être organisés ?',
  null, null, 'Article R.123-43 du CCH : exercice tous les 6 mois en ERP courant. En type R (enseignement) : 1 dans le 1er mois de l''année scolaire puis 2/3/an selon catégorie.',
  1, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack','partie5']::text[], 'challenge',
  (select coalesce(max(display_order), -1) + 1 + 2 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie5' and q2.id not like 'ssiap1-hc-p5-%')),
('ssiap1-hc-p5-q4', 'ssiap1-partie5', 'quiz', 'Hauteur d''affichage des plans', 'À quelle hauteur d''œil un plan d''évacuation doit-il être affiché ?',
  null, null, 'Hauteur recommandée 1,30 m à 1,80 m — accessible aussi aux personnes en fauteuil. Le plan doit être lisible, à jour, et orienté correctement (vous êtes ici).',
  1, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack','partie5']::text[], 'challenge',
  (select coalesce(max(display_order), -1) + 1 + 3 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie5' and q2.id not like 'ssiap1-hc-p5-%')),
('ssiap1-hc-p5-q5', 'ssiap1-partie5', 'true-false', 'POI dans tous les ERP', 'Le POI est obligatoire dans tous les ERP, quelle que soit la catégorie.',
  null, null, 'FAUX — Le POI est obligatoire pour les sites à risques particuliers (installations classées Seveso, IGH, certains ERP de 1ère catégorie). Les ERP courants ont des consignes simplifiées via l''affichage.',
  1, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack','partie5']::text[], 'challenge',
  (select coalesce(max(display_order), -1) + 1 + 4 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie5' and q2.id not like 'ssiap1-hc-p5-%')),
('ssiap1-hc-p5-q6', 'ssiap1-partie5', 'true-false', 'Plan d''évacuation et extincteurs', 'Le plan d''évacuation doit obligatoirement faire figurer les extincteurs.',
  null, null, 'VRAI — La norme NF X08-070 impose la représentation des moyens de secours : extincteurs, RIA, déclencheurs manuels, point de rassemblement, issues de secours. Avec leur localisation exacte.',
  0, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack','partie5']::text[], 'challenge',
  (select coalesce(max(display_order), -1) + 1 + 5 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie5' and q2.id not like 'ssiap1-hc-p5-%')),
('ssiap1-hc-p5-q7', 'ssiap1-partie5', 'true-false', 'SSIAP donne l''ordre d''évacuation', 'L''agent SSIAP 1 a l''autorité pour ordonner l''évacuation totale d''un ERP.',
  null, null, 'FAUX — L''agent SSIAP 1 exécute. La décision d''évacuation totale appartient au chef de service sécurité (SSIAP 3) ou à défaut à l''exploitant. SSIAP 1 peut déclencher l''alarme évacuation localement.',
  1, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack','partie5']::text[], 'challenge',
  (select coalesce(max(display_order), -1) + 1 + 6 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie5' and q2.id not like 'ssiap1-hc-p5-%')),
('ssiap1-hc-p5-q8', 'ssiap1-partie5', 'true-false', 'Exercice noté au registre', 'Tout exercice d''évacuation doit être consigné au registre de sécurité avec son retour d''expérience.',
  null, null, 'VRAI — Date, durée, anomalies, plan d''action correctif. Le registre prouve la régularité réglementaire et est exigible par la commission de sécurité.',
  0, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack','partie5']::text[], 'challenge',
  (select coalesce(max(display_order), -1) + 1 + 7 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie5' and q2.id not like 'ssiap1-hc-p5-%')),
('ssiap1-hc-p5-q9', 'ssiap1-partie5', 'multiple-select', 'Mentions obligatoires plan', 'Quelles informations sont OBLIGATOIRES sur un plan d''évacuation ? (plusieurs réponses)',
  null, null, '« Vous êtes ici » + cheminements + moyens de secours + numéros d''urgence. Le SIRET n''a aucun intérêt opérationnel — pas obligatoire.',
  null, array[0,1,3,4]::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack','partie5']::text[], 'challenge',
  (select coalesce(max(display_order), -1) + 1 + 8 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie5' and q2.id not like 'ssiap1-hc-p5-%')),
('ssiap1-hc-p5-q10', 'ssiap1-partie5', 'multiple-select', 'Documents en commission', 'Quels documents sont à présenter à la commission de sécurité lors d''une visite ?',
  null, null, 'Registre + notice + rapports de contrôle (extincteurs, SSI, gaz, électricité). Bilans comptables et contrats RH = pas du ressort de la commission.',
  null, array[0,1,3]::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack','partie5']::text[], 'challenge',
  (select coalesce(max(display_order), -1) + 1 + 9 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie5' and q2.id not like 'ssiap1-hc-p5-%')),
('ssiap1-hc-p5-q11', 'ssiap1-partie5', 'multiple-select', 'Composantes d''un POI', 'Quelles parties trouve-t-on dans un POI ?',
  null, null, 'Risques + organisation + cartographie + fiches réflexes. Les tarifs commerciaux n''ont rien à faire dans un POI opérationnel.',
  null, array[0,1,2,4]::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack','partie5']::text[], 'challenge',
  (select coalesce(max(display_order), -1) + 1 + 10 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie5' and q2.id not like 'ssiap1-hc-p5-%')),
('ssiap1-hc-p5-q12', 'ssiap1-partie5', 'find-intruder', 'Pas sur un plan d''évacuation', 'Lequel de ces éléments NE doit PAS figurer sur un plan d''évacuation ?',
  null, null, 'La liste des employés relève de la confidentialité RH et n''a aucun intérêt opérationnel sur un plan affiché publiquement.',
  2, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack','partie5']::text[], 'challenge',
  (select coalesce(max(display_order), -1) + 1 + 11 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie5' and q2.id not like 'ssiap1-hc-p5-%')),
('ssiap1-hc-p5-q13', 'ssiap1-partie5', 'find-intruder', 'Pas une mission du serre-file', 'Laquelle de ces actions N''EST PAS du ressort du serre-file ?',
  null, null, 'Le serre-file vérifie/ferme/compte. La décision d''évacuation appartient au responsable d''évacuation, pas au serre-file qui exécute.',
  2, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack','partie5']::text[], 'challenge',
  (select coalesce(max(display_order), -1) + 1 + 12 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie5' and q2.id not like 'ssiap1-hc-p5-%')),
('ssiap1-hc-p5-q14', 'ssiap1-partie5', 'find-intruder', 'Pas un point de ronde', 'Lequel de ces points N''EST PAS un point de contrôle classique d''une ronde SSIAP ?',
  null, null, 'Les caisses commerciales = ressort de la direction/comptabilité. La ronde SSIAP vérifie l''état des moyens de secours, des dégagements et des locaux à risques.',
  2, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack','partie5']::text[], 'challenge',
  (select coalesce(max(display_order), -1) + 1 + 13 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie5' and q2.id not like 'ssiap1-hc-p5-%')),
('ssiap1-hc-p5-q15', 'ssiap1-partie5', 'scenario', 'Plan d''évacuation manquant', 'Que faites-vous ?',
  'En arrivant au PC sécurité, vous constatez que le plan d''évacuation du 2ème étage a été retiré (rénovation des couloirs). Le chantier doit durer 3 semaines.', null, 'L''absence d''affichage = non-conformité immédiate. Solution : plan provisoire + signalement au registre + alerte hiérarchie. La conformité prime, on ne peut pas attendre 3 semaines.',
  1, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack','partie5']::text[], 'challenge',
  (select coalesce(max(display_order), -1) + 1 + 14 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie5' and q2.id not like 'ssiap1-hc-p5-%')),
('ssiap1-hc-p5-q16', 'ssiap1-partie5', 'scenario', 'Exercice non préparé', 'Quelle est votre attitude ?',
  'Le directeur vous demande de déclencher un exercice d''évacuation maintenant, sans préavis, sans information à la sous-traitance, sans coordination avec l''accueil. "On verra bien si ça marche."', null, 'Un exercice non préparé peut blesser (panique, sous-traitants, PMR oubliées). L''exercice doit être structuré, briefé, mesuré. Refuser et expliquer est professionnel.',
  1, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack','partie5']::text[], 'challenge',
  (select coalesce(max(display_order), -1) + 1 + 15 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie5' and q2.id not like 'ssiap1-hc-p5-%')),
('ssiap1-hc-p5-q17', 'ssiap1-partie5', 'scenario', 'Visite commission imprévue', 'Comment réagissez-vous ?',
  'Un inspecteur de la commission de sécurité arrive sans prévenir. Le directeur est absent, vous êtes seul SSIAP en poste.', null, 'Inspecteurs/contrôleurs ont droit d''accès. Accueillir poliment, présenter le registre + ce qui est disponible, joindre la direction immédiatement. Refuser engage la responsabilité.',
  1, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack','partie5']::text[], 'challenge',
  (select coalesce(max(display_order), -1) + 1 + 16 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie5' and q2.id not like 'ssiap1-hc-p5-%')),
('ssiap1-hc-p5-q18', 'ssiap1-partie5', 'scenario', 'Évacuation au cinéma', 'Quelle action prioritaire ?',
  'Vous êtes SSIAP 1 dans un multiplexe de cinéma (type L). Une alarme se déclenche pendant la projection. Le public est dans le noir, désorienté.', null, 'Lumière + ouverture portes + guidage vocal calme = procédure type L. La désorientation dans le noir est dangereuse. Ne JAMAIS couper l''alarme sans levée de doute.',
  1, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack','partie5']::text[], 'challenge',
  (select coalesce(max(display_order), -1) + 1 + 17 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie5' and q2.id not like 'ssiap1-hc-p5-%')),
('ssiap1-hc-p5-q19', 'ssiap1-partie5', 'scenario', 'Personne en bas de l''escalier', 'Action correcte ?',
  'Lors d''un exercice d''évacuation, vous trouvez un visiteur âgé essoufflé, assis en bas de l''escalier, qui dit "j''arrive, j''arrive".', null, 'Personne en difficulté = on ne laisse pas seul. Communication PC pour info, accompagnement à son rythme jusqu''au point sûr. La sécurité humaine prime sur le chrono d''exercice.',
  1, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack','partie5']::text[], 'challenge',
  (select coalesce(max(display_order), -1) + 1 + 18 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie5' and q2.id not like 'ssiap1-hc-p5-%')),
('ssiap1-hc-p5-q20', 'ssiap1-partie5', 'image-identify', 'Pictogramme rassemblement', 'Ce pictogramme vert ISO 7010 désigne :',
  null, null, 'E007 — Point de rassemblement. Lieu désigné pour comptage post-évacuation. Sa position est notée sur le plan d''évacuation et communiquée aux pompiers.',
  1, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, 'assembly', 'ISO 7010 — E007',
  array['handcrafted','starter-pack','partie5']::text[], 'challenge',
  (select coalesce(max(display_order), -1) + 1 + 19 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie5' and q2.id not like 'ssiap1-hc-p5-%')),
('ssiap1-hc-p5-q21', 'ssiap1-partie5', 'image-identify', 'Sortie de secours', 'Ce panneau vert avec personnage et flèche indique :',
  null, null, 'E003 — Direction issue de secours. Pictogramme luminescent ou rétro-éclairé jalonnant tout le cheminement d''évacuation, jusqu''à la sortie finale.',
  1, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, 'exit-direction', 'ISO 7010 — E003',
  array['handcrafted','starter-pack','partie5']::text[], 'challenge',
  (select coalesce(max(display_order), -1) + 1 + 20 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie5' and q2.id not like 'ssiap1-hc-p5-%')),
('ssiap1-hc-p5-q22', 'ssiap1-partie5', 'image-identify', 'Emplacement extincteur', 'Ce panneau carré rouge avec extincteur blanc signale :',
  null, null, 'F001 — Emplacement extincteur. Doit être visible à 15 m, l''extincteur accessible sans obstacle. Son emplacement figure sur les plans d''évacuation.',
  1, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, 'extinguisher', 'ISO 7010 — F001',
  array['handcrafted','starter-pack','partie5']::text[], 'challenge',
  (select coalesce(max(display_order), -1) + 1 + 21 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie5' and q2.id not like 'ssiap1-hc-p5-%')),
('ssiap1-hc-p5-q23', 'ssiap1-partie5', 'sequence', 'Étapes d''un exercice évacuation', 'Remettez dans l''ordre les étapes d''un exercice d''évacuation réussi :',
  null, null, 'Préparation → Déclenchement → Évacuation → Comptage → Débriefing. Sauter une étape (ex : pas de débriefing) rend l''exercice inutile pédagogiquement.',
  null, null::integer[],
  array[0,1,2,3,4]::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack','partie5']::text[], 'challenge',
  (select coalesce(max(display_order), -1) + 1 + 22 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie5' and q2.id not like 'ssiap1-hc-p5-%')),
('ssiap1-hc-p5-q24', 'ssiap1-partie5', 'sequence', 'Procédure d''accueil pompiers', 'Classez dans l''ordre les actions d''accueil des secours :',
  null, null, 'L''agent SSIAP doit être PRÊT à donner les bonnes infos en quelques secondes : où ? quoi ? combien ? Cela conditionne la rapidité d''intervention.',
  null, null::integer[],
  array[0,1,2,3]::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack','partie5']::text[], 'challenge',
  (select coalesce(max(display_order), -1) + 1 + 23 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie5' and q2.id not like 'ssiap1-hc-p5-%')),
('ssiap1-hc-p5-q25', 'ssiap1-partie5', 'sequence', 'Phases d''un débriefing', 'Ordre logique d''un débriefing post-exercice :',
  null, null, 'À chaud (mémoire fraîche) → analyse → corrections → trace écrite. Sans consignation, l''exercice n''a pas de valeur réglementaire ni d''amélioration continue.',
  null, null::integer[],
  array[0,1,2,3]::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack','partie5']::text[], 'challenge',
  (select coalesce(max(display_order), -1) + 1 + 24 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie5' and q2.id not like 'ssiap1-hc-p5-%')),
('ssiap1-hc-p5-q26', 'ssiap1-partie5', 'ranking', 'Périodicité maintenance', 'Classez ces vérifications de la PLUS FRÉQUENTE à la MOINS FRÉQUENTE :',
  null, null, 'Test BAES : mensuel. Vérif extincteurs : annuelle. Recyclage SSIAP : 3 ans. Épreuve hydraulique : 10 ans. Du plus fréquent au plus espacé.',
  null, null::integer[],
  array[0,1,3,2]::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack','partie5']::text[], 'challenge',
  (select coalesce(max(display_order), -1) + 1 + 25 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie5' and q2.id not like 'ssiap1-hc-p5-%')),
('ssiap1-hc-p5-q27', 'ssiap1-partie5', 'ranking', 'Priorités évacuation', 'Classez ces priorités du PLUS IMPORTANT au MOINS IMPORTANT lors d''une évacuation :',
  null, null, 'Vies humaines > alerte secours > limitation > biens. Les biens sont assurables, pas les vies. Toute hésitation se règle dans cet ordre.',
  null, null::integer[],
  array[0,1,2,3]::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack','partie5']::text[], 'challenge',
  (select coalesce(max(display_order), -1) + 1 + 26 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie5' and q2.id not like 'ssiap1-hc-p5-%')),
('ssiap1-hc-p5-q28', 'ssiap1-partie5', 'ranking', 'Phases temporelles intervention', 'Classez ces phases dans leur ordre d''apparition pendant un sinistre :',
  null, null, 'Détection → Alarme → Évacuation → Pompiers. Ce schéma est universel et structure tous les POI / consignes.',
  null, null::integer[],
  array[0,1,2,3]::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack','partie5']::text[], 'challenge',
  (select coalesce(max(display_order), -1) + 1 + 27 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie5' and q2.id not like 'ssiap1-hc-p5-%')),
('ssiap1-hc-p5-q29', 'ssiap1-partie5', 'matching', 'Document ↔ destinataire', 'Associez chaque document à son destinataire principal :',
  null, null, 'Chaque document a un destinataire et un usage. Confondre les rôles fait perdre du temps en intervention.',
  null, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack','partie5']::text[], 'challenge',
  (select coalesce(max(display_order), -1) + 1 + 28 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie5' and q2.id not like 'ssiap1-hc-p5-%')),
('ssiap1-hc-p5-q30', 'ssiap1-partie5', 'matching', 'Périodicité ↔ contrôle', 'Associez chaque contrôle à sa périodicité réglementaire :',
  null, null, 'Connaître les périodicités = base du métier. Ces 4 sont à mémoriser absolument pour le SSIAP 1.',
  null, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack','partie5']::text[], 'challenge',
  (select coalesce(max(display_order), -1) + 1 + 29 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie5' and q2.id not like 'ssiap1-hc-p5-%')),
('ssiap1-hc-p5-q31', 'ssiap1-partie5', 'matching', 'Acteur ↔ rôle évacuation', 'Associez chaque acteur à son rôle dans le dispositif :',
  null, null, 'Chaque rôle est complémentaire. La défaillance d''un seul peut compromettre toute l''évacuation.',
  null, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack','partie5']::text[], 'challenge',
  (select coalesce(max(display_order), -1) + 1 + 30 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie5' and q2.id not like 'ssiap1-hc-p5-%')),
('ssiap1-hc-p5-q32', 'ssiap1-partie5', 'fill-blank', 'Périodicité exercice ERP', 'Complétez la fréquence réglementaire des exercices :',
  null, null, 'Tous les 6 mois minimum. Consigné au registre de sécurité avec retour d''expérience pour preuve.',
  null, null::integer[],
  null::integer[], array['6','registre de sécurité']::text[],
  null::integer[], array['6','12','3','registre de sécurité','plan d''évacuation','POI','dossier']::text[],
  'Dans un ERP courant, un exercice d''évacuation doit être organisé tous les %1% mois et consigné au %2%.', null, null,
  array['handcrafted','starter-pack','partie5']::text[], 'challenge',
  (select coalesce(max(display_order), -1) + 1 + 31 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie5' and q2.id not like 'ssiap1-hc-p5-%')),
('ssiap1-hc-p5-q33', 'ssiap1-partie5', 'fill-blank', 'Recyclage SSIAP', 'Complétez les obligations de recyclage :',
  null, null, '3 ans / 14 heures (7h théorie + 7h pratique). Sans recyclage, la qualification est suspendue.',
  null, null::integer[],
  null::integer[], array['3','14']::text[],
  null::integer[], array['3','5','2','14','21','7','30']::text[],
  'Le recyclage SSIAP 1 a lieu tous les %1% ans pour une durée de %2% heures.', null, null,
  array['handcrafted','starter-pack','partie5']::text[], 'challenge',
  (select coalesce(max(display_order), -1) + 1 + 32 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie5' and q2.id not like 'ssiap1-hc-p5-%')),
('ssiap1-hc-p5-q34', 'ssiap1-partie5', 'fill-blank', 'Sigles POI / POSI', 'Complétez les acronymes :',
  null, null, 'POI = Plan d''Opération Interne (réaction). POSI = Plan d''Organisation de la Sécurité Incendie (prévention quotidienne).',
  null, null::integer[],
  null::integer[], array['POI','POSI']::text[],
  null::integer[], array['POI','POSI','PPI','SSI','SDIS','EAS']::text[],
  'Le %1% organise la réponse à un sinistre majeur. Le %2% organise au quotidien la prévention dans l''établissement.', null, null,
  array['handcrafted','starter-pack','partie5']::text[], 'challenge',
  (select coalesce(max(display_order), -1) + 1 + 33 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie5' and q2.id not like 'ssiap1-hc-p5-%')),
('ssiap1-hc-p5-q35', 'ssiap1-partie5', 'categories', 'Document obligatoire ou non', 'Classez ces documents selon leur caractère réglementaire en ERP :',
  null, null, 'Obligatoires : registre, plans, notice. Le reste peut être utile mais pas exigé par la commission.',
  null, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack','partie5']::text[], 'challenge',
  (select coalesce(max(display_order), -1) + 1 + 34 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie5' and q2.id not like 'ssiap1-hc-p5-%')),
('ssiap1-hc-p5-q36', 'ssiap1-partie5', 'categories', 'Niveau d''urgence', 'Classez ces situations selon leur niveau de gravité :',
  null, null, 'Bien graduer la réponse évite paniques inutiles ET sous-réactions dangereuses. Le SSIAP doit calibrer.',
  null, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack','partie5']::text[], 'challenge',
  (select coalesce(max(display_order), -1) + 1 + 35 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie5' and q2.id not like 'ssiap1-hc-p5-%')),
('ssiap1-hc-p5-q37', 'ssiap1-partie5', 'categories', 'Acteurs et compétences', 'Classez ces actions par acteur compétent :',
  null, null, 'Chacun son champ. Sortir de son rôle peut engager la responsabilité civile et pénale.',
  null, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack','partie5']::text[], 'challenge',
  (select coalesce(max(display_order), -1) + 1 + 36 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie5' and q2.id not like 'ssiap1-hc-p5-%')),
('ssiap1-hc-p5-q38', 'ssiap1-partie5', 'decision', 'Porte CF bloquée ouverte', 'Arbre de décision :',
  'En ronde du soir, vous constatez qu''une porte coupe-feu du couloir principal est calée ouverte avec un extincteur posé à terre. C''est la 3ème fois cette semaine.', null, 'Refermer + tracer + escalader. Une porte CF calée 30 minutes annule tout le compartimentage. Récidive = problème organisationnel à signaler.',
  null, null::integer[],
  null::integer[], null::text[],
  array[0,0,0]::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack','partie5']::text[], 'challenge',
  (select coalesce(max(display_order), -1) + 1 + 37 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie5' and q2.id not like 'ssiap1-hc-p5-%')),
('ssiap1-hc-p5-q39', 'ssiap1-partie5', 'decision', 'Conflit de procédure', 'Arbre de décision :',
  'Un manager vous demande de couper l''alarme déclenchée à 14h pour ne pas déranger une réunion VIP. Vous savez que la procédure impose une levée de doute physique avant tout réarmement.', null, 'La procédure prime sur l''autorité hiérarchique sur ce type de risque. Ne pas céder protège juridiquement l''agent. Tout doit être tracé.',
  null, null::integer[],
  null::integer[], null::text[],
  array[0,0,0]::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack','partie5']::text[], 'challenge',
  (select coalesce(max(display_order), -1) + 1 + 38 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie5' and q2.id not like 'ssiap1-hc-p5-%'));
commit;
