begin;
insert into public.cc_question_options (question_id, option_index, option_text) values
('ssiap1-hc-p5-q1', 0, 'Plan d''Opération Interne'),
('ssiap1-hc-p5-q1', 1, 'Plan d''Organisation Incendie'),
('ssiap1-hc-p5-q1', 2, 'Procédure d''Opération Immédiate'),
('ssiap1-hc-p5-q1', 3, 'Programme Officiel d''Intervention'),
('ssiap1-hc-p5-q2', 0, 'Tous les ans'),
('ssiap1-hc-p5-q2', 1, 'Tous les 2 ans'),
('ssiap1-hc-p5-q2', 2, 'Tous les 3 ans'),
('ssiap1-hc-p5-q2', 3, 'Tous les 5 ans'),
('ssiap1-hc-p5-q3', 0, 'Tous les mois'),
('ssiap1-hc-p5-q3', 1, 'Tous les 6 mois'),
('ssiap1-hc-p5-q3', 2, 'Une fois par an'),
('ssiap1-hc-p5-q3', 3, 'Tous les 3 ans'),
('ssiap1-hc-p5-q4', 0, 'À 1 mètre du sol'),
('ssiap1-hc-p5-q4', 1, 'Entre 1,30 m et 1,80 m'),
('ssiap1-hc-p5-q4', 2, 'À hauteur de poignée de porte'),
('ssiap1-hc-p5-q4', 3, 'Sous le plafond'),
('ssiap1-hc-p5-q5', 0, 'Vrai'),
('ssiap1-hc-p5-q5', 1, 'Faux'),
('ssiap1-hc-p5-q6', 0, 'Vrai'),
('ssiap1-hc-p5-q6', 1, 'Faux'),
('ssiap1-hc-p5-q7', 0, 'Vrai'),
('ssiap1-hc-p5-q7', 1, 'Faux'),
('ssiap1-hc-p5-q8', 0, 'Vrai'),
('ssiap1-hc-p5-q8', 1, 'Faux'),
('ssiap1-hc-p5-q9', 0, 'Vous êtes ici'),
('ssiap1-hc-p5-q9', 1, 'Itinéraires d''évacuation'),
('ssiap1-hc-p5-q9', 2, 'Numéro SIRET de l''établissement'),
('ssiap1-hc-p5-q9', 3, 'Localisation des moyens de secours'),
('ssiap1-hc-p5-q9', 4, 'Numéros d''appel des secours'),
('ssiap1-hc-p5-q10', 0, 'Registre de sécurité'),
('ssiap1-hc-p5-q10', 1, 'Notice descriptive de sécurité'),
('ssiap1-hc-p5-q10', 2, 'Bilans comptables'),
('ssiap1-hc-p5-q10', 3, 'Rapports de vérifications périodiques'),
('ssiap1-hc-p5-q10', 4, 'Contrats de travail du personnel'),
('ssiap1-hc-p5-q11', 0, 'Identification des risques'),
('ssiap1-hc-p5-q11', 1, 'Organisation des secours'),
('ssiap1-hc-p5-q11', 2, 'Cartographie des dangers'),
('ssiap1-hc-p5-q11', 3, 'Tarifs de prestation'),
('ssiap1-hc-p5-q11', 4, 'Fiches réflexes par scénario'),
('ssiap1-hc-p5-q12', 0, 'Localisation des extincteurs'),
('ssiap1-hc-p5-q12', 1, 'Sens d''évacuation'),
('ssiap1-hc-p5-q12', 2, 'Liste nominative des employés'),
('ssiap1-hc-p5-q12', 3, 'Point de rassemblement'),
('ssiap1-hc-p5-q13', 0, 'Vérifier les locaux'),
('ssiap1-hc-p5-q13', 1, 'Fermer les portes coupe-feu'),
('ssiap1-hc-p5-q13', 2, 'Décider d''évacuer le bâtiment'),
('ssiap1-hc-p5-q13', 3, 'Transmettre l''effectif au point de rassemblement'),
('ssiap1-hc-p5-q14', 0, 'Issues de secours dégagées'),
('ssiap1-hc-p5-q14', 1, 'Compteurs électriques accessibles'),
('ssiap1-hc-p5-q14', 2, 'Caisses du jour réconciliées'),
('ssiap1-hc-p5-q14', 3, 'État des extincteurs'),
('ssiap1-hc-p5-q15', 0, 'Rien — il sera remis à la fin du chantier'),
('ssiap1-hc-p5-q15', 1, 'Mettre un plan provisoire affiché et consigner au registre'),
('ssiap1-hc-p5-q15', 2, 'Évacuer le 2ème étage'),
('ssiap1-hc-p5-q15', 3, 'Faire un courrier formel au directeur uniquement'),
('ssiap1-hc-p5-q16', 0, 'Exécuter — c''est la hiérarchie'),
('ssiap1-hc-p5-q16', 1, 'Refuser et expliquer les risques (panique, accidents, sous-traitants non formés)'),
('ssiap1-hc-p5-q16', 2, 'Faire semblant et déclencher seulement l''alarme'),
('ssiap1-hc-p5-q16', 3, 'Demander un courrier écrit'),
('ssiap1-hc-p5-q17', 0, 'Refuser l''accès'),
('ssiap1-hc-p5-q17', 1, 'Accueillir, présenter les documents disponibles, prévenir la direction'),
('ssiap1-hc-p5-q17', 2, 'Demander un rendez-vous officiel'),
('ssiap1-hc-p5-q17', 3, 'Évacuer l''inspecteur du site'),
('ssiap1-hc-p5-q18', 0, 'Couper l''alarme — fausse alerte probable'),
('ssiap1-hc-p5-q18', 1, 'Allumer immédiatement la lumière de salle, ouvrir les portes, guider vocalement'),
('ssiap1-hc-p5-q18', 2, 'Attendre la fin de la séance'),
('ssiap1-hc-p5-q18', 3, 'Appeler le directeur d''abord'),
('ssiap1-hc-p5-q19', 0, 'Le pousser à continuer'),
('ssiap1-hc-p5-q19', 1, 'S''arrêter avec lui, prévenir le PC, l''aider à atteindre le point de rassemblement à son rythme'),
('ssiap1-hc-p5-q19', 2, 'L''abandonner pour finir l''évacuation'),
('ssiap1-hc-p5-q19', 3, 'L''allonger sur place'),
('ssiap1-hc-p5-q20', 0, 'Un poste de premiers secours'),
('ssiap1-hc-p5-q20', 1, 'Le point de rassemblement après évacuation'),
('ssiap1-hc-p5-q20', 2, 'La salle de pause du personnel'),
('ssiap1-hc-p5-q20', 3, 'L''accueil principal'),
('ssiap1-hc-p5-q21', 0, 'Le sens du courant d''air'),
('ssiap1-hc-p5-q21', 1, 'La direction d''une issue de secours'),
('ssiap1-hc-p5-q21', 2, 'L''accès au stationnement personnel'),
('ssiap1-hc-p5-q21', 3, 'Le poste de garde'),
('ssiap1-hc-p5-q22', 0, 'Une zone à risque incendie'),
('ssiap1-hc-p5-q22', 1, 'L''emplacement d''un extincteur'),
('ssiap1-hc-p5-q22', 2, 'Une coupure d''urgence électrique'),
('ssiap1-hc-p5-q22', 3, 'Une porte CF à fermer');
insert into public.cc_question_items (question_id, item_index, item_text) values
('ssiap1-hc-p5-q23', 0, 'Préparation et information préalable des occupants'),
('ssiap1-hc-p5-q23', 1, 'Déclenchement de l''alarme'),
('ssiap1-hc-p5-q23', 2, 'Évacuation et chronométrage'),
('ssiap1-hc-p5-q23', 3, 'Comptage au point de rassemblement'),
('ssiap1-hc-p5-q23', 4, 'Débriefing et consignation au registre'),
('ssiap1-hc-p5-q24', 0, 'Récupérer plans, clés, badges au PC'),
('ssiap1-hc-p5-q24', 1, 'Se positionner à l''entrée principale'),
('ssiap1-hc-p5-q24', 2, 'Donner l''information précise (lieu, nature, victimes)'),
('ssiap1-hc-p5-q24', 3, 'Guider la première équipe vers le sinistre'),
('ssiap1-hc-p5-q25', 0, 'Collecte des observations à chaud'),
('ssiap1-hc-p5-q25', 1, 'Analyse des points forts et faibles'),
('ssiap1-hc-p5-q25', 2, 'Identification des actions correctives'),
('ssiap1-hc-p5-q25', 3, 'Consignation écrite au registre'),
('ssiap1-hc-p5-q26', 0, 'Test BAES par l''exploitant'),
('ssiap1-hc-p5-q26', 1, 'Vérification annuelle extincteurs'),
('ssiap1-hc-p5-q26', 2, 'Épreuve hydraulique extincteurs'),
('ssiap1-hc-p5-q26', 3, 'Recyclage SSIAP 1'),
('ssiap1-hc-p5-q27', 0, 'Sauver les personnes'),
('ssiap1-hc-p5-q27', 1, 'Avertir les secours'),
('ssiap1-hc-p5-q27', 2, 'Limiter la propagation (fermer les portes)'),
('ssiap1-hc-p5-q27', 3, 'Préserver les biens'),
('ssiap1-hc-p5-q28', 0, 'Détection / découverte'),
('ssiap1-hc-p5-q28', 1, 'Alerte interne (alarme)'),
('ssiap1-hc-p5-q28', 2, 'Évacuation des occupants'),
('ssiap1-hc-p5-q28', 3, 'Intervention des secours extérieurs');
insert into public.cc_question_pairs (question_id, pair_index, left_text, right_text) values
('ssiap1-hc-p5-q29', 0, 'Registre de sécurité', 'Commission de sécurité'),
('ssiap1-hc-p5-q29', 1, 'Plan d''évacuation', 'Public / occupants'),
('ssiap1-hc-p5-q29', 2, 'Plan d''intervention', 'Sapeurs-pompiers'),
('ssiap1-hc-p5-q29', 3, 'Notice descriptive de sécurité', 'Maître d''œuvre / architecte'),
('ssiap1-hc-p5-q30', 0, 'Test BAES', 'Mensuel'),
('ssiap1-hc-p5-q30', 1, 'Vérification extincteur', 'Annuel'),
('ssiap1-hc-p5-q30', 2, 'Visite ERP 3ème catégorie', '2 ans'),
('ssiap1-hc-p5-q30', 3, 'Épreuve hydraulique extincteur', '10 ans'),
('ssiap1-hc-p5-q31', 0, 'Guide-file', 'Ouvre la marche, dirige vers la sortie'),
('ssiap1-hc-p5-q31', 1, 'Serre-file', 'Ferme la marche, vérifie les locaux'),
('ssiap1-hc-p5-q31', 2, 'SSIAP 1', 'Met en sécurité, accueille les secours'),
('ssiap1-hc-p5-q31', 3, 'Responsable évacuation', 'Décide et coordonne');
insert into public.cc_question_categories (question_id, category_index, category_id, category_label) values
('ssiap1-hc-p5-q35', 0, 'oblig', '📌 Obligatoire'),
('ssiap1-hc-p5-q35', 1, 'reco', '💡 Recommandé / Facultatif'),
('ssiap1-hc-p5-q36', 0, 'rou', '🔴 Sinistre — évacuation'),
('ssiap1-hc-p5-q36', 1, 'orange', '🟠 Alerte — vérification urgente'),
('ssiap1-hc-p5-q36', 2, 'jaune', '🟡 Anomalie — à signaler'),
('ssiap1-hc-p5-q37', 0, 'ssiap', '🛡️ SSIAP 1'),
('ssiap1-hc-p5-q37', 1, 'pomp', '🚒 Sapeurs-pompiers'),
('ssiap1-hc-p5-q37', 2, 'dir', '👔 Direction / exploitant');
insert into public.cc_question_category_items (question_id, item_index, item_text, correct_category) values
('ssiap1-hc-p5-q35', 0, 'Registre de sécurité', 'oblig'),
('ssiap1-hc-p5-q35', 1, 'Plan d''évacuation à chaque niveau', 'oblig'),
('ssiap1-hc-p5-q35', 2, 'Notice descriptive de sécurité', 'oblig'),
('ssiap1-hc-p5-q35', 3, 'Cartouche de service du PC', 'reco'),
('ssiap1-hc-p5-q35', 4, 'Tableau d''avancement formations', 'reco'),
('ssiap1-hc-p5-q36', 0, 'Fumée visible dans un local', 'rou'),
('ssiap1-hc-p5-q36', 1, 'Alarme SSI active sans confirmation', 'orange'),
('ssiap1-hc-p5-q36', 2, 'Voyant défaut technique sur ECS', 'jaune'),
('ssiap1-hc-p5-q36', 3, 'Porte CF bloquée ouverte par cale', 'jaune'),
('ssiap1-hc-p5-q36', 4, 'Odeur de brûlé dans une gaine technique', 'orange'),
('ssiap1-hc-p5-q37', 0, 'Effectuer une ronde de prévention', 'ssiap'),
('ssiap1-hc-p5-q37', 1, 'Décider de la fermeture administrative', 'dir'),
('ssiap1-hc-p5-q37', 2, 'Engager une lance à incendie 70 mm', 'pomp'),
('ssiap1-hc-p5-q37', 3, 'Tenir le registre de sécurité', 'ssiap'),
('ssiap1-hc-p5-q37', 4, 'Signer le permis de feu', 'dir');
insert into public.cc_question_decision_steps (question_id, step_index, step_question, options) values
('ssiap1-hc-p5-q38', 0, 'ÉTAPE 1 — Action immédiate ?', '[{"text":"Refermer la porte et noter au registre","nextStep":1},{"text":"Laisser ouvert, c''est bientôt fini","nextStep":99},{"text":"Démonter la porte par la maintenance","nextStep":99}]'::jsonb),
('ssiap1-hc-p5-q38', 1, 'ÉTAPE 2 — Comportement récidivant. Que faites-vous ?', '[{"text":"Identifier le service responsable et alerter le chef d''équipe","nextStep":2},{"text":"Mettre un cadenas","nextStep":99},{"text":"Ne rien dire","nextStep":99}]'::jsonb),
('ssiap1-hc-p5-q38', 2, 'ÉTAPE 3 — La traçabilité ?', '[{"text":"Noter chaque occurrence au registre + photo + escalade hiérarchique","nextStep":null},{"text":"Seulement à l''oral","nextStep":null},{"text":"Tweet interne","nextStep":null}]'::jsonb),
('ssiap1-hc-p5-q39', 0, 'ÉTAPE 1 — Réponse immédiate ?', '[{"text":"Refuser poliment et expliquer la procédure","nextStep":1},{"text":"Couper — c''est un manager","nextStep":99},{"text":"Faire semblant de couper","nextStep":99}]'::jsonb),
('ssiap1-hc-p5-q39', 1, 'ÉTAPE 2 — Le manager insiste fortement.', '[{"text":"Maintenir le refus, contacter immédiatement le chef de service sécurité","nextStep":2},{"text":"Céder pour ne pas créer de tension","nextStep":99},{"text":"Quitter le poste","nextStep":99}]'::jsonb),
('ssiap1-hc-p5-q39', 2, 'ÉTAPE 3 — Une fois la levée de doute négative effectuée.', '[{"text":"Réarmer + consigner l''incident au registre + transmettre","nextStep":null},{"text":"Réarmer sans rien dire","nextStep":null},{"text":"Modifier la fiche de poste","nextStep":null}]'::jsonb);
commit;
