begin;
insert into public.cc_question_options (question_id, option_index, option_text) values
('ssiap1-hc-p1-ext-q1', 0, 'La température minimale où le liquide émet assez de vapeurs pour s''enflammer en présence d''une flamme'),
('ssiap1-hc-p1-ext-q1', 1, 'La température à laquelle le liquide bout'),
('ssiap1-hc-p1-ext-q1', 2, 'La température d''auto-inflammation sans source d''ignition'),
('ssiap1-hc-p1-ext-q1', 3, 'La quantité de chaleur dégagée par la combustion'),
('ssiap1-hc-p1-ext-q2', 0, 'Conduction'),
('ssiap1-hc-p1-ext-q2', 1, 'Convection'),
('ssiap1-hc-p1-ext-q2', 2, 'Rayonnement'),
('ssiap1-hc-p1-ext-q2', 3, 'Combustion lente'),
('ssiap1-hc-p1-ext-q3', 0, '10 ppm'),
('ssiap1-hc-p1-ext-q3', 1, '100 ppm'),
('ssiap1-hc-p1-ext-q3', 2, '400 ppm'),
('ssiap1-hc-p1-ext-q3', 3, '3000 ppm et plus'),
('ssiap1-hc-p1-ext-q4', 0, 'Résistance, Étanchéité, Isolation thermique'),
('ssiap1-hc-p1-ext-q4', 1, 'Réaction, Efficacité, Inflammation'),
('ssiap1-hc-p1-ext-q4', 2, 'Résistance Européenne d''Incendie'),
('ssiap1-hc-p1-ext-q4', 3, 'Recyclage Énergétique d''Incendie'),
('ssiap1-hc-p1-ext-q5', 0, 'Vrai'),
('ssiap1-hc-p1-ext-q5', 1, 'Faux'),
('ssiap1-hc-p1-ext-q6', 0, 'Vrai'),
('ssiap1-hc-p1-ext-q6', 1, 'Faux'),
('ssiap1-hc-p1-ext-q7', 0, 'Vrai'),
('ssiap1-hc-p1-ext-q7', 1, 'Faux'),
('ssiap1-hc-p1-ext-q8', 0, 'Brûlures cutanées'),
('ssiap1-hc-p1-ext-q8', 1, 'Asphyxie par les fumées'),
('ssiap1-hc-p1-ext-q8', 2, 'Hyperthermie'),
('ssiap1-hc-p1-ext-q8', 3, 'Œdème pulmonaire'),
('ssiap1-hc-p1-ext-q8', 4, 'Choc thermique'),
('ssiap1-hc-p1-ext-q9', 0, 'Combustible'),
('ssiap1-hc-p1-ext-q9', 1, 'Comburant (oxygène)'),
('ssiap1-hc-p1-ext-q9', 2, 'Énergie d''activation'),
('ssiap1-hc-p1-ext-q9', 3, 'Réaction en chaîne'),
('ssiap1-hc-p1-ext-q9', 4, 'Pression atmosphérique élevée'),
('ssiap1-hc-p1-ext-q10', 0, 'CO (monoxyde de carbone)'),
('ssiap1-hc-p1-ext-q10', 1, 'HCN (acide cyanhydrique)'),
('ssiap1-hc-p1-ext-q10', 2, 'HCl (acide chlorhydrique)'),
('ssiap1-hc-p1-ext-q10', 3, 'O2 pur'),
('ssiap1-hc-p1-ext-q10', 4, 'SO2 (dioxyde de soufre)'),
('ssiap1-hc-p1-ext-q11', 0, 'CO2'),
('ssiap1-hc-p1-ext-q11', 1, 'Mousse AFFF'),
('ssiap1-hc-p1-ext-q11', 2, 'Sable'),
('ssiap1-hc-p1-ext-q11', 3, 'Oxygène pur'),
('ssiap1-hc-p1-ext-q12', 0, 'Court-circuit électrique'),
('ssiap1-hc-p1-ext-q12', 1, 'Travaux par points chauds'),
('ssiap1-hc-p1-ext-q12', 2, 'Cigarette mal éteinte'),
('ssiap1-hc-p1-ext-q12', 3, 'Foudre direct sur bâtiment'),
('ssiap1-hc-p1-ext-q13', 0, 'Ouvrir pour voir'),
('ssiap1-hc-p1-ext-q13', 1, 'Ne pas ouvrir, alerter le PC, déclencher le DM le plus proche'),
('ssiap1-hc-p1-ext-q13', 2, 'Forcer la porte avec un extincteur'),
('ssiap1-hc-p1-ext-q13', 3, 'Courir chercher un collègue avant tout'),
('ssiap1-hc-p1-ext-q14', 0, 'Allumer la lumière pour voir'),
('ssiap1-hc-p1-ext-q14', 1, 'Couper l''arrivée gaz, ne pas créer d''étincelle, ventiler, évacuer, alerter'),
('ssiap1-hc-p1-ext-q14', 2, 'Vaporiser de l''eau pour disperser le gaz'),
('ssiap1-hc-p1-ext-q14', 3, 'Approcher pour vérifier l''origine'),
('ssiap1-hc-p1-ext-q15', 0, 'Un risque de chute de hauteur'),
('ssiap1-hc-p1-ext-q15', 1, 'Un danger électrique — risque d''électrocution'),
('ssiap1-hc-p1-ext-q15', 2, 'Une zone réservée aux secours'),
('ssiap1-hc-p1-ext-q15', 3, 'Un risque de glissade'),
('ssiap1-hc-p1-ext-q16', 0, 'L''emplacement d''un extincteur portatif'),
('ssiap1-hc-p1-ext-q16', 1, 'Une zone à risque incendie'),
('ssiap1-hc-p1-ext-q16', 2, 'Le PC sécurité'),
('ssiap1-hc-p1-ext-q16', 3, 'Un local technique fermé à clé');
insert into public.cc_question_items (question_id, item_index, item_text) values
('ssiap1-hc-p1-ext-q17', 0, 'Pull — Tirer la goupille de sécurité'),
('ssiap1-hc-p1-ext-q17', 1, 'Aim — Viser la base des flammes'),
('ssiap1-hc-p1-ext-q17', 2, 'Squeeze — Presser la poignée'),
('ssiap1-hc-p1-ext-q17', 3, 'Sweep — Balayer de gauche à droite'),
('ssiap1-hc-p1-ext-q18', 0, 'Phase de naissance (T° basse, fumée légère)'),
('ssiap1-hc-p1-ext-q18', 1, 'Phase de développement (T° monte, flammes visibles)'),
('ssiap1-hc-p1-ext-q18', 2, 'Embrasement généralisé (flashover, ~500°C)'),
('ssiap1-hc-p1-ext-q18', 3, 'Phase de décrescence (combustible épuisé)'),
('ssiap1-hc-p1-ext-q19', 0, 'Point éclair de l''essence (-43 °C)'),
('ssiap1-hc-p1-ext-q19', 1, 'Point auto-inflammation gasoil (~250 °C)'),
('ssiap1-hc-p1-ext-q19', 2, 'Flashover plafond (~500 °C)'),
('ssiap1-hc-p1-ext-q19', 3, 'Combustion bois en pleine flamme (~1000 °C)'),
('ssiap1-hc-p1-ext-q20', 0, 'Mousse polyuréthane (PUR)'),
('ssiap1-hc-p1-ext-q20', 1, 'Bois résineux (sapin)'),
('ssiap1-hc-p1-ext-q20', 2, 'Bois feuillu (chêne)'),
('ssiap1-hc-p1-ext-q20', 3, 'Béton cellulaire');
insert into public.cc_question_pairs (question_id, pair_index, left_text, right_text) values
('ssiap1-hc-p1-ext-q21', 0, 'Classe A', 'Bois, papier, textile'),
('ssiap1-hc-p1-ext-q21', 1, 'Classe B', 'Essence, alcool, peinture'),
('ssiap1-hc-p1-ext-q21', 2, 'Classe C', 'Méthane, propane, butane'),
('ssiap1-hc-p1-ext-q21', 3, 'Classe F', 'Huile de friture'),
('ssiap1-hc-p1-ext-q22', 0, 'Conduction', 'Transfert par contact direct des matériaux'),
('ssiap1-hc-p1-ext-q22', 1, 'Convection', 'Transfert par les fumées et gaz chauds'),
('ssiap1-hc-p1-ext-q22', 2, 'Rayonnement', 'Transfert par ondes infrarouges'),
('ssiap1-hc-p1-ext-q22', 3, 'Projection', 'Particules incandescentes (escarbilles)');
insert into public.cc_question_categories (question_id, category_index, category_id, category_label) values
('ssiap1-hc-p1-ext-q25', 0, 'A', '🟫 Classe A — solides'),
('ssiap1-hc-p1-ext-q25', 1, 'B', '🟡 Classe B — liquides'),
('ssiap1-hc-p1-ext-q25', 2, 'C', '⚪ Classe C — gaz'),
('ssiap1-hc-p1-ext-q25', 3, 'F', '🟧 Classe F — huiles cuisson');
insert into public.cc_question_category_items (question_id, item_index, item_text, correct_category) values
('ssiap1-hc-p1-ext-q25', 0, 'Carton', 'A'),
('ssiap1-hc-p1-ext-q25', 1, 'Essence', 'B'),
('ssiap1-hc-p1-ext-q25', 2, 'Bois sec', 'A'),
('ssiap1-hc-p1-ext-q25', 3, 'Propane bouteille', 'C'),
('ssiap1-hc-p1-ext-q25', 4, 'Acétone', 'B'),
('ssiap1-hc-p1-ext-q25', 5, 'Huile de tournesol cuite', 'F');
insert into public.cc_question_decision_steps (question_id, step_index, step_question, options) values
('ssiap1-hc-p1-ext-q26', 0, 'ÉTAPE 1 — Première action ?', '[{"text":"Déclencher le DM avant tout","nextStep":1},{"text":"Foncer pour étouffer avec mes mains","nextStep":99},{"text":"Sortir et fermer la porte","nextStep":99}]'::jsonb),
('ssiap1-hc-p1-ext-q26', 1, 'ÉTAPE 2 — DM enclenché. Action suivante ?', '[{"text":"Saisir l''extincteur, viser la base, balayer","nextStep":2},{"text":"Attendre les pompiers","nextStep":99},{"text":"Verser de l''eau dessus directement","nextStep":99}]'::jsonb),
('ssiap1-hc-p1-ext-q26', 2, 'ÉTAPE 3 — Le feu est éteint. Que faire ?', '[{"text":"Vérifier l''absence de reprise + signaler + consigner au registre","nextStep":null},{"text":"Reprendre le travail","nextStep":null},{"text":"Remettre l''extincteur en place","nextStep":null}]'::jsonb);
commit;
