begin;
delete from public.cc_questions where id like 'ssiap1-hc-p1-ext-%';
insert into public.cc_questions
  (id, module_id, type, title, question, scenario, situation, explanation,
   correct_answer, correct_answers, correct_order, correct_blanks, correct_path,
   word_bank, sentence, image_key, image_desc, tags, pool, display_order)
values
('ssiap1-hc-p1-ext-q1', 'ssiap1-partie1', 'quiz', 'Point éclair', 'Le point éclair d''un liquide inflammable correspond à :',
  null, null, 'Point éclair (flash point) = T° minimale d''émission de vapeurs inflammables. À ne pas confondre avec le point d''auto-inflammation (sans source extérieure) ni avec le pouvoir calorifique.',
  0, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack','partie1-ext']::text[], 'challenge',
  (select coalesce(max(display_order), -1) + 1 + 0 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie1' and q2.id not like 'ssiap1-hc-p1-ext-%')),
('ssiap1-hc-p1-ext-q2', 'ssiap1-partie1', 'quiz', 'Modes de propagation thermique', 'Quel est le mode de propagation thermique le plus rapide à grande distance ?',
  null, null, 'Rayonnement = ondes infrarouges, instantané, traverse l''air. La convection (fumées chaudes) déplace la chaleur dans le bâtiment. La conduction se fait par contact direct (lent).',
  2, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack','partie1-ext']::text[], 'challenge',
  (select coalesce(max(display_order), -1) + 1 + 1 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie1' and q2.id not like 'ssiap1-hc-p1-ext-%')),
('ssiap1-hc-p1-ext-q3', 'ssiap1-partie1', 'quiz', 'CO mortel', 'À partir de quelle concentration le monoxyde de carbone (CO) devient-il rapidement mortel pour un adulte ?',
  null, null, 'Au-delà de 3000 ppm (0,3 %), perte de conscience en quelques minutes, décès rapide. À 100 ppm = symptômes en heures. Le CO se fixe sur l''hémoglobine 200× plus que l''O2.',
  3, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack','partie1-ext']::text[], 'challenge',
  (select coalesce(max(display_order), -1) + 1 + 2 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie1' and q2.id not like 'ssiap1-hc-p1-ext-%')),
('ssiap1-hc-p1-ext-q4', 'ssiap1-partie1', 'quiz', 'REI signification', 'Que signifie le sigle "REI" dans le classement de résistance au feu ?',
  null, null, 'R = Résistance mécanique (capacité portante). E = Étanchéité (aux flammes et fumées). I = Isolation thermique (face non exposée < 140°C). REI 60 = tient les 3 critères 60 minutes.',
  0, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack','partie1-ext']::text[], 'challenge',
  (select coalesce(max(display_order), -1) + 1 + 3 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie1' and q2.id not like 'ssiap1-hc-p1-ext-%')),
('ssiap1-hc-p1-ext-q5', 'ssiap1-partie1', 'true-false', 'Auto-inflammation', 'Un liquide peut s''enflammer sans flamme ni étincelle si sa température dépasse son point d''auto-inflammation.',
  null, null, 'VRAI — Le point d''auto-inflammation est la T° à laquelle un combustible s''enflamme spontanément (ex : essence ~280°C, diesel ~250°C). C''est pourquoi on évite chaud + carburant.',
  0, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack','partie1-ext']::text[], 'challenge',
  (select coalesce(max(display_order), -1) + 1 + 4 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie1' and q2.id not like 'ssiap1-hc-p1-ext-%')),
('ssiap1-hc-p1-ext-q6', 'ssiap1-partie1', 'true-false', 'CO2 plus lourd que l''air', 'Le CO2 est plus lourd que l''air et stagne donc en partie basse des locaux.',
  null, null, 'VRAI — Densité CO2 ≈ 1,5 vs 1 pour l''air. Risque d''asphyxie en fosse, sous-sol, salle serveur après décharge d''une installation CO2. Toujours ventiler avant d''entrer.',
  0, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack','partie1-ext']::text[], 'challenge',
  (select coalesce(max(display_order), -1) + 1 + 5 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie1' and q2.id not like 'ssiap1-hc-p1-ext-%')),
('ssiap1-hc-p1-ext-q7', 'ssiap1-partie1', 'true-false', 'Eau et feu d''huile', 'On peut éteindre un feu d''huile de cuisson en jetant de l''eau dessus.',
  null, null, 'FAUX — Eau + huile à 300°C = vaporisation explosive (boilover). L''huile est projetée en gouttelettes enflammées. Utiliser un extincteur classe F ou un couvercle/textile humide.',
  1, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack','partie1-ext']::text[], 'challenge',
  (select coalesce(max(display_order), -1) + 1 + 6 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie1' and q2.id not like 'ssiap1-hc-p1-ext-%')),
('ssiap1-hc-p1-ext-q8', 'ssiap1-partie1', 'multiple-select', 'Effets de la chaleur sur le corps', 'Quels sont les effets DIRECTS de la chaleur intense sur l''organisme ? (plusieurs réponses)',
  null, null, 'Brûlures, hyperthermie, choc thermique = effets directs. Asphyxie et œdème pulmonaire = effets des fumées (toxicité), pas de la chaleur seule.',
  null, array[0,2,4]::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack','partie1-ext']::text[], 'challenge',
  (select coalesce(max(display_order), -1) + 1 + 7 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie1' and q2.id not like 'ssiap1-hc-p1-ext-%')),
('ssiap1-hc-p1-ext-q9', 'ssiap1-partie1', 'multiple-select', 'Conditions du tétraèdre', 'Quelles conditions doivent être réunies pour qu''un feu se développe ?',
  null, null, 'Les 4 piliers du tétraèdre. La pression normale suffit (l''air contient 21 % O2). Un feu peut exister à basse altitude comme en montagne.',
  null, array[0,1,2,3]::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack','partie1-ext']::text[], 'challenge',
  (select coalesce(max(display_order), -1) + 1 + 8 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie1' and q2.id not like 'ssiap1-hc-p1-ext-%')),
('ssiap1-hc-p1-ext-q10', 'ssiap1-partie1', 'multiple-select', 'Composants de la fumée', 'Quels gaz toxiques peut-on retrouver dans la fumée d''un incendie ?',
  null, null, 'CO + HCN + HCl + SO2 selon les matériaux qui brûlent (plastiques, textiles, soufre). L''O2 est CONSOMMÉ par le feu, pas produit.',
  null, array[0,1,2,4]::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack','partie1-ext']::text[], 'challenge',
  (select coalesce(max(display_order), -1) + 1 + 9 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie1' and q2.id not like 'ssiap1-hc-p1-ext-%')),
('ssiap1-hc-p1-ext-q11', 'ssiap1-partie1', 'find-intruder', 'Pas un agent extincteur', 'Lequel de ces éléments N''EST PAS un agent extincteur reconnu ?',
  null, null, 'L''oxygène pur ALIMENTE le feu, il ne l''éteint pas. Sable = étouffement (utilisé pour métaux ou hydrocarbures). CO2 et mousse = agents standards.',
  3, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack','partie1-ext']::text[], 'challenge',
  (select coalesce(max(display_order), -1) + 1 + 10 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie1' and q2.id not like 'ssiap1-hc-p1-ext-%')),
('ssiap1-hc-p1-ext-q12', 'ssiap1-partie1', 'find-intruder', 'Pas une cause d''incendie courante', 'Laquelle de ces causes est LA MOINS courante en milieu professionnel ?',
  null, null, 'Court-circuits, points chauds, cigarettes représentent la majorité. La foudre est rare grâce aux paratonnerres et reste localisée. Cause statistique mineure en milieu pro.',
  3, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack','partie1-ext']::text[], 'challenge',
  (select coalesce(max(display_order), -1) + 1 + 11 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie1' and q2.id not like 'ssiap1-hc-p1-ext-%')),
('ssiap1-hc-p1-ext-q13', 'ssiap1-partie1', 'scenario', 'Fumée légère sous une porte', 'Action immédiate ?',
  'Vous patrouillez au sous-sol. Sous une porte de local technique, vous voyez une légère fumée blanche. La porte est tiède. Vous êtes seul avec une radio.', null, 'Porte tiède + fumée blanche = feu probable. NE JAMAIS OUVRIR (apport d''O2 → flashover/backdraft possible). Alerte → DM → attente sécurisée. La radio est l''outil prioritaire.',
  1, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack','partie1-ext']::text[], 'challenge',
  (select coalesce(max(display_order), -1) + 1 + 12 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie1' and q2.id not like 'ssiap1-hc-p1-ext-%')),
('ssiap1-hc-p1-ext-q14', 'ssiap1-partie1', 'scenario', 'Chaudière qui claque', 'Conduite à tenir ?',
  'Dans une chaufferie gaz, vous entendez un claquement et sentez une odeur de gaz forte. Aucune fumée, aucune flamme.', null, 'Fuite gaz = priorité ABSOLUE pas d''étincelle. Couper amont (vanne combustible), ouvrir aération, évacuer la zone, alerter pompiers via portable hors zone. Toute étincelle = explosion.',
  1, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack','partie1-ext']::text[], 'challenge',
  (select coalesce(max(display_order), -1) + 1 + 13 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie1' and q2.id not like 'ssiap1-hc-p1-ext-%')),
('ssiap1-hc-p1-ext-q15', 'ssiap1-partie1', 'image-identify', 'Risque incendie générique', 'Ce panneau triangulaire jaune désigne :',
  null, null, 'W012 — Avertissement risque électrique. Présent près des armoires HT, transformateurs. Ne jamais intervenir sans habilitation (B0, BR, BC...).',
  1, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, 'electrical-hazard', 'ISO 7010 — W012',
  array['handcrafted','starter-pack','partie1-ext']::text[], 'challenge',
  (select coalesce(max(display_order), -1) + 1 + 14 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie1' and q2.id not like 'ssiap1-hc-p1-ext-%')),
('ssiap1-hc-p1-ext-q16', 'ssiap1-partie1', 'image-identify', 'Extincteur', 'Ce panneau rouge avec extincteur blanc indique :',
  null, null, 'F001 — Emplacement extincteur. Visible à 15 m, accessible sans obstacle. Doit figurer sur le plan d''évacuation avec son type (eau, CO2, poudre).',
  0, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, 'extinguisher', 'ISO 7010 — F001',
  array['handcrafted','starter-pack','partie1-ext']::text[], 'challenge',
  (select coalesce(max(display_order), -1) + 1 + 15 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie1' and q2.id not like 'ssiap1-hc-p1-ext-%')),
('ssiap1-hc-p1-ext-q17', 'ssiap1-partie1', 'sequence', 'Ordre PASS extincteur', 'Remettez dans l''ordre les étapes d''utilisation d''un extincteur (méthode PASS) :',
  null, null, 'P-A-S-S : Pull, Aim, Squeeze, Sweep. Vous tirez la goupille AVANT de viser. Toujours viser la BASE des flammes, pas le sommet. Maintenir 1-3 m de distance.',
  null, null::integer[],
  array[0,1,2,3]::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack','partie1-ext']::text[], 'challenge',
  (select coalesce(max(display_order), -1) + 1 + 16 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie1' and q2.id not like 'ssiap1-hc-p1-ext-%')),
('ssiap1-hc-p1-ext-q18', 'ssiap1-partie1', 'sequence', 'Phases combustion', 'Classez ces phases dans l''ordre du développement d''un incendie :',
  null, null, 'Naissance → développement → flashover → décrescence. Le flashover est le point critique non-retour : tous les matériaux s''enflamment simultanément.',
  null, null::integer[],
  array[0,1,2,3]::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack','partie1-ext']::text[], 'challenge',
  (select coalesce(max(display_order), -1) + 1 + 17 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie1' and q2.id not like 'ssiap1-hc-p1-ext-%')),
('ssiap1-hc-p1-ext-q19', 'ssiap1-partie1', 'ranking', 'Classement températures', 'Classez ces températures du PLUS BAS au PLUS HAUT :',
  null, null, 'Essence -43°C → gasoil 250°C → flashover 500°C → bois 1000°C. À retenir : essence très volatile, gasoil moins, flammes très chaudes.',
  null, null::integer[],
  array[0,1,2,3]::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack','partie1-ext']::text[], 'challenge',
  (select coalesce(max(display_order), -1) + 1 + 18 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie1' and q2.id not like 'ssiap1-hc-p1-ext-%')),
('ssiap1-hc-p1-ext-q20', 'ssiap1-partie1', 'ranking', 'Classement vitesse propagation', 'Classez ces matériaux du PLUS RAPIDE au PLUS LENT à propager le feu :',
  null, null, 'Mousse PU = très inflammable, très vite (canapés, matelas !). Sapin résineux > chêne (densité). Béton = quasi-incombustible (Euroclasse A1).',
  null, null::integer[],
  array[0,1,2,3]::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack','partie1-ext']::text[], 'challenge',
  (select coalesce(max(display_order), -1) + 1 + 19 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie1' and q2.id not like 'ssiap1-hc-p1-ext-%')),
('ssiap1-hc-p1-ext-q21', 'ssiap1-partie1', 'matching', 'Classe ↔ exemples', 'Associez chaque classe de feu à un exemple typique :',
  null, null, 'A = solides (carbonisation). B = liquides inflammables. C = gaz. D = métaux (Mg, Al, Na...). F = huiles cuisson. Connaître la classe → choisir l''extincteur.',
  null, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack','partie1-ext']::text[], 'challenge',
  (select coalesce(max(display_order), -1) + 1 + 20 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie1' and q2.id not like 'ssiap1-hc-p1-ext-%')),
('ssiap1-hc-p1-ext-q22', 'ssiap1-partie1', 'matching', 'Mode propagation ↔ description', 'Associez chaque mode de propagation thermique à sa description :',
  null, null, 'Les 4 modes opèrent simultanément en incendie réel. Comprendre les 4 = comprendre comment un feu passe d''une pièce à une autre.',
  null, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack','partie1-ext']::text[], 'challenge',
  (select coalesce(max(display_order), -1) + 1 + 21 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie1' and q2.id not like 'ssiap1-hc-p1-ext-%')),
('ssiap1-hc-p1-ext-q23', 'ssiap1-partie1', 'fill-blank', 'Triangle vs tétraèdre', 'Complétez la définition :',
  null, null, 'Triangle : combustible + comburant + énergie d''activation = 3 éléments. Tétraèdre : ajoute la réaction en chaîne (auto-entretien moléculaire).',
  null, null::integer[],
  null::integer[], array['3','la réaction en chaîne']::text[],
  null::integer[], array['3','4','5','la réaction en chaîne','l''oxygène','la pression','le combustible']::text[],
  'Le triangle du feu comporte %1% éléments. Le tétraèdre du feu en ajoute un quatrième : %2%.', null, null,
  array['handcrafted','starter-pack','partie1-ext']::text[], 'challenge',
  (select coalesce(max(display_order), -1) + 1 + 22 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie1' and q2.id not like 'ssiap1-hc-p1-ext-%')),
('ssiap1-hc-p1-ext-q24', 'ssiap1-partie1', 'fill-blank', 'Limites d''inflammabilité', 'Complétez les limites de l''air respirable et de combustion :',
  null, null, 'Air = 21 % O2 + 78 % N2 + 1 % autres. Combustion s''arrête vers 15 % O2. Principe des systèmes hypoxiques (salles serveur) : maintenir 14-17 % d''O2.',
  null, null::integer[],
  null::integer[], array['21','15']::text[],
  null::integer[], array['21','15','78','5','30','10','25']::text[],
  'L''air contient %1% % d''oxygène. La combustion s''arrête en dessous de %2% % d''oxygène.', null, null,
  array['handcrafted','starter-pack','partie1-ext']::text[], 'challenge',
  (select coalesce(max(display_order), -1) + 1 + 23 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie1' and q2.id not like 'ssiap1-hc-p1-ext-%')),
('ssiap1-hc-p1-ext-q25', 'ssiap1-partie1', 'categories', 'Classer par classe de feu', 'Classez ces combustibles dans la bonne classe de feu :',
  null, null, 'Classer correctement = choisir le bon extincteur. Erreur classique : utiliser eau sur classe B (étend le feu) ou CO2 sur F (projection).',
  null, null::integer[],
  null::integer[], null::text[],
  null::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack','partie1-ext']::text[], 'challenge',
  (select coalesce(max(display_order), -1) + 1 + 24 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie1' and q2.id not like 'ssiap1-hc-p1-ext-%')),
('ssiap1-hc-p1-ext-q26', 'ssiap1-partie1', 'decision', 'Feu naissant dans une corbeille', 'Arbre de décision face à un départ de feu :',
  'Dans un bureau, une corbeille à papier prend feu. Les flammes font 30 cm. Vous êtes à 2 m, un extincteur eau pulvérisée + additif est à 5 m, et le DM est à 8 m.', null, 'DM en premier (alerte interne) → extinction si feu naissant (< 1 m²) → vérification reprise + traçabilité. Toujours signaler même si feu éteint : déclaration sinistre + ré-armement extincteur.',
  null, null::integer[],
  null::integer[], null::text[],
  array[0,0,0]::integer[], null::text[],
  null, null, null,
  array['handcrafted','starter-pack','partie1-ext']::text[], 'challenge',
  (select coalesce(max(display_order), -1) + 1 + 25 from public.cc_questions q2 where q2.module_id = 'ssiap1-partie1' and q2.id not like 'ssiap1-hc-p1-ext-%'));
commit;
