begin;
insert into public.cc_question_options (question_id,option_index,option_text) values
('ssiap1-hc-p2-ext-q1',0,'R.123-1 et suivants'),
('ssiap1-hc-p2-ext-q1',1,'L.111-1'),
('ssiap1-hc-p2-ext-q1',2,'D.541-2'),
('ssiap1-hc-p2-ext-q1',3,'CO 12'),
('ssiap1-hc-p2-ext-q2',0,'100 personnes'),
('ssiap1-hc-p2-ext-q2',1,'300 personnes'),
('ssiap1-hc-p2-ext-q2',2,'Effectif sous le seuil par type'),
('ssiap1-hc-p2-ext-q2',3,'Aucune limite, c''est la surface qui compte'),
('ssiap1-hc-p2-ext-q3',0,'A1'),
('ssiap1-hc-p2-ext-q3',1,'B'),
('ssiap1-hc-p2-ext-q3',2,'D'),
('ssiap1-hc-p2-ext-q3',3,'F'),
('ssiap1-hc-p2-ext-q4',0,'Refroidir les locaux'),
('ssiap1-hc-p2-ext-q4',1,'Éliminer la fumée pour permettre l''évacuation et l''intervention'),
('ssiap1-hc-p2-ext-q4',2,'Évacuer le CO2'),
('ssiap1-hc-p2-ext-q4',3,'Faire des économies d''énergie'),
('ssiap1-hc-p2-ext-q5',0,'Vrai'),
('ssiap1-hc-p2-ext-q5',1,'Faux'),
('ssiap1-hc-p2-ext-q6',0,'Vrai'),
('ssiap1-hc-p2-ext-q6',1,'Faux'),
('ssiap1-hc-p2-ext-q7',0,'Vrai'),
('ssiap1-hc-p2-ext-q7',1,'Faux'),
('ssiap1-hc-p2-ext-q8',0,'Maire ou son représentant'),
('ssiap1-hc-p2-ext-q8',1,'SDIS (sapeurs-pompiers)'),
('ssiap1-hc-p2-ext-q8',2,'DDT (urbanisme/accessibilité)'),
('ssiap1-hc-p2-ext-q8',3,'Police nationale'),
('ssiap1-hc-p2-ext-q8',4,'Représentant de l''Église'),
('ssiap1-hc-p2-ext-q9',0,'Calculs d''effectif'),
('ssiap1-hc-p2-ext-q9',1,'Description des moyens de secours'),
('ssiap1-hc-p2-ext-q9',2,'Programme musical de l''établissement'),
('ssiap1-hc-p2-ext-q9',3,'Plans des dégagements'),
('ssiap1-hc-p2-ext-q9',4,'Mode de désenfumage prévu'),
('ssiap1-hc-p2-ext-q10',0,'Limiter la propagation du feu'),
('ssiap1-hc-p2-ext-q10',1,'Préserver les voies d''évacuation'),
('ssiap1-hc-p2-ext-q10',2,'Augmenter le coefficient d''occupation'),
('ssiap1-hc-p2-ext-q10',3,'Faciliter l''intervention pompiers'),
('ssiap1-hc-p2-ext-q10',4,'Réduire la facture électrique'),
('ssiap1-hc-p2-ext-q11',0,'Type J — Personnes âgées'),
('ssiap1-hc-p2-ext-q11',1,'Type L — Salles polyvalentes'),
('ssiap1-hc-p2-ext-q11',2,'Type Q — Bureaux administratifs'),
('ssiap1-hc-p2-ext-q11',3,'Type V — Lieux de culte'),
('ssiap1-hc-p2-ext-q12',0,'Service de sécurité 24h/24'),
('ssiap1-hc-p2-ext-q12',1,'Compartimentage 2500 m²/3 niveaux'),
('ssiap1-hc-p2-ext-q12',2,'Évacuation totale au signal d''alarme'),
('ssiap1-hc-p2-ext-q12',3,'Colonne humide aux étages'),
('ssiap1-hc-p2-ext-q13',0,'Laisser faire — l''entreprise est qualifiée'),
('ssiap1-hc-p2-ext-q13',1,'Stopper immédiatement et exiger un permis de feu signé'),
('ssiap1-hc-p2-ext-q13',2,'Faire signer un permis verbal'),
('ssiap1-hc-p2-ext-q13',3,'Aller acheter un extincteur'),
('ssiap1-hc-p2-ext-q14',0,'Obéir, on a le temps de corriger'),
('ssiap1-hc-p2-ext-q14',1,'Refuser fermement, garder l''intégrité du registre, expliquer le risque pénal de falsification'),
('ssiap1-hc-p2-ext-q14',2,'Photocopier le registre original'),
('ssiap1-hc-p2-ext-q14',3,'Signaler à la commission par téléphone'),
('ssiap1-hc-p2-ext-q15',0,'Une zone de fumeurs'),
('ssiap1-hc-p2-ext-q15',1,'Le point de rassemblement après évacuation'),
('ssiap1-hc-p2-ext-q15',2,'Une infirmerie'),
('ssiap1-hc-p2-ext-q15',3,'Une zone de chargement'),
('ssiap1-hc-p2-ext-q16',0,'Direction des toilettes'),
('ssiap1-hc-p2-ext-q16',1,'Direction d''une issue de secours'),
('ssiap1-hc-p2-ext-q16',2,'Sortie de l''entreprise'),
('ssiap1-hc-p2-ext-q16',3,'Zone de fitness');
insert into public.cc_question_items (question_id,item_index,item_text) values
('ssiap1-hc-p2-ext-q17',0,'Dépôt de la demande au maire'),
('ssiap1-hc-p2-ext-q17',1,'Étude technique des services'),
('ssiap1-hc-p2-ext-q17',2,'Visite et avis de la commission'),
('ssiap1-hc-p2-ext-q17',3,'Arrêté d''autorisation d''ouverture du maire'),
('ssiap1-hc-p2-ext-q18',0,'Loi (Code de la Construction)'),
('ssiap1-hc-p2-ext-q18',1,'Décrets (R.123)'),
('ssiap1-hc-p2-ext-q18',2,'Arrêté (règlement de sécurité)'),
('ssiap1-hc-p2-ext-q18',3,'Notice descriptive du bâtiment'),
('ssiap1-hc-p2-ext-q19',0,'1ère catégorie (>1500 personnes)'),
('ssiap1-hc-p2-ext-q19',1,'2ème catégorie (701-1500)'),
('ssiap1-hc-p2-ext-q19',2,'3ème catégorie (301-700)'),
('ssiap1-hc-p2-ext-q19',3,'4ème catégorie (≤300, > seuil 5è)'),
('ssiap1-hc-p2-ext-q20',0,'A1 — Incombustible'),
('ssiap1-hc-p2-ext-q20',1,'A2 — Très peu combustible'),
('ssiap1-hc-p2-ext-q20',2,'B — Combustible difficilement inflammable'),
('ssiap1-hc-p2-ext-q20',3,'D — Combustible très inflammable');
insert into public.cc_question_pairs (question_id,pair_index,left_text,right_text) values
('ssiap1-hc-p2-ext-q21',0,'Type J','Personnes âgées / handicapées'),
('ssiap1-hc-p2-ext-q21',1,'Type M','Magasins / centres commerciaux'),
('ssiap1-hc-p2-ext-q21',2,'Type R','Enseignement'),
('ssiap1-hc-p2-ext-q21',3,'Type U','Établissements de soins'),
('ssiap1-hc-p2-ext-q22',0,'GHA','Habitation (>50 m)'),
('ssiap1-hc-p2-ext-q22',1,'GHO','Hôtels'),
('ssiap1-hc-p2-ext-q22',2,'GHU','Sanitaire'),
('ssiap1-hc-p2-ext-q22',3,'GHW','Bureaux');
insert into public.cc_question_categories (question_id,category_index,category_id,category_label) values
('ssiap1-hc-p2-ext-q25',0,'M','🛍️ Type M — Magasins'),
('ssiap1-hc-p2-ext-q25',1,'O','🏨 Type O — Hôtels'),
('ssiap1-hc-p2-ext-q25',2,'R','🎓 Type R — Enseignement');
insert into public.cc_question_category_items (question_id,item_index,item_text,correct_category) values
('ssiap1-hc-p2-ext-q25',0,'Centre commercial','M'),
('ssiap1-hc-p2-ext-q25',1,'Hôtel 4 étoiles','O'),
('ssiap1-hc-p2-ext-q25',2,'Lycée professionnel','R'),
('ssiap1-hc-p2-ext-q25',3,'Crèche','R'),
('ssiap1-hc-p2-ext-q25',4,'Hypermarché','M'),
('ssiap1-hc-p2-ext-q25',5,'Auberge de jeunesse','O');
insert into public.cc_question_decision_steps (question_id,step_index,step_question,options) values
('ssiap1-hc-p2-ext-q26',0,'ÉTAPE 1 — Vérifiez-vous l''impact sécurité ?','[{"text":"Oui, mur porteur = risque structure et compartimentage","nextStep":1},{"text":"Non, c''est l''affaire du locataire","nextStep":99},{"text":"Refuser sans analyse","nextStep":99}]'::jsonb),
('ssiap1-hc-p2-ext-q26',1,'ÉTAPE 2 — Quelle procédure imposer ?','[{"text":"Étude par bureau d''études + demande commission de sécurité","nextStep":2},{"text":"Verbal au directeur uniquement","nextStep":99},{"text":"Aucune — bricolage interne suffit","nextStep":99}]'::jsonb),
('ssiap1-hc-p2-ext-q26',2,'ÉTAPE 3 — Avant les travaux ?','[{"text":"Permis de feu signé + balisage + extincteurs sur place","nextStep":null},{"text":"Aucune préparation","nextStep":null},{"text":"Couper le feu d''alarme","nextStep":null}]'::jsonb);
commit;
