-- SSIAP 2 — Partie 2 « Réglementation IGH et compléments ERP »
-- 26 challenge cc_questions covering all 12 game types — module_id = ssiap2-partie2
begin;

insert into public.cc_questions
  (id, module_id, type, title, question, scenario, explanation,
   correct_answer, correct_answers, correct_order, correct_blanks, word_bank, sentence,
   difficulty, tags, pool, status, is_active)
values
('ssiap2-hc-p2-q1','ssiap2-partie2','quiz','Seuil IGH habitation',
 'À partir de quelle hauteur du dernier plancher accessible un bâtiment d''habitation devient-il IGH ?',
 null, 'IGH habitation = > 50 m. Autres usages = > 28 m. ITGH = > 200 m.',
 1, null, null, null, null, null,
 1, array['handcrafted','ssiap2','partie2']::text[], 'challenge', 'published', true),
('ssiap2-hc-p2-q2','ssiap2-partie2','quiz','Classe IGH bureaux',
 'Un IGH à usage exclusivement de bureaux est classé :',
 null, 'GHA = habitation, GHO = hôtels, GHR = enseignement, GHU = sanitaire, GHW = bureaux, GHZ = mixte.',
 2, null, null, null, null, null,
 1, array['handcrafted','ssiap2','partie2']::text[], 'challenge', 'published', true),
('ssiap2-hc-p2-q3','ssiap2-partie2','quiz','Compartimentage IGH',
 'La surface maximale d''un compartiment IGH est de :',
 null, 'Compartiment IGH : 2500 m² par niveau, ou 3 niveaux max si <= 2500 m². Coupe-feu 2 h.',
 1, null, null, null, null, null,
 1, array['handcrafted','ssiap2','partie2']::text[], 'challenge', 'published', true),
('ssiap2-hc-p2-q4','ssiap2-partie2','quiz','Permanence sécurité IGH',
 'Le service de sécurité d''un IGH doit être présent :',
 null, 'En IGH, service de sécurité 24h/24 7j/7 obligatoire (au minimum 1 SSIAP 2 + agents SSIAP 1).',
 1, null, null, null, null, null,
 1, array['handcrafted','ssiap2','partie2']::text[], 'challenge', 'published', true),
('ssiap2-hc-p2-q5','ssiap2-partie2','true-false','PCS IGH',
 'Tout IGH doit disposer d''un PC sécurité (PCS) opérationnel en permanence.',
 null, 'VRAI — PCS = poste central de sécurité, équipé de la centralisation SSI, présence permanente.',
 0, null, null, null, null, null,
 1, array['handcrafted','ssiap2','partie2']::text[], 'challenge', 'published', true),
('ssiap2-hc-p2-q6','ssiap2-partie2','true-false','Évacuation IGH',
 'L''évacuation d''un IGH se fait toujours en totalité dès le déclenchement de l''alarme.',
 null, 'FAUX — Logique de compartimentage : on évacue d''abord le compartiment sinistré + N+1, le reste est mis en attente.',
 1, null, null, null, null, null,
 1, array['handcrafted','ssiap2','partie2']::text[], 'challenge', 'published', true),
('ssiap2-hc-p2-q7','ssiap2-partie2','true-false','Autorité IGH',
 'Pour les IGH, c''est toujours le maire qui prend l''arrêté d''autorisation.',
 null, 'FAUX — En IGH, c''est généralement le préfet (commission consultative départementale de sécurité) qui statue.',
 1, null, null, null, null, null,
 1, array['handcrafted','ssiap2','partie2']::text[], 'challenge', 'published', true),
('ssiap2-hc-p2-q8','ssiap2-partie2','multiple-select','Commission ERP',
 'Qui sont les membres permanents d''une commission de sécurité ERP ?',
 null, 'Maire (ou représentant), SDIS, DDT, police/gendarmerie. Le syndicat n''en fait pas partie.',
 null, array[0,1,2,3]::integer[], null, null, null, null,
 1, array['handcrafted','ssiap2','partie2']::text[], 'challenge', 'published', true),
('ssiap2-hc-p2-q9','ssiap2-partie2','multiple-select','Documents commission',
 'Quels documents doivent être présentés à la commission de sécurité ?',
 null, 'Registre, RVRAT/RVRMD/Q18, plans d''intervention/évacuation, PV essais SSI. Les comptes annuels n''ont pas leur place.',
 null, array[0,1,2,3]::integer[], null, null, null, null,
 1, array['handcrafted','ssiap2','partie2']::text[], 'challenge', 'published', true),
('ssiap2-hc-p2-q10','ssiap2-partie2','multiple-select','Missions SSIAP 2',
 'Parmi ces missions, lesquelles relèvent du chef d''équipe SSIAP 2 ?',
 null, 'Encadrement SSIAP 1, registre, exercices d''évacuation, préparation commission. Les contrats fournisseurs relèvent du directeur.',
 null, array[0,1,2,3]::integer[], null, null, null, null,
 1, array['handcrafted','ssiap2','partie2']::text[], 'challenge', 'published', true),
('ssiap2-hc-p2-q11','ssiap2-partie2','find-intruder','Pas un type IGH',
 'Lequel n''est PAS un type IGH réglementaire ?',
 null, 'GHX n''est pas une classe IGH. Les classes existantes : GHA, GHO, GHR, GHS, GHTC, GHU, GHW1/W2, GHZ.',
 2, null, null, null, null, null,
 1, array['handcrafted','ssiap2','partie2']::text[], 'challenge', 'published', true),
('ssiap2-hc-p2-q12','ssiap2-partie2','find-intruder','Registre de sécurité',
 'Lequel n''est PAS une mention obligatoire du registre de sécurité ?',
 null, 'Le registre consigne exercices, contrôles, rapports. Pas les salaires.',
 2, null, null, null, null, null,
 1, array['handcrafted','ssiap2','partie2']::text[], 'challenge', 'published', true),
('ssiap2-hc-p2-q13','ssiap2-partie2','scenario','Ascenseur défaut SSI',
 'Action correcte ?',
 'En pleine journée, le tableau central affiche un défaut sur l''ascenseur prioritaire pompiers d''un IGH (priorité incendie HS).',
 'L''ascenseur prioritaire est essentiel à l''intervention. Mise hors service immédiate, alerte maintenance, consignation registre, info directeur sécurité.',
 1, null, null, null, null, null,
 1, array['handcrafted','ssiap2','partie2']::text[], 'challenge', 'published', true),
('ssiap2-hc-p2-q14','ssiap2-partie2','scenario','Commission imprévue',
 'Que faire ?',
 'Une commission de sécurité se présente sans prévenir alors que le directeur est absent. Vous êtes seul SSIAP 2 sur site.',
 'Le SSIAP 2 est l''interlocuteur naturel : accueil, présentation du registre + dossier de sécurité, accompagnement de la visite.',
 1, null, null, null, null, null,
 1, array['handcrafted','ssiap2','partie2']::text[], 'challenge', 'published', true),
('ssiap2-hc-p2-q15','ssiap2-partie2','image-identify','Issue de secours',
 'Ce panneau vert avec personnage et flèche signale :',
 null, 'NF EN ISO 7010 — E001/E002 : sortie / issue de secours.',
 1, null, null, null, null, null,
 1, array['handcrafted','ssiap2','partie2']::text[], 'challenge', 'published', true),
('ssiap2-hc-p2-q16','ssiap2-partie2','image-identify','Point d''eau pompiers',
 'Ce panneau rouge avec une borne signale :',
 null, 'F002 — Point d''eau d''incendie / poteau d''incendie pour les sapeurs-pompiers.',
 1, null, null, null, null, null,
 1, array['handcrafted','ssiap2','partie2']::text[], 'challenge', 'published', true),
('ssiap2-hc-p2-q17','ssiap2-partie2','sequence','Ouverture d''un ERP',
 'Classez les étapes administratives d''ouverture d''un ERP :',
 null, 'Permis/DAACT → étude technique → visite commission → avis → arrêté du maire.',
 null, null, array[0,1,2,3,4]::integer[], null, null, null,
 1, array['handcrafted','ssiap2','partie2']::text[], 'challenge', 'published', true),
('ssiap2-hc-p2-q18','ssiap2-partie2','sequence','Évacuation IGH',
 'Classez la chronologie d''une évacuation IGH :',
 null, 'Détection → confirmation SSIAP → évacuation compartiment + N+1 → alerte 18 → accueil pompiers.',
 null, null, array[0,1,2,3,4]::integer[], null, null, null,
 1, array['handcrafted','ssiap2','partie2']::text[], 'challenge', 'published', true),
('ssiap2-hc-p2-q19','ssiap2-partie2','ranking','Catégories ERP',
 'Classez les catégories ERP par effectif décroissant :',
 null, '1ère (>1500) > 2e (701-1500) > 3e (301-700) > 4e (≤300, > seuil 5e).',
 null, null, array[0,1,2,3]::integer[], null, null, null,
 1, array['handcrafted','ssiap2','partie2']::text[], 'challenge', 'published', true),
('ssiap2-hc-p2-q20','ssiap2-partie2','ranking','Périodicité contrôles',
 'Classez ces vérifications du plus fréquent au moins fréquent :',
 null, 'Essais alarme hebdo > essais SSI mensuels > Q18 / vérifications annuelles > visite périodique commission (3 ou 5 ans).',
 null, null, array[0,1,2,3]::integer[], null, null, null,
 1, array['handcrafted','ssiap2','partie2']::text[], 'challenge', 'published', true),
('ssiap2-hc-p2-q21','ssiap2-partie2','matching','Types ERP',
 'Associez chaque type ERP à son activité :',
 null, 'J = personnes âgées/handicapées, O = hôtels, R = enseignement, U = soins.',
 null, null, null, null, null, null,
 1, array['handcrafted','ssiap2','partie2']::text[], 'challenge', 'published', true),
('ssiap2-hc-p2-q22','ssiap2-partie2','matching','Classes IGH',
 'Associez chaque classe IGH à son usage :',
 null, 'GHA = habitation, GHO = hôtels, GHU = sanitaire/hospitalier, GHW2 = bureaux > 50 m.',
 null, null, null, null, null, null,
 1, array['handcrafted','ssiap2','partie2']::text[], 'challenge', 'published', true),
('ssiap2-hc-p2-q23','ssiap2-partie2','fill-blank','Seuils IGH',
 'Complétez les seuils IGH :',
 null, 'IGH habitation > 50 m / autres usages > 28 m / ITGH > 200 m.',
 null, null, null, array['50','28']::text[], array['28','50','100','200','12','15']::text[],
 'L''IGH commence à %1% mètres pour l''habitation et %2% mètres pour les autres usages.',
 1, array['handcrafted','ssiap2','partie2']::text[], 'challenge', 'published', true),
('ssiap2-hc-p2-q24','ssiap2-partie2','fill-blank','Compartiment IGH',
 'Complétez les valeurs de compartimentage :',
 null, 'Compartiment IGH : 2500 m² par niveau, 3 niveaux max si surface ≤ 2500 m².',
 null, null, null, array['2500','3']::text[], array['500','2500','5000','2','3','5']::text[],
 'Un compartiment IGH est limité à %1% m² par niveau ou peut couvrir %2% niveaux maximum.',
 1, array['handcrafted','ssiap2','partie2']::text[], 'challenge', 'published', true),
('ssiap2-hc-p2-q25','ssiap2-partie2','categories','Documents sécurité',
 'Classez ces documents par nature :',
 null, 'Réglementaire = arrêtés/notice. Opérationnel = plans, planning. Technique = rapports vérifications.',
 null, null, null, null, null, null,
 1, array['handcrafted','ssiap2','partie2']::text[], 'challenge', 'published', true),
('ssiap2-hc-p2-q26','ssiap2-partie2','decision','Visite commission',
 'Arbre de décision :',
 'Visite imprévue de la commission de sécurité. Le directeur est absent, vous êtes le SSIAP 2 sur site.',
 'Accueil professionnel + registre à jour + consigner les non-conformités + plan d''actions chiffré pour la prochaine visite.',
 null, null, null, null, null, null,
 1, array['handcrafted','ssiap2','partie2']::text[], 'challenge', 'published', true);

commit;
