-- SSIAP 2 — Partie 3 « Installations techniques approfondies »
-- 26 challenge cc_questions covering all 12 game types — module_id = ssiap2-partie3
begin;

insert into public.cc_questions
  (id, module_id, type, title, question, scenario, explanation,
   correct_answer, correct_answers, correct_order, correct_blanks, word_bank, sentence,
   difficulty, tags, pool, status, is_active)
values
('ssiap2-hc-p3-q1','ssiap2-partie3','quiz','SSI catégorie A',
 'Un SSI de catégorie A comprend obligatoirement :',
 null, 'Le SSI cat A est le plus complet : SDI + SMSI complet (CMSI + DAS asservis).',
 1, null, null, null, null, null,
 1, array['handcrafted','ssiap2','partie3']::text[], 'challenge', 'published', true),
('ssiap2-hc-p3-q2','ssiap2-partie3','quiz','Autonomie BAES',
 'L''autonomie minimale d''un BAES est de :',
 null, 'NF EN 50172 : autonomie 1 h, flux ≥ 45 lm.',
 1, null, null, null, null, null,
 1, array['handcrafted','ssiap2','partie3']::text[], 'challenge', 'published', true),
('ssiap2-hc-p3-q3','ssiap2-partie3','quiz','Débit RIA',
 'Une RIA DN 25/8 a un débit nominal minimal de :',
 null, 'RIA DN 25/8 : 30 L/min sous 4 bars (NF EN 671).',
 1, null, null, null, null, null,
 1, array['handcrafted','ssiap2','partie3']::text[], 'challenge', 'published', true),
('ssiap2-hc-p3-q4','ssiap2-partie3','quiz','Désenfumage naturel',
 'La surface des exutoires de désenfumage naturel doit être au minimum de :',
 null, 'En ERP : surface utile ≥ 1/100 (1 %) de la surface du local désenfumé.',
 1, null, null, null, null, null,
 1, array['handcrafted','ssiap2','partie3']::text[], 'challenge', 'published', true),
('ssiap2-hc-p3-q5','ssiap2-partie3','true-false','Test BAES',
 'Les BAES doivent être testés tous les mois (allumage) et tous les 6 mois (autonomie 1 h).',
 null, 'VRAI — Mensuel + semestriel, consignés au registre.',
 0, null, null, null, null, null,
 1, array['handcrafted','ssiap2','partie3']::text[], 'challenge', 'published', true),
('ssiap2-hc-p3-q6','ssiap2-partie3','true-false','Activation DAS',
 'Un DAS ne peut être activé que par la détection automatique.',
 null, 'FAUX — DAI, DM ou commande manuelle CMSI.',
 1, null, null, null, null, null,
 1, array['handcrafted','ssiap2','partie3']::text[], 'challenge', 'published', true),
('ssiap2-hc-p3-q7','ssiap2-partie3','true-false','Étiquetage BAES',
 'Tout BAES doit porter une étiquette indiquant la date de mise en service.',
 null, 'VRAI — Date de mise en service obligatoire.',
 0, null, null, null, null, null,
 1, array['handcrafted','ssiap2','partie3']::text[], 'challenge', 'published', true),
('ssiap2-hc-p3-q8','ssiap2-partie3','multiple-select','Fonctions SSI A',
 'Quelles fonctions sont assurées par un SSI catégorie A ?',
 null, 'Détection, alarme, compartimentage, désenfumage. Pas la climatisation.',
 null, array[0,1,2,3]::integer[], null, null, null, null,
 1, array['handcrafted','ssiap2','partie3']::text[], 'challenge', 'published', true),
('ssiap2-hc-p3-q9','ssiap2-partie3','multiple-select','Composants CMSI',
 'Quels éléments composent un CMSI ?',
 null, 'UCMC, US, USC, voyants DAS. La pompe de relevage est sanitaire.',
 null, array[0,1,2,3]::integer[], null, null, null, null,
 1, array['handcrafted','ssiap2','partie3']::text[], 'challenge', 'published', true),
('ssiap2-hc-p3-q10','ssiap2-partie3','multiple-select','Coupures d''urgence',
 'Quelles coupures d''urgence le SSIAP doit-il connaître ?',
 null, 'Électricité, gaz, ventilation, carburant chaufferie. Pas le téléphone.',
 null, array[0,1,2,3]::integer[], null, null, null, null,
 1, array['handcrafted','ssiap2','partie3']::text[], 'challenge', 'published', true),
('ssiap2-hc-p3-q11','ssiap2-partie3','find-intruder','Pas un détecteur',
 'Lequel n''est PAS un type de détecteur incendie ?',
 null, 'Le détecteur « gravimétrique » n''existe pas.',
 2, null, null, null, null, null,
 1, array['handcrafted','ssiap2','partie3']::text[], 'challenge', 'published', true),
('ssiap2-hc-p3-q12','ssiap2-partie3','find-intruder','Pas un RIA',
 'Lequel n''est PAS un diamètre nominal de RIA réglementaire ?',
 null, 'DN 70/40 n''existe pas pour les RIA.',
 2, null, null, null, null, null,
 1, array['handcrafted','ssiap2','partie3']::text[], 'challenge', 'published', true),
('ssiap2-hc-p3-q13','ssiap2-partie3','scenario','RIA dépressurisé',
 'Action correcte ?',
 'Au passage matinal, vous constatez qu''une RIA est dépressurisée à la suite d''un essai effectué la veille par un agent.',
 'Vérifier vanne, alerter PCS, consigner registre, refaire test.',
 1, null, null, null, null, null,
 1, array['handcrafted','ssiap2','partie3']::text[], 'challenge', 'published', true),
('ssiap2-hc-p3-q14','ssiap2-partie3','scenario','BAES éteints',
 'Action correcte ?',
 'Lors d''une ronde, vous constatez 3 BAES éteints dans un couloir d''évacuation.',
 'Consigner, alerter mainteneur, balisage portatif, ronde renforcée.',
 1, null, null, null, null, null,
 1, array['handcrafted','ssiap2','partie3']::text[], 'challenge', 'published', true),
('ssiap2-hc-p3-q15','ssiap2-partie3','image-identify','Casque obligatoire',
 'Pictogramme rond bleu avec un casque de chantier :',
 null, 'M014 — Port du casque obligatoire (ronds bleus = obligation).',
 1, null, null, null, null, null,
 1, array['handcrafted','ssiap2','partie3']::text[], 'challenge', 'published', true),
('ssiap2-hc-p3-q16','ssiap2-partie3','image-identify','Interdiction de fumer',
 'Pictogramme rond rouge barré avec une cigarette :',
 null, 'P002 — Interdiction de fumer.',
 1, null, null, null, null, null,
 1, array['handcrafted','ssiap2','partie3']::text[], 'challenge', 'published', true),
('ssiap2-hc-p3-q17','ssiap2-partie3','sequence','Cycle alarme SSI A',
 'Classez le cycle d''une alarme incendie en SSI catégorie A :',
 null, 'DAI → alarme PCS → confirmation SSIAP → alarme générale + DAS → évacuation.',
 null, null, array[0,1,2,3,4]::integer[], null, null, null,
 1, array['handcrafted','ssiap2','partie3']::text[], 'challenge', 'published', true),
('ssiap2-hc-p3-q18','ssiap2-partie3','sequence','Vie d''un extincteur',
 'Classez les étapes de la vie réglementaire d''un extincteur :',
 null, 'Visuelle annuelle → révision 5 ans → recharge 10 ans → remplacement 20 ans → recyclage.',
 null, null, array[0,1,2,3,4]::integer[], null, null, null,
 1, array['handcrafted','ssiap2','partie3']::text[], 'challenge', 'published', true),
('ssiap2-hc-p3-q19','ssiap2-partie3','ranking','Autonomie alimentations',
 'Classez ces alimentations de secours de la plus longue à la plus courte autonomie :',
 null, 'Groupe diesel > BAES > Onduleur > batterie smartphone.',
 null, null, array[0,1,2,3]::integer[], null, null, null,
 1, array['handcrafted','ssiap2','partie3']::text[], 'challenge', 'published', true),
('ssiap2-hc-p3-q20','ssiap2-partie3','ranking','Catégories SSI',
 'Classez les catégories SSI du plus complet au plus simple :',
 null, 'A > B > C > D/E.',
 null, null, array[0,1,2,3]::integer[], null, null, null,
 1, array['handcrafted','ssiap2','partie3']::text[], 'challenge', 'published', true),
('ssiap2-hc-p3-q21','ssiap2-partie3','matching','DAS ↔ fonction',
 'Associez chaque DAS à sa fonction :',
 null, 'Porte CF = compartimentage, volet/clapet = désenfumage, trappe = exutoire toiture, ventouse = maintien porte CF.',
 null, null, null, null, null, null,
 1, array['handcrafted','ssiap2','partie3']::text[], 'challenge', 'published', true),
('ssiap2-hc-p3-q22','ssiap2-partie3','matching','Coupure ↔ couleur',
 'Associez chaque coupure à la couleur normalisée :',
 null, 'Élec rouge / Gaz jaune / Eau bleu / Ventilation vert.',
 null, null, null, null, null, null,
 1, array['handcrafted','ssiap2','partie3']::text[], 'challenge', 'published', true),
('ssiap2-hc-p3-q23','ssiap2-partie3','fill-blank','Catégories SSI',
 'Complétez les catégories SSI :',
 null, 'A le plus complet, E le plus simple.',
 null, null, null, array['A','E']::text[], array['A','B','C','D','E']::text[],
 'Le SSI catégorie %1% est le plus complet, le SSI catégorie %2% est le plus simple.',
 1, array['handcrafted','ssiap2','partie3']::text[], 'challenge', 'published', true),
('ssiap2-hc-p3-q24','ssiap2-partie3','fill-blank','BAES autonomie/test',
 'Complétez les valeurs BAES :',
 null, 'BAES : 1 h d''autonomie, test mensuel.',
 null, null, null, array['1','mois']::text[], array['1','6','12','24','jour','semaine','mois','an']::text[],
 'Un BAES doit avoir une autonomie minimale de %1% heure et être testé en fonctionnement au moins une fois par %2%.',
 1, array['handcrafted','ssiap2','partie3']::text[], 'challenge', 'published', true),
('ssiap2-hc-p3-q25','ssiap2-partie3','categories','Familles SSI',
 'Classez ces équipements par famille SSI :',
 null, 'Détection / Alarme / Mise en sécurité.',
 null, null, null, null, null, null,
 1, array['handcrafted','ssiap2','partie3']::text[], 'challenge', 'published', true),
('ssiap2-hc-p3-q26','ssiap2-partie3','decision','Coupure courant évac',
 'Arbre de décision :',
 'En pleine évacuation IGH, une coupure générale du courant survient. Le PCS bascule sur batterie, les BAES s''allument, les ascenseurs sont hors service.',
 'Vérifier groupe + ascenseurs + diffuser des consignes claires aux occupants.',
 null, null, null, null, null, null,
 1, array['handcrafted','ssiap2','partie3']::text[], 'challenge', 'published', true);

commit;
