-- SSIAP 2 — Partie 3 « Installations techniques approfondies » — sub-tables
begin;

insert into public.cc_question_options (question_id, option_index, option_text) values
('ssiap2-hc-p3-q1', 0, 'Seulement des déclencheurs manuels'),
('ssiap2-hc-p3-q1', 1, 'Un SDI + un SMSI complet (CMSI + DAS asservis)'),
('ssiap2-hc-p3-q1', 2, 'Uniquement un éclairage de sécurité'),
('ssiap2-hc-p3-q1', 3, 'Une simple alarme mécanique'),
('ssiap2-hc-p3-q2', 0, '30 minutes'),
('ssiap2-hc-p3-q2', 1, '1 heure'),
('ssiap2-hc-p3-q2', 2, '6 heures'),
('ssiap2-hc-p3-q2', 3, '24 heures'),
('ssiap2-hc-p3-q3', 0, '15 L/min'),
('ssiap2-hc-p3-q3', 1, '30 L/min'),
('ssiap2-hc-p3-q3', 2, '100 L/min'),
('ssiap2-hc-p3-q3', 3, '300 L/min'),
('ssiap2-hc-p3-q4', 0, '1/200 (0,5 %)'),
('ssiap2-hc-p3-q4', 1, '1/100 (1 %)'),
('ssiap2-hc-p3-q4', 2, '1/50 (2 %)'),
('ssiap2-hc-p3-q4', 3, '1/10 (10 %)'),
('ssiap2-hc-p3-q5', 0, 'Vrai'),
('ssiap2-hc-p3-q5', 1, 'Faux'),
('ssiap2-hc-p3-q6', 0, 'Vrai'),
('ssiap2-hc-p3-q6', 1, 'Faux'),
('ssiap2-hc-p3-q7', 0, 'Vrai'),
('ssiap2-hc-p3-q7', 1, 'Faux'),
('ssiap2-hc-p3-q8', 0, 'Détection automatique d''incendie'),
('ssiap2-hc-p3-q8', 1, 'Alarme générale (sélective ou non)'),
('ssiap2-hc-p3-q8', 2, 'Compartimentage (portes coupe-feu)'),
('ssiap2-hc-p3-q8', 3, 'Désenfumage automatique'),
('ssiap2-hc-p3-q8', 4, 'Climatisation des bureaux'),
('ssiap2-hc-p3-q9', 0, 'UCMC — unité de commande manuelle centralisée'),
('ssiap2-hc-p3-q9', 1, 'US — unités de signalisation'),
('ssiap2-hc-p3-q9', 2, 'USC — unité de synchronisation'),
('ssiap2-hc-p3-q9', 3, 'Voyants d''état des DAS'),
('ssiap2-hc-p3-q9', 4, 'Pompe de relevage des eaux usées'),
('ssiap2-hc-p3-q10', 0, 'Coupure générale électricité'),
('ssiap2-hc-p3-q10', 1, 'Coupure générale gaz'),
('ssiap2-hc-p3-q10', 2, 'Coupure ventilation / climatisation'),
('ssiap2-hc-p3-q10', 3, 'Coupure carburant chaufferie'),
('ssiap2-hc-p3-q10', 4, 'Coupure téléphonie'),
('ssiap2-hc-p3-q11', 0, 'DI optique de fumée'),
('ssiap2-hc-p3-q11', 1, 'DI thermique (chaleur)'),
('ssiap2-hc-p3-q11', 2, 'DI gravimétrique'),
('ssiap2-hc-p3-q11', 3, 'DI flamme (UV/IR)'),
('ssiap2-hc-p3-q12', 0, 'RIA DN 19/6'),
('ssiap2-hc-p3-q12', 1, 'RIA DN 25/8'),
('ssiap2-hc-p3-q12', 2, 'RIA DN 70/40'),
('ssiap2-hc-p3-q12', 3, 'RIA DN 33/12'),
('ssiap2-hc-p3-q13', 0, 'Faire comme si de rien n''était, le service marche'),
('ssiap2-hc-p3-q13', 1, 'Vérifier la fermeture de vanne, alerter le PCS, consigner au registre, refaire un test de pression'),
('ssiap2-hc-p3-q13', 2, 'Démonter la RIA pour réparation interne'),
('ssiap2-hc-p3-q13', 3, 'Couper la colonne d''eau du bâtiment'),
('ssiap2-hc-p3-q14', 0, 'Les remplacer immédiatement par des éclairages portatifs'),
('ssiap2-hc-p3-q14', 1, 'Consigner au registre, alerter le mainteneur, balisage portatif et ronde renforcée'),
('ssiap2-hc-p3-q14', 2, 'Reporter la maintenance au prochain trimestre'),
('ssiap2-hc-p3-q14', 3, 'Couper l''alimentation électrique du couloir'),
('ssiap2-hc-p3-q15', 0, 'Un avertissement de chute'),
('ssiap2-hc-p3-q15', 1, 'Une obligation — port du casque (M014)'),
('ssiap2-hc-p3-q15', 2, 'Une interdiction'),
('ssiap2-hc-p3-q15', 3, 'Une issue de secours'),
('ssiap2-hc-p3-q16', 0, 'Un sauvetage / point de premiers secours'),
('ssiap2-hc-p3-q16', 1, 'Une interdiction — défense de fumer (P002)'),
('ssiap2-hc-p3-q16', 2, 'Une obligation'),
('ssiap2-hc-p3-q16', 3, 'Un panneau d''information générique');

insert into public.cc_question_items (question_id, item_index, item_text) values
('ssiap2-hc-p3-q17', 0, 'Détection automatique (DAI) ou DM'),
('ssiap2-hc-p3-q17', 1, 'Alarme restreinte au PCS'),
('ssiap2-hc-p3-q17', 2, 'Confirmation par l''équipe SSIAP sur le terrain'),
('ssiap2-hc-p3-q17', 3, 'Alarme générale + asservissements DAS'),
('ssiap2-hc-p3-q17', 4, 'Évacuation et appel des secours'),
('ssiap2-hc-p3-q18', 0, 'Vérification visuelle annuelle'),
('ssiap2-hc-p3-q18', 1, 'Révision complète à 5 ans (démontage interne)'),
('ssiap2-hc-p3-q18', 2, 'Recharge / contrôle approfondi à 10 ans'),
('ssiap2-hc-p3-q18', 3, 'Remplacement réglementaire à 20 ans'),
('ssiap2-hc-p3-q18', 4, 'Recyclage / mise au rebut'),
('ssiap2-hc-p3-q19', 0, 'Groupe électrogène diesel (plusieurs heures)'),
('ssiap2-hc-p3-q19', 1, 'BAES (1 h)'),
('ssiap2-hc-p3-q19', 2, 'Onduleur informatique (~30 min)'),
('ssiap2-hc-p3-q19', 3, 'Batterie de smartphone en mode lampe (~10 min)'),
('ssiap2-hc-p3-q20', 0, 'SSI catégorie A — le plus complet'),
('ssiap2-hc-p3-q20', 1, 'SSI catégorie B'),
('ssiap2-hc-p3-q20', 2, 'SSI catégorie C'),
('ssiap2-hc-p3-q20', 3, 'SSI catégorie D / E — alarme simple');

insert into public.cc_question_pairs (question_id, pair_index, left_text, right_text) values
('ssiap2-hc-p3-q21', 0, 'Porte coupe-feu', 'Compartimentage'),
('ssiap2-hc-p3-q21', 1, 'Volet / clapet de désenfumage', 'Désenfumage mécanique'),
('ssiap2-hc-p3-q21', 2, 'Trappe d''exutoire', 'Évacuation des fumées en toiture'),
('ssiap2-hc-p3-q21', 3, 'Ventouse électromagnétique', 'Maintien ouvert d''une porte coupe-feu'),
('ssiap2-hc-p3-q22', 0, 'Coupure électricité', 'Rouge avec éclair'),
('ssiap2-hc-p3-q22', 1, 'Coupure gaz', 'Jaune'),
('ssiap2-hc-p3-q22', 2, 'Coupure eau', 'Bleu'),
('ssiap2-hc-p3-q22', 3, 'Coupure ventilation', 'Vert');

insert into public.cc_question_categories (question_id, category_index, category_id, category_label) values
('ssiap2-hc-p3-q25', 0, 'detection', '🔎 Détection'),
('ssiap2-hc-p3-q25', 1, 'alarme', '🔔 Alarme'),
('ssiap2-hc-p3-q25', 2, 'mise_securite', '🛡️ Mise en sécurité');

insert into public.cc_question_category_items (question_id, item_index, item_text, correct_category) values
('ssiap2-hc-p3-q25', 0, 'DAI optique de fumée', 'detection'),
('ssiap2-hc-p3-q25', 1, 'Déclencheur manuel (DM)', 'detection'),
('ssiap2-hc-p3-q25', 2, 'Sirène / diffuseur sonore', 'alarme'),
('ssiap2-hc-p3-q25', 3, 'Flash visuel (DAS pour malentendants)', 'alarme'),
('ssiap2-hc-p3-q25', 4, 'Porte coupe-feu asservie', 'mise_securite'),
('ssiap2-hc-p3-q25', 5, 'Trappe de désenfumage en toiture', 'mise_securite');

insert into public.cc_question_decision_steps (question_id, step_index, step_question, options) values
('ssiap2-hc-p3-q26', 0,
 'ÉTAPE 1 — Coupure générale du courant en pleine évacuation. Premier réflexe ?',
 '[{"text":"Vérifier le basculement automatique sur groupe électrogène et confirmer l''état du PCS","nextStep":1},{"text":"Couper aussi le gaz « par sécurité »","nextStep":99},{"text":"Quitter le PCS pour aller voir","nextStep":99}]'::jsonb),
('ssiap2-hc-p3-q26', 1,
 'ÉTAPE 2 — Le groupe électrogène prend le relais. Action sur les ascenseurs ?',
 '[{"text":"Vérifier que les ascenseurs sont stationnés au niveau d''accès et non bloqués entre étages","nextStep":2},{"text":"Tenter de relancer manuellement les cabines","nextStep":99},{"text":"Évacuer les usagers en utilisant les cabines","nextStep":99}]'::jsonb),
('ssiap2-hc-p3-q26', 2,
 'ÉTAPE 3 — Évacuation par les escaliers en cours. Information à diffuser ?',
 '[{"text":"Annoncer aux occupants : sortie par les escaliers, BAES actifs, pompiers en route","nextStep":null},{"text":"Annoncer que le bâtiment est sécurisé, retour aux postes","nextStep":null},{"text":"Garder le silence pour ne pas paniquer","nextStep":null}]'::jsonb);

commit;
