-- SSIAP 2 — Partie 4 « Management de l'équipe de sécurité » — sub-tables
begin;

insert into public.cc_question_options (question_id, option_index, option_text) values
('ssiap2-hc-p4-q1', 0, '1 SSIAP 1 seul'),
('ssiap2-hc-p4-q1', 1, '1 SSIAP 1 + 1 SSIAP 2'),
('ssiap2-hc-p4-q1', 2, '1 SSIAP 2 + 3 SSIAP 1'),
('ssiap2-hc-p4-q1', 3, '3 SSIAP 3 minimum'),
('ssiap2-hc-p4-q2', 0, 'Éteindre lui-même le feu en remplaçant les pompiers'),
('ssiap2-hc-p4-q2', 1, 'Diriger l''équipe SSIAP 1 et coordonner les actions jusqu''à l''arrivée des secours'),
('ssiap2-hc-p4-q2', 2, 'Informer la presse'),
('ssiap2-hc-p4-q2', 3, 'Téléphoner aux familles des occupants'),
('ssiap2-hc-p4-q3', 0, 'Une fois par jour'),
('ssiap2-hc-p4-q3', 1, 'Toutes les 4 heures environ (selon planning établi)'),
('ssiap2-hc-p4-q3', 2, 'Une fois par semaine'),
('ssiap2-hc-p4-q3', 3, 'Aucune obligation réglementaire'),
('ssiap2-hc-p4-q4', 0, 'Sanctionner les retards individuels'),
('ssiap2-hc-p4-q4', 1, 'Identifier les écarts et améliorer les procédures'),
('ssiap2-hc-p4-q4', 2, 'Faire un rapport à la presse'),
('ssiap2-hc-p4-q4', 3, 'Mesurer l''effectif présent'),
('ssiap2-hc-p4-q5', 0, 'Vrai'),
('ssiap2-hc-p4-q5', 1, 'Faux'),
('ssiap2-hc-p4-q6', 0, 'Vrai'),
('ssiap2-hc-p4-q6', 1, 'Faux'),
('ssiap2-hc-p4-q7', 0, 'Vrai'),
('ssiap2-hc-p4-q7', 1, 'Faux'),
('ssiap2-hc-p4-q8', 0, 'Effectif présent et absences'),
('ssiap2-hc-p4-q8', 1, 'Évènements de la journée (incidents, levées de doute)'),
('ssiap2-hc-p4-q8', 2, 'État des installations techniques'),
('ssiap2-hc-p4-q8', 3, 'Travaux en cours et permis de feu'),
('ssiap2-hc-p4-q8', 4, 'Liste des achats personnels'),
('ssiap2-hc-p4-q9', 0, 'Remettre les plans d''intervention'),
('ssiap2-hc-p4-q9', 1, 'Indiquer le lieu du sinistre confirmé'),
('ssiap2-hc-p4-q9', 2, 'Communiquer la nature du sinistre et les actions déjà engagées'),
('ssiap2-hc-p4-q9', 3, 'Indiquer les coupures déjà effectuées'),
('ssiap2-hc-p4-q9', 4, 'Les laisser se débrouiller seuls'),
('ssiap2-hc-p4-q10', 0, 'Leadership et autorité bienveillante'),
('ssiap2-hc-p4-q10', 1, 'Maîtrise technique du SSI et des moyens de secours'),
('ssiap2-hc-p4-q10', 2, 'Communication claire (radio + face à face)'),
('ssiap2-hc-p4-q10', 3, 'Gestion du stress et capacité de décision rapide'),
('ssiap2-hc-p4-q10', 4, 'Comptabilité analytique'),
('ssiap2-hc-p4-q11', 0, 'Radio portatif'),
('ssiap2-hc-p4-q11', 1, 'Téléphone interne PCS'),
('ssiap2-hc-p4-q11', 2, 'Pigeon voyageur'),
('ssiap2-hc-p4-q11', 3, 'Affichage au PCS'),
('ssiap2-hc-p4-q12', 0, 'Météo et impact possible sur le bâtiment'),
('ssiap2-hc-p4-q12', 1, 'Travaux du jour avec permis de feu'),
('ssiap2-hc-p4-q12', 2, 'Vie privée des collègues'),
('ssiap2-hc-p4-q12', 3, 'Effectif et affectation des rondes'),
('ssiap2-hc-p4-q13', 0, 'Ignorer, ce sont leurs problèmes personnels'),
('ssiap2-hc-p4-q13', 1, 'Recevoir les deux séparément, écouter, recadrer factuellement, fixer des objectifs mesurables'),
('ssiap2-hc-p4-q13', 2, 'Sanctionner publiquement le plus jeune'),
('ssiap2-hc-p4-q13', 3, 'Annoncer le conflit en réunion plénière'),
('ssiap2-hc-p4-q14', 0, 'Le sermonner sur place devant l''équipe'),
('ssiap2-hc-p4-q14', 1, 'Le mettre en retrait, lui confier une tâche simple, débriefer après l''incident'),
('ssiap2-hc-p4-q14', 2, 'L''envoyer seul tenir le PCS'),
('ssiap2-hc-p4-q14', 3, 'Continuer comme si de rien n''était'),
('ssiap2-hc-p4-q15', 0, 'Un agent de propreté'),
('ssiap2-hc-p4-q15', 1, 'Un agent du service de sécurité incendie identifiable en intervention'),
('ssiap2-hc-p4-q15', 2, 'Un visiteur'),
('ssiap2-hc-p4-q15', 3, 'Un livreur'),
('ssiap2-hc-p4-q16', 0, 'Une cabine téléphonique commerciale'),
('ssiap2-hc-p4-q16', 1, 'Un téléphone d''urgence / point d''appel sécurité (M005/E007)'),
('ssiap2-hc-p4-q16', 2, 'Un point WiFi'),
('ssiap2-hc-p4-q16', 3, 'Un parloir');

insert into public.cc_question_items (question_id, item_index, item_text) values
('ssiap2-hc-p4-q17', 0, 'Lecture du registre et de la main courante'),
('ssiap2-hc-p4-q17', 1, 'Briefing par le chef d''équipe sortant'),
('ssiap2-hc-p4-q17', 2, 'Tour des installations critiques (PCS, RIA, BAES…)'),
('ssiap2-hc-p4-q17', 3, 'Affectation des rondes et des missions du jour'),
('ssiap2-hc-p4-q17', 4, 'Premier passage en ronde'),
('ssiap2-hc-p4-q18', 0, 'Préparation et information préalable du personnel'),
('ssiap2-hc-p4-q18', 1, 'Déclenchement de l''alarme'),
('ssiap2-hc-p4-q18', 2, 'Évacuation et guidage par les serre-files'),
('ssiap2-hc-p4-q18', 3, 'Comptage au point de rassemblement'),
('ssiap2-hc-p4-q18', 4, 'Débriefing et rédaction du compte rendu'),
('ssiap2-hc-p4-q19', 0, 'SSIAP 3 — chef de service sécurité incendie'),
('ssiap2-hc-p4-q19', 1, 'SSIAP 2 — chef d''équipe'),
('ssiap2-hc-p4-q19', 2, 'SSIAP 1 — agent de sécurité incendie'),
('ssiap2-hc-p4-q19', 3, 'ESI — équipier de seconde intervention'),
('ssiap2-hc-p4-q20', 0, 'Sauvegarde des personnes'),
('ssiap2-hc-p4-q20', 1, 'Donner l''alerte aux secours'),
('ssiap2-hc-p4-q20', 2, 'Combattre le sinistre — premières mesures'),
('ssiap2-hc-p4-q20', 3, 'Préservation des biens');

insert into public.cc_question_pairs (question_id, pair_index, left_text, right_text) values
('ssiap2-hc-p4-q21', 0, 'SSIAP 1', 'Rondes et premières actions sur le terrain'),
('ssiap2-hc-p4-q21', 1, 'SSIAP 2', 'Encadrement de l''équipe et liaison avec le directeur sécurité'),
('ssiap2-hc-p4-q21', 2, 'SSIAP 3', 'Direction du service / conseil de l''exploitant'),
('ssiap2-hc-p4-q21', 3, 'ESI', 'Intervention spécialisée de seconde ligne (interne entreprise)'),
('ssiap2-hc-p4-q22', 0, 'Main courante', 'Évènements horodatés du quart'),
('ssiap2-hc-p4-q22', 1, 'Registre de sécurité', 'Contrôles, exercices et rapports successifs'),
('ssiap2-hc-p4-q22', 2, 'Compte rendu d''intervention', 'Détail factuel d''un sinistre traité'),
('ssiap2-hc-p4-q22', 3, 'Cahier de consignes', 'Procédures permanentes du site');

insert into public.cc_question_categories (question_id, category_index, category_id, category_label) values
('ssiap2-hc-p4-q25', 0, 'quotidien', '🟢 Quotidien'),
('ssiap2-hc-p4-q25', 1, 'hebdo', '🟡 Hebdomadaire'),
('ssiap2-hc-p4-q25', 2, 'mensuel', '🟠 Mensuel');

insert into public.cc_question_category_items (question_id, item_index, item_text, correct_category) values
('ssiap2-hc-p4-q25', 0, 'Tour de prise de service / briefing', 'quotidien'),
('ssiap2-hc-p4-q25', 1, 'Tenue de la main courante', 'quotidien'),
('ssiap2-hc-p4-q25', 2, 'Essai d''alarme générale', 'hebdo'),
('ssiap2-hc-p4-q25', 3, 'Inspection visuelle du parc d''extincteurs', 'hebdo'),
('ssiap2-hc-p4-q25', 4, 'Essai SSI et asservissements DAS', 'mensuel'),
('ssiap2-hc-p4-q25', 5, 'Test allumage BAES', 'mensuel');

insert into public.cc_question_decision_steps (question_id, step_index, step_question, options) values
('ssiap2-hc-p4-q26', 0,
 'ÉTAPE 1 — Un SSIAP 1 signale par radio un dégagement de fumée. Premier réflexe au PCS ?',
 '[{"text":"Demander une description précise (lieu, intensité, victimes ?) avant d''engager une décision","nextStep":1},{"text":"Déclencher immédiatement l''évacuation totale","nextStep":99},{"text":"Couper toute la ventilation centrale du bâtiment","nextStep":99}]'::jsonb),
('ssiap2-hc-p4-q26', 1,
 'ÉTAPE 2 — Description : début de feu, pas de victimes, fumée localisée. Action ?',
 '[{"text":"Envoyer un agent avec extincteur, alerter le PCS, préparer une éventuelle évacuation","nextStep":2},{"text":"Quitter le PCS pour aller voir personnellement","nextStep":99},{"text":"Attendre 10 minutes pour confirmer","nextStep":99}]'::jsonb),
('ssiap2-hc-p4-q26', 2,
 'ÉTAPE 3 — Le feu n''est pas maîtrisé en 2 minutes. Suite ?',
 '[{"text":"Déclencher l''évacuation du compartiment, alerter les pompiers, organiser leur accueil","nextStep":null},{"text":"Couper l''eau du bâtiment","nextStep":null},{"text":"Reprendre les rondes habituelles","nextStep":null}]'::jsonb);

commit;
