-- SSIAP 2 — Partie 4 « Management de l'équipe de sécurité »
-- 26 challenge cc_questions covering all 12 game types — module_id = ssiap2-partie4
begin;

insert into public.cc_questions
  (id, module_id, type, title, question, scenario, explanation,
   correct_answer, correct_answers, correct_order, correct_blanks, word_bank, sentence,
   difficulty, tags, pool, status, is_active)
values
('ssiap2-hc-p4-q1','ssiap2-partie4','quiz','Effectif service sécurité',
 'Dans un ERP de 1ère catégorie (>1500 personnes), l''effectif minimal du service de sécurité par tranche de 4000 m² est :',
 null, '1 SSIAP 2 + 3 SSIAP 1 minimum par tranche de 4 000 m² en 1ère catégorie.',
 2, null, null, null, null, null,
 1, array['handcrafted','ssiap2','partie4']::text[], 'challenge', 'published', true),
('ssiap2-hc-p4-q2','ssiap2-partie4','quiz','Rôle SSIAP 2 sinistre',
 'Le rôle principal du SSIAP 2 lors d''un sinistre est :',
 null, 'Diriger l''équipe SSIAP 1 et coordonner les actions jusqu''à l''arrivée des secours.',
 1, null, null, null, null, null,
 1, array['handcrafted','ssiap2','partie4']::text[], 'challenge', 'published', true),
('ssiap2-hc-p4-q3','ssiap2-partie4','quiz','Fréquence ronde IGH',
 'La fréquence d''une ronde de sécurité dans un IGH est typiquement :',
 null, 'En IGH, rondes toutes les 4 h ou selon plan défini.',
 1, null, null, null, null, null,
 1, array['handcrafted','ssiap2','partie4']::text[], 'challenge', 'published', true),
('ssiap2-hc-p4-q4','ssiap2-partie4','quiz','Objectif débriefing',
 'Le débriefing d''une équipe SSIAP après un exercice d''évacuation sert principalement à :',
 null, 'Identifier les écarts (objectifs / réalité), capitaliser et améliorer les procédures.',
 1, null, null, null, null, null,
 1, array['handcrafted','ssiap2','partie4']::text[], 'challenge', 'published', true),
('ssiap2-hc-p4-q5','ssiap2-partie4','true-false','Sanction sans hiérarchie',
 'Un SSIAP 2 peut sanctionner directement un SSIAP 1 sans en référer à la hiérarchie.',
 null, 'FAUX — La sanction relève de l''employeur. Le SSIAP 2 fait remonter les écarts.',
 1, null, null, null, null, null,
 1, array['handcrafted','ssiap2','partie4']::text[], 'challenge', 'published', true),
('ssiap2-hc-p4-q6','ssiap2-partie4','true-false','Radio courte et claire',
 'Les communications radio doivent être courtes, claires et utiliser des messages standardisés.',
 null, 'VRAI — Phrases brèves + accusé de réception.',
 0, null, null, null, null, null,
 1, array['handcrafted','ssiap2','partie4']::text[], 'challenge', 'published', true),
('ssiap2-hc-p4-q7','ssiap2-partie4','true-false','Briefing facultatif',
 'Le briefing de prise de service est facultatif s''il n''y a pas eu d''événement.',
 null, 'FAUX — Briefing systématique : main courante, état des installations, missions.',
 1, null, null, null, null, null,
 1, array['handcrafted','ssiap2','partie4']::text[], 'challenge', 'published', true),
('ssiap2-hc-p4-q8','ssiap2-partie4','multiple-select','Rapport quotidien',
 'Quelles informations doivent figurer dans le rapport quotidien du chef d''équipe ?',
 null, 'Effectif, événements, état des installations, travaux/permis. Pas les achats personnels.',
 null, array[0,1,2,3]::integer[], null, null, null, null,
 1, array['handcrafted','ssiap2','partie4']::text[], 'challenge', 'published', true),
('ssiap2-hc-p4-q9','ssiap2-partie4','multiple-select','Accueil pompiers',
 'Lors de l''accueil des sapeurs-pompiers, le SSIAP 2 doit :',
 null, 'Plans, lieu confirmé, nature/actions, coupures effectuées.',
 null, array[0,1,2,3]::integer[], null, null, null, null,
 1, array['handcrafted','ssiap2','partie4']::text[], 'challenge', 'published', true),
('ssiap2-hc-p4-q10','ssiap2-partie4','multiple-select','Compétences SSIAP 2',
 'Quelles sont les compétences clés d''un chef d''équipe SSIAP 2 ?',
 null, 'Leadership, technique, communication, gestion du stress.',
 null, array[0,1,2,3]::integer[], null, null, null, null,
 1, array['handcrafted','ssiap2','partie4']::text[], 'challenge', 'published', true),
('ssiap2-hc-p4-q11','ssiap2-partie4','find-intruder','Pas un canal radio',
 'Lequel n''est PAS un canal de communication d''équipe SSIAP ?',
 null, 'Le pigeon voyageur n''est plus en service.',
 2, null, null, null, null, null,
 1, array['handcrafted','ssiap2','partie4']::text[], 'challenge', 'published', true),
('ssiap2-hc-p4-q12','ssiap2-partie4','find-intruder','Pas un sujet briefing',
 'Lequel n''est PAS un sujet de briefing de prise de service ?',
 null, 'La vie privée des collègues n''a pas sa place en briefing professionnel.',
 2, null, null, null, null, null,
 1, array['handcrafted','ssiap2','partie4']::text[], 'challenge', 'published', true),
('ssiap2-hc-p4-q13','ssiap2-partie4','scenario','Conflit dans l''équipe',
 'Action correcte ?',
 'Deux agents SSIAP 1 sont en conflit ouvert : l''un accuse l''autre de ne pas réaliser sa part de rondes. L''ambiance perturbe le service.',
 'Recevoir séparément, écouter, recadrer factuellement, fixer des objectifs mesurables.',
 1, null, null, null, null, null,
 1, array['handcrafted','ssiap2','partie4']::text[], 'challenge', 'published', true),
('ssiap2-hc-p4-q14','ssiap2-partie4','scenario','Stagiaire en panique',
 'Action correcte ?',
 'En intervention sur un début d''incendie, un stagiaire SSIAP 1 se fige et perd ses moyens.',
 'Mettre en retrait, confier une tâche simple et utile, débriefer à froid.',
 1, null, null, null, null, null,
 1, array['handcrafted','ssiap2','partie4']::text[], 'challenge', 'published', true),
('ssiap2-hc-p4-q15','ssiap2-partie4','image-identify','Brassard sécurité',
 'Brassard fluo « SÉCURITÉ INCENDIE » signale :',
 null, 'Identification visuelle d''un agent du service de sécurité incendie en intervention/exercice.',
 1, null, null, null, null, null,
 1, array['handcrafted','ssiap2','partie4']::text[], 'challenge', 'published', true),
('ssiap2-hc-p4-q16','ssiap2-partie4','image-identify','Téléphone d''urgence',
 'Pictogramme rond bleu avec téléphone signale :',
 null, 'M005/E007 — Téléphone d''urgence / point d''appel sécurité.',
 1, null, null, null, null, null,
 1, array['handcrafted','ssiap2','partie4']::text[], 'challenge', 'published', true),
('ssiap2-hc-p4-q17','ssiap2-partie4','sequence','Prise de service',
 'Classez les étapes d''une prise de service SSIAP :',
 null, 'Lire registre/main courante → briefing par sortant → tour des installations → affectations → premier passage.',
 null, null, array[0,1,2,3,4]::integer[], null, null, null,
 1, array['handcrafted','ssiap2','partie4']::text[], 'challenge', 'published', true),
('ssiap2-hc-p4-q18','ssiap2-partie4','sequence','Exercice évacuation',
 'Classez les étapes d''un exercice d''évacuation :',
 null, 'Préparation → déclenchement → évacuation guidée → comptage → débriefing.',
 null, null, array[0,1,2,3,4]::integer[], null, null, null,
 1, array['handcrafted','ssiap2','partie4']::text[], 'challenge', 'published', true),
('ssiap2-hc-p4-q19','ssiap2-partie4','ranking','Niveaux SSIAP',
 'Classez les niveaux SSIAP du plus haut au plus bas :',
 null, 'SSIAP 3 > SSIAP 2 > SSIAP 1 > ESI.',
 null, null, array[0,1,2,3]::integer[], null, null, null,
 1, array['handcrafted','ssiap2','partie4']::text[], 'challenge', 'published', true),
('ssiap2-hc-p4-q20','ssiap2-partie4','ranking','Priorités sinistre',
 'Classez ces missions par ordre de priorité en cas de sinistre :',
 null, 'Personnes > alerte > attaque du sinistre > biens.',
 null, null, array[0,1,2,3]::integer[], null, null, null,
 1, array['handcrafted','ssiap2','partie4']::text[], 'challenge', 'published', true),
('ssiap2-hc-p4-q21','ssiap2-partie4','matching','Niveau SSIAP ↔ rôle',
 'Associez chaque niveau à son rôle :',
 null, 'SSIAP 1 = rondes, SSIAP 2 = encadrement, SSIAP 3 = direction, ESI = seconde intervention.',
 null, null, null, null, null, null,
 1, array['handcrafted','ssiap2','partie4']::text[], 'challenge', 'published', true),
('ssiap2-hc-p4-q22','ssiap2-partie4','matching','Document ↔ contenu',
 'Associez chaque document à son contenu :',
 null, 'Main courante = évènements / Registre = contrôles + exercices / CR intervention = sinistre / Cahier consignes = procédures.',
 null, null, null, null, null, null,
 1, array['handcrafted','ssiap2','partie4']::text[], 'challenge', 'published', true),
('ssiap2-hc-p4-q23','ssiap2-partie4','fill-blank','Effectif ERP cat 1',
 'Complétez l''effectif minimal :',
 null, 'ERP cat 1 : 1 SSIAP 2 + 3 SSIAP 1 par tranche de 4000 m².',
 null, null, null, array['2','1']::text[], array['1','2','3','ESI','SST']::text[],
 'Effectif minimal en ERP de 1ère catégorie : 1 SSIAP %1% + 3 SSIAP %2% par tranche de 4000 m².',
 1, array['handcrafted','ssiap2','partie4']::text[], 'challenge', 'published', true),
('ssiap2-hc-p4-q24','ssiap2-partie4','fill-blank','Missions SSIAP',
 'Complétez les missions :',
 null, 'Prévention, alerte, secours, accueil des secours.',
 null, null, null, array['alerte','secours']::text[], array['alerte','sanction','communication','formation','secours','visiteurs','pompiers']::text[],
 'Les missions du SSIAP comprennent la prévention, l''%1%, le secours aux personnes et l''accueil des %2%.',
 1, array['handcrafted','ssiap2','partie4']::text[], 'challenge', 'published', true),
('ssiap2-hc-p4-q25','ssiap2-partie4','categories','Périodicité tâches',
 'Classez ces tâches par périodicité :',
 null, 'Quotidien : ronde, briefing, main courante. Hebdo : essai alarme. Mensuel : essai SSI, allumage BAES.',
 null, null, null, null, null, null,
 1, array['handcrafted','ssiap2','partie4']::text[], 'challenge', 'published', true),
('ssiap2-hc-p4-q26','ssiap2-partie4','decision','Fumée signalée par radio',
 'Arbre de décision :',
 'Un SSIAP 1 vient de signaler par radio un dégagement de fumée localisé. Vous êtes au PCS.',
 'Confirmer la nature du sinistre, engager une action proportionnée, évacuer si non maîtrisé.',
 null, null, null, null, null, null,
 1, array['handcrafted','ssiap2','partie4']::text[], 'challenge', 'published', true);

commit;
