-- SSIAP 3 — Partie 1 « Réglementation et expertise avancée » — sub-tables
begin;

insert into public.cc_question_options (question_id, option_index, option_text) values
('ssiap3-hc-p1-q1', 0, 'R.111-1'),
('ssiap3-hc-p1-q1', 1, 'R.143 et suivants'),
('ssiap3-hc-p1-q1', 2, 'L.541-2'),
('ssiap3-hc-p1-q1', 3, 'D.123-1'),
('ssiap3-hc-p1-q2', 0, 'La loi'),
('ssiap3-hc-p1-q2', 1, 'Le décret'),
('ssiap3-hc-p1-q2', 2, 'L''arrêté ministériel'),
('ssiap3-hc-p1-q2', 3, 'La circulaire'),
('ssiap3-hc-p1-q3', 0, 'Une décision exécutoire à elle seule'),
('ssiap3-hc-p1-q3', 1, 'Un avis simple, suivi ou non par l''autorité de police (maire/préfet)'),
('ssiap3-hc-p1-q3', 2, 'Un acte juridictionnel'),
('ssiap3-hc-p1-q3', 3, 'Une simple obligation de moyens'),
('ssiap3-hc-p1-q4', 0, '6 mois'),
('ssiap3-hc-p1-q4', 1, '2 ans (J/O/U avec sommeil) ou 3 ans (autres types)'),
('ssiap3-hc-p1-q4', 2, '5 ans uniformément'),
('ssiap3-hc-p1-q4', 3, 'Aucune visite obligatoire'),
('ssiap3-hc-p1-q5', 0, 'Vrai'),
('ssiap3-hc-p1-q5', 1, 'Faux'),
('ssiap3-hc-p1-q6', 0, 'Vrai'),
('ssiap3-hc-p1-q6', 1, 'Faux'),
('ssiap3-hc-p1-q7', 0, 'Vrai'),
('ssiap3-hc-p1-q7', 1, 'Faux'),
('ssiap3-hc-p1-q8', 0, 'Conseil au chef d''établissement en sécurité incendie'),
('ssiap3-hc-p1-q8', 1, 'Veille réglementaire et normative'),
('ssiap3-hc-p1-q8', 2, 'Suivi des contrats de maintenance des installations de sécurité'),
('ssiap3-hc-p1-q8', 3, 'Gestion du budget du service de sécurité'),
('ssiap3-hc-p1-q8', 4, 'Comptabilité fournisseurs de l''entreprise'),
('ssiap3-hc-p1-q9', 0, 'Notice de sécurité'),
('ssiap3-hc-p1-q9', 1, 'Plans (intervention, évacuation, niveaux)'),
('ssiap3-hc-p1-q9', 2, 'Calculs d''effectif et de désenfumage'),
('ssiap3-hc-p1-q9', 3, 'PV de classement au feu des matériaux'),
('ssiap3-hc-p1-q9', 4, 'Bilan financier de l''exploitant'),
('ssiap3-hc-p1-q10', 0, 'Mise en demeure de l''exploitant'),
('ssiap3-hc-p1-q10', 1, 'Plan d''actions chiffré et nouvelle visite'),
('ssiap3-hc-p1-q10', 2, 'Fermeture administrative en cas de péril imminent'),
('ssiap3-hc-p1-q10', 3, 'Sanctions pénales en cas de manquements graves'),
('ssiap3-hc-p1-q10', 4, 'Fermeture définitive sans aucun recours possible'),
('ssiap3-hc-p1-q11', 0, 'CCDSA — commission consultative départementale de sécurité et accessibilité'),
('ssiap3-hc-p1-q11', 1, 'Sous-commission départementale ERP-IGH'),
('ssiap3-hc-p1-q11', 2, 'CSE / CHSCT (instances représentatives du personnel)'),
('ssiap3-hc-p1-q11', 3, 'Sous-commission communale de sécurité'),
('ssiap3-hc-p1-q12', 0, 'Arrêté du 25 juin 1980 (règlement ERP)'),
('ssiap3-hc-p1-q12', 1, 'Arrêté du 30 décembre 2011 (règlement IGH)'),
('ssiap3-hc-p1-q12', 2, 'Norme ISO 9001 (qualité)'),
('ssiap3-hc-p1-q12', 3, 'Arrêté du 31 janvier 1986 (sécurité habitation)'),
('ssiap3-hc-p1-q13', 0, 'Suivre les ordres du directeur sans broncher'),
('ssiap3-hc-p1-q13', 1, 'Alerter par écrit sur les risques pénaux, proposer un plan d''actions chiffré et daté, refuser de couvrir'),
('ssiap3-hc-p1-q13', 2, 'Appeler la presse'),
('ssiap3-hc-p1-q13', 3, 'Démissionner immédiatement sans procédure'),
('ssiap3-hc-p1-q14', 0, 'Refuser d''appliquer purement et simplement'),
('ssiap3-hc-p1-q14', 1, 'Argumenter par écrit, demander un réexamen, exercer un recours hiérarchique au préfet si besoin'),
('ssiap3-hc-p1-q14', 2, 'Saisir directement la presse'),
('ssiap3-hc-p1-q14', 3, 'Démanteler les installations litigieuses'),
('ssiap3-hc-p1-q15', 0, 'Une borne d''incendie'),
('ssiap3-hc-p1-q15', 1, 'Un extincteur fixe ou sur roues (F003)'),
('ssiap3-hc-p1-q15', 2, 'Une lance pompiers'),
('ssiap3-hc-p1-q15', 3, 'Un poteau d''incendie'),
('ssiap3-hc-p1-q16', 0, 'Une pharmacie commerciale'),
('ssiap3-hc-p1-q16', 1, 'Local / matériel de premiers secours, défibrillateur (E003)'),
('ssiap3-hc-p1-q16', 2, 'Un point de rassemblement après évacuation'),
('ssiap3-hc-p1-q16', 3, 'Une issue de secours');

insert into public.cc_question_items (question_id, item_index, item_text) values
('ssiap3-hc-p1-q17', 0, 'Constitution / traités internationaux'),
('ssiap3-hc-p1-q17', 1, 'Loi (Parlement)'),
('ssiap3-hc-p1-q17', 2, 'Décret (Conseil d''État ou simple)'),
('ssiap3-hc-p1-q17', 3, 'Arrêté (ministériel, préfectoral, municipal)'),
('ssiap3-hc-p1-q17', 4, 'Circulaire / instruction (non opposable)'),
('ssiap3-hc-p1-q18', 0, 'Visite et constat de la commission'),
('ssiap3-hc-p1-q18', 1, 'Avis défavorable motivé'),
('ssiap3-hc-p1-q18', 2, 'Notification à l''exploitant + mise en demeure du maire'),
('ssiap3-hc-p1-q18', 3, 'Plan d''actions et délai d''exécution'),
('ssiap3-hc-p1-q18', 4, 'Nouvelle visite et levée (ou fermeture)'),
('ssiap3-hc-p1-q19', 0, 'ERP type U 1ère catégorie (soins) — tous les 2 ans'),
('ssiap3-hc-p1-q19', 1, 'ERP type O 2ème catégorie (hôtel) — tous les 3 ans'),
('ssiap3-hc-p1-q19', 2, 'ERP type M 3ème catégorie (magasin) — tous les 5 ans'),
('ssiap3-hc-p1-q19', 3, 'ERP 5ème catégorie sans sommeil — sur demande du maire'),
('ssiap3-hc-p1-q20', 0, 'Ministre de l''Intérieur (national)'),
('ssiap3-hc-p1-q20', 1, 'Préfet (départemental)'),
('ssiap3-hc-p1-q20', 2, 'Maire (communal)'),
('ssiap3-hc-p1-q20', 3, 'Directeur d''établissement (local)');

insert into public.cc_question_pairs (question_id, pair_index, left_text, right_text) values
('ssiap3-hc-p1-q21', 0, 'Arrêté 25/06/1980', 'Règlement de sécurité ERP'),
('ssiap3-hc-p1-q21', 1, 'Arrêté 30/12/2011', 'Règlement de sécurité IGH'),
('ssiap3-hc-p1-q21', 2, 'Arrêté 31/01/1986', 'Sécurité dans les bâtiments d''habitation'),
('ssiap3-hc-p1-q21', 3, 'Code du travail (titre IV livre II)', 'Sécurité incendie sur les lieux de travail'),
('ssiap3-hc-p1-q22', 0, 'Maire', 'Police administrative ERP / arrêté d''autorisation'),
('ssiap3-hc-p1-q22', 1, 'Préfet', 'Police administrative IGH / commission départementale'),
('ssiap3-hc-p1-q22', 2, 'SDIS', 'Avis technique de sécurité incendie'),
('ssiap3-hc-p1-q22', 3, 'DDT', 'Avis accessibilité / urbanisme');

insert into public.cc_question_categories (question_id, category_index, category_id, category_label) values
('ssiap3-hc-p1-q25', 0, 'loi', '⚖️ Valeur législative'),
('ssiap3-hc-p1-q25', 1, 'reglement', '📜 Valeur réglementaire'),
('ssiap3-hc-p1-q25', 2, 'doctrine', '📝 Doctrine / non opposable');

insert into public.cc_question_category_items (question_id, item_index, item_text, correct_category) values
('ssiap3-hc-p1-q25', 0, 'Loi du 17/06/1955', 'loi'),
('ssiap3-hc-p1-q25', 1, 'Code de la Construction (partie législative)', 'loi'),
('ssiap3-hc-p1-q25', 2, 'Décret en Conseil d''État', 'reglement'),
('ssiap3-hc-p1-q25', 3, 'Arrêté ministériel', 'reglement'),
('ssiap3-hc-p1-q25', 4, 'Circulaire interministérielle', 'doctrine'),
('ssiap3-hc-p1-q25', 5, 'Doctrine du SDIS', 'doctrine');

insert into public.cc_question_decision_steps (question_id, step_index, step_question, options) values
('ssiap3-hc-p1-q26', 0,
 'ÉTAPE 1 — Désaccord motivé avec le SDIS sur l''interprétation d''un article. Première action ?',
 '[{"text":"Demander la motivation écrite et la jurisprudence éventuelle","nextStep":1},{"text":"Refuser publiquement et menacer de démission","nextStep":99},{"text":"Imposer mon interprétation au technicien sur place","nextStep":99}]'::jsonb),
('ssiap3-hc-p1-q26', 1,
 'ÉTAPE 2 — Le désaccord persiste. Voie à privilégier ?',
 '[{"text":"Saisine écrite du président de la commission, demande de réexamen avec arguments","nextStep":2},{"text":"Plainte aux médias","nextStep":99},{"text":"Refuser d''appliquer en attendant","nextStep":99}]'::jsonb),
('ssiap3-hc-p1-q26', 2,
 'ÉTAPE 3 — Le réexamen est défavorable. Suite ?',
 '[{"text":"Recours hiérarchique au préfet, à défaut recours contentieux au Tribunal Administratif","nextStep":null},{"text":"Faire les travaux contestés sans plus argumenter","nextStep":null},{"text":"Fermer l''établissement de force","nextStep":null}]'::jsonb);

commit;
