-- SSIAP 3 — Partie 1 « Réglementation et expertise avancée »
-- 26 challenge cc_questions covering all 12 game types — module_id = ssiap3-partie1
begin;

insert into public.cc_questions
  (id, module_id, type, title, question, scenario, explanation,
   correct_answer, correct_answers, correct_order, correct_blanks, word_bank, sentence,
   difficulty, tags, pool, status, is_active)
values
('ssiap3-hc-p1-q1','ssiap3-partie1','quiz','Article CCH ERP',
 'Depuis la recodification 2021, le règlement de sécurité ERP est codifié à partir de l''article :',
 null, 'CCH article R.143-1 et suivants depuis 2021 (anciennement R.123-1 et suivants).',
 1, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie1']::text[], 'challenge', 'published', true),
('ssiap3-hc-p1-q2','ssiap3-partie1','quiz','Hiérarchie des textes',
 'Dans la hiérarchie des normes, lequel a la valeur juridique la plus élevée ?',
 null, 'Pyramide de Kelsen : Constitution > traités > loi > décret > arrêté > circulaire (non opposable).',
 0, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie1']::text[], 'challenge', 'published', true),
('ssiap3-hc-p1-q3','ssiap3-partie1','quiz','Avis commission',
 'L''avis de la commission de sécurité est :',
 null, 'Avis simple : il oriente la décision du maire ou du préfet, qui restent les autorités de police.',
 1, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie1']::text[], 'challenge', 'published', true),
('ssiap3-hc-p1-q4','ssiap3-partie1','quiz','Périodicité ERP 1ère cat',
 'La périodicité des visites périodiques d''un ERP de 1ère catégorie est généralement :',
 null, '2 ans pour les types avec sommeil (J/O/U) en 1ère catégorie ; 3 ans pour les autres.',
 1, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie1']::text[], 'challenge', 'published', true),
('ssiap3-hc-p1-q5','ssiap3-partie1','true-false','Responsabilité pénale',
 'Le chef de service de sécurité incendie peut être tenu pénalement responsable en cas de manquement à ses obligations.',
 null, 'VRAI — Mise en danger d''autrui, blessures involontaires, homicide involontaire.',
 0, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie1']::text[], 'challenge', 'published', true),
('ssiap3-hc-p1-q6','ssiap3-partie1','true-false','Valeur circulaire',
 'Une circulaire ministérielle a la même valeur juridique qu''un arrêté.',
 null, 'FAUX — Une circulaire est une instruction interne, sans valeur réglementaire opposable.',
 1, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie1']::text[], 'challenge', 'published', true),
('ssiap3-hc-p1-q7','ssiap3-partie1','true-false','AT par le maire',
 'En ERP, l''autorisation de travaux est délivrée par le maire après avis de la commission de sécurité.',
 null, 'VRAI — Le maire est l''autorité de police compétente en ERP.',
 0, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie1']::text[], 'challenge', 'published', true),
('ssiap3-hc-p1-q8','ssiap3-partie1','multiple-select','Missions chef service',
 'Quelles sont les obligations d''un chef de service SSIAP 3 ?',
 null, 'Conseil, veille réglementaire, suivi maintenance, budget. La compta fournisseurs n''est pas SSIAP.',
 null, array[0,1,2,3]::integer[], null, null, null, null,
 1, array['handcrafted','ssiap3','partie1']::text[], 'challenge', 'published', true),
('ssiap3-hc-p1-q9','ssiap3-partie1','multiple-select','Dossier de sécurité',
 'Quels documents composent le dossier de sécurité d''un ERP ?',
 null, 'Notice, plans, calculs, PV classement matériaux. Pas le bilan financier.',
 null, array[0,1,2,3]::integer[], null, null, null, null,
 1, array['handcrafted','ssiap3','partie1']::text[], 'challenge', 'published', true),
('ssiap3-hc-p1-q10','ssiap3-partie1','multiple-select','Suites avis défavorable',
 'Quelles sont les suites possibles d''un avis défavorable ?',
 null, 'Mise en demeure, plan d''actions, fermeture admin si péril, sanctions pénales. Pas de fermeture définitive sans recours.',
 null, array[0,1,2,3]::integer[], null, null, null, null,
 1, array['handcrafted','ssiap3','partie1']::text[], 'challenge', 'published', true),
('ssiap3-hc-p1-q11','ssiap3-partie1','find-intruder','Pas une commission',
 'Lequel n''est PAS une commission de sécurité ?',
 null, 'Le CSE (ex-CHSCT) est une instance représentative du personnel.',
 2, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie1']::text[], 'challenge', 'published', true),
('ssiap3-hc-p1-q12','ssiap3-partie1','find-intruder','Pas un texte SSI',
 'Lequel n''est PAS un texte réglementaire de sécurité incendie ?',
 null, 'ISO 9001 = norme qualité, pas sécurité incendie.',
 2, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie1']::text[], 'challenge', 'published', true),
('ssiap3-hc-p1-q13','ssiap3-partie1','scenario','Pression du directeur',
 'Action correcte ?',
 'La commission rend un avis défavorable (RIA non conformes, BAES vétustes). Le directeur veut continuer l''exploitation comme si de rien n''était.',
 'Alerter par écrit sur les risques pénaux, proposer un plan d''actions chiffré, refuser de couvrir.',
 1, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie1']::text[], 'challenge', 'published', true),
('ssiap3-hc-p1-q14','ssiap3-partie1','scenario','Désaccord avec commission',
 'Action correcte ?',
 'Vous êtes en désaccord motivé avec la commission sur l''interprétation d''un article du règlement.',
 'Argumenter par écrit, demander un réexamen, recours hiérarchique au préfet si nécessaire.',
 1, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie1']::text[], 'challenge', 'published', true),
('ssiap3-hc-p1-q15','ssiap3-partie1','image-identify','Extincteur fixe',
 'Pictogramme rouge avec extincteur sur roues / fixe :',
 null, 'F003 — Extincteur fixe ou sur roues.',
 1, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie1']::text[], 'challenge', 'published', true),
('ssiap3-hc-p1-q16','ssiap3-partie1','image-identify','Premier secours',
 'Pictogramme vert avec croix blanche :',
 null, 'E003 — Local / matériel de premiers secours.',
 1, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie1']::text[], 'challenge', 'published', true),
('ssiap3-hc-p1-q17','ssiap3-partie1','sequence','Hiérarchie des textes',
 'Classez ces normes du plus contraignant au moins :',
 null, 'Constitution > loi > décret > arrêté > circulaire.',
 null, null, array[0,1,2,3,4]::integer[], null, null, null,
 1, array['handcrafted','ssiap3','partie1']::text[], 'challenge', 'published', true),
('ssiap3-hc-p1-q18','ssiap3-partie1','sequence','Avis défavorable',
 'Classez les étapes de la procédure suite à un avis défavorable :',
 null, 'Visite → avis défavorable → notification + mise en demeure → plan d''actions → nouvelle visite.',
 null, null, array[0,1,2,3,4]::integer[], null, null, null,
 1, array['handcrafted','ssiap3','partie1']::text[], 'challenge', 'published', true),
('ssiap3-hc-p1-q19','ssiap3-partie1','ranking','Visites par fréquence',
 'Classez ces visites par fréquence (du plus fréquent au plus rare) :',
 null, 'U 1ère cat (2 ans) > O 2ème cat (3 ans) > M 3ème cat (5 ans) > 5ème cat sans sommeil.',
 null, null, array[0,1,2,3]::integer[], null, null, null,
 1, array['handcrafted','ssiap3','partie1']::text[], 'challenge', 'published', true),
('ssiap3-hc-p1-q20','ssiap3-partie1','ranking','Étendue d''autorité',
 'Classez ces autorités par étendue de compétence (la plus large d''abord) :',
 null, 'Ministre > Préfet > Maire > Directeur.',
 null, null, array[0,1,2,3]::integer[], null, null, null,
 1, array['handcrafted','ssiap3','partie1']::text[], 'challenge', 'published', true),
('ssiap3-hc-p1-q21','ssiap3-partie1','matching','Texte ↔ domaine',
 'Associez chaque texte réglementaire à son domaine :',
 null, '25/06/1980 = ERP / 30/12/2011 = IGH / 31/01/1986 = habitation / Code travail = lieux de travail.',
 null, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie1']::text[], 'challenge', 'published', true),
('ssiap3-hc-p1-q22','ssiap3-partie1','matching','Acteur ↔ rôle',
 'Associez chaque acteur à son rôle :',
 null, 'Maire = ERP / Préfet = IGH / SDIS = avis technique / DDT = accessibilité.',
 null, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie1']::text[], 'challenge', 'published', true),
('ssiap3-hc-p1-q23','ssiap3-partie1','fill-blank','Règlement ERP',
 'Complétez la date du règlement ERP :',
 null, 'Arrêté du 25 juin 1980 — règlement de sécurité ERP.',
 null, null, null, array['25','1980']::text[], array['25','30','31','15','1980','1986','2011','2002']::text[],
 'L''arrêté du %1% juin %2% constitue le règlement de sécurité ERP.',
 1, array['handcrafted','ssiap3','partie1']::text[], 'challenge', 'published', true),
('ssiap3-hc-p1-q24','ssiap3-partie1','fill-blank','Périodicités visites',
 'Complétez les périodicités :',
 null, 'U 1ère cat : 2 ans / R 1ère cat : 3 ans.',
 null, null, null, array['2','3']::text[], array['1','2','3','5','10','20']::text[],
 'Les visites périodiques d''un ERP de 1ère catégorie type U (soins) ont lieu tous les %1% ans et type R (enseignement) tous les %2% ans.',
 1, array['handcrafted','ssiap3','partie1']::text[], 'challenge', 'published', true),
('ssiap3-hc-p1-q25','ssiap3-partie1','categories','Valeur juridique',
 'Classez ces actes selon leur valeur juridique :',
 null, 'Loi / Règlement (décret, arrêté) / Doctrine (circulaire, doctrine SDIS).',
 null, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie1']::text[], 'challenge', 'published', true),
('ssiap3-hc-p1-q26','ssiap3-partie1','decision','Désaccord SDIS',
 'Arbre de décision :',
 'Lors d''une visite, vous êtes en désaccord motivé avec le SDIS sur l''interprétation d''un article du règlement.',
 'Motivation écrite, recours gracieux puis hiérarchique, contentieux TA en dernier ressort.',
 null, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie1']::text[], 'challenge', 'published', true);

commit;
