-- SSIAP 3 — Partie 2 « Direction du service / Management stratégique »
-- 26 challenge cc_questions covering all 12 game types — module_id = ssiap3-partie2
begin;

insert into public.cc_questions
  (id, module_id, type, title, question, scenario, explanation,
   correct_answer, correct_answers, correct_order, correct_blanks, word_bank, sentence,
   difficulty, tags, pool, status, is_active)
values
('ssiap3-hc-p2-q1','ssiap3-partie2','quiz','Périmètre hiérarchique',
 'Le SSIAP 3 est responsable hiérarchiquement de :',
 null, 'Le chef de service sécurité incendie encadre la totalité du service (SSIAP 1/2 + administratif rattaché).',
 1, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie2']::text[], 'challenge', 'published', true),
('ssiap3-hc-p2-q2','ssiap3-partie2','quiz','Évaluation annuelle',
 'L''évaluation annuelle d''un agent SSIAP porte essentiellement sur :',
 null, 'Compétences techniques + comportementales + atteinte des objectifs.',
 1, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie2']::text[], 'challenge', 'published', true),
('ssiap3-hc-p2-q3','ssiap3-partie2','quiz','Recyclage SSIAP',
 'Le recyclage SSIAP doit être effectué :',
 null, 'Recyclage triennal (arrêté 02/05/2005).',
 1, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie2']::text[], 'challenge', 'published', true),
('ssiap3-hc-p2-q4','ssiap3-partie2','quiz','Délégation de pouvoir',
 'Une délégation de pouvoir doit être :',
 null, 'Écrite, datée, signée, claire, limitée à un domaine et acceptée par le délégataire.',
 1, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie2']::text[], 'challenge', 'published', true),
('ssiap3-hc-p2-q5','ssiap3-partie2','true-false','Conseil et décision',
 'Le chef de service SSIAP 3 conseille le chef d''établissement, mais c''est ce dernier qui décide en dernier ressort.',
 null, 'VRAI — Responsabilité finale du chef d''établissement.',
 0, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie2']::text[], 'challenge', 'published', true),
('ssiap3-hc-p2-q6','ssiap3-partie2','true-false','Cellule de crise',
 'Une cellule de crise se met en place uniquement quand le sinistre est terminé.',
 null, 'FAUX — Activation dès la confirmation du sinistre majeur.',
 1, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie2']::text[], 'challenge', 'published', true),
('ssiap3-hc-p2-q7','ssiap3-partie2','true-false','Formation continue',
 'La formation continue n''est pas obligatoire pour les SSIAP.',
 null, 'FAUX — Recyclage triennal obligatoire.',
 1, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie2']::text[], 'challenge', 'published', true),
('ssiap3-hc-p2-q8','ssiap3-partie2','multiple-select','Indicateurs sécurité',
 'Quels indicateurs de performance sont pertinents pour un service de sécurité ?',
 null, 'Conformité, faux signaux, délais d''intervention, présence exercices.',
 null, array[0,1,2,3]::integer[], null, null, null, null,
 1, array['handcrafted','ssiap3','partie2']::text[], 'challenge', 'published', true),
('ssiap3-hc-p2-q9','ssiap3-partie2','multiple-select','Cellule de crise',
 'Quels acteurs composent une cellule de crise ?',
 null, 'Direction, SSIAP 3, communication, liaison secours.',
 null, array[0,1,2,3]::integer[], null, null, null, null,
 1, array['handcrafted','ssiap3','partie2']::text[], 'challenge', 'published', true),
('ssiap3-hc-p2-q10','ssiap3-partie2','multiple-select','Recrutement SSIAP',
 'Quelles étapes sont incontournables lors du recrutement d''un SSIAP ?',
 null, 'Carte SSIAP valide, aptitudes médicales, entretien, intégration.',
 null, array[0,1,2,3]::integer[], null, null, null, null,
 1, array['handcrafted','ssiap3','partie2']::text[], 'challenge', 'published', true),
('ssiap3-hc-p2-q11','ssiap3-partie2','find-intruder','Pas un mode management',
 'Lequel n''est PAS un mode de management ?',
 null, 'Le management aléatoire n''est pas un mode reconnu.',
 2, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie2']::text[], 'challenge', 'published', true),
('ssiap3-hc-p2-q12','ssiap3-partie2','find-intruder','Pas un indicateur',
 'Lequel n''est PAS un indicateur pertinent pour la qualité d''un service sécurité ?',
 null, 'Le taux de change n''a aucun lien avec la sécurité.',
 2, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie2']::text[], 'challenge', 'published', true),
('ssiap3-hc-p2-q13','ssiap3-partie2','scenario','Sous-effectif chronique',
 'Action correcte ?',
 'Le service tourne en sous-effectif depuis 3 mois. Les agents enchaînent les heures supplémentaires. Le risque d''erreur et de burnout monte.',
 'Documenter, alerter par écrit la direction avec analyse de risque, proposer un plan de recrutement chiffré.',
 1, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie2']::text[], 'challenge', 'published', true),
('ssiap3-hc-p2-q14','ssiap3-partie2','scenario','Faux appels répétés',
 'Action correcte ?',
 'La même tête de détection se déclenche intempestivement 4 nuits d''affilée. Les pompiers interviennent à chaque fois et envisagent une facturation pour appel abusif.',
 'Investiguer la cause, missionner le mainteneur, consigner.',
 1, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie2']::text[], 'challenge', 'published', true),
('ssiap3-hc-p2-q15','ssiap3-partie2','image-identify','EPI obligatoires',
 'Pictogramme rond bleu avec casque et chaussures :',
 null, 'M002 / M008 — Obligation de port des EPI.',
 1, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie2']::text[], 'challenge', 'published', true),
('ssiap3-hc-p2-q16','ssiap3-partie2','image-identify','Direction PCS',
 'Panneau bleu fléché avec mention « PC sécurité » :',
 null, 'Direction du PC sécurité incendie / poste central de sécurité.',
 1, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie2']::text[], 'challenge', 'published', true),
('ssiap3-hc-p2-q17','ssiap3-partie2','sequence','Cycle de vie agent SSIAP',
 'Classez les étapes de la vie d''un agent SSIAP dans le service :',
 null, 'Recrutement → intégration → mise en situation tutorée → autonomie + évaluation → recyclage.',
 null, null, array[0,1,2,3,4]::integer[], null, null, null,
 1, array['handcrafted','ssiap3','partie2']::text[], 'challenge', 'published', true),
('ssiap3-hc-p2-q18','ssiap3-partie2','sequence','Cellule de crise',
 'Classez les étapes d''une cellule de crise :',
 null, 'Activation → recueil → décision/coordination → communication → désactivation + REX.',
 null, null, array[0,1,2,3,4]::integer[], null, null, null,
 1, array['handcrafted','ssiap3','partie2']::text[], 'challenge', 'published', true),
('ssiap3-hc-p2-q19','ssiap3-partie2','ranking','Niveaux de criticité',
 'Classez ces évènements du plus critique au moins critique :',
 null, 'Crise majeure > incident grave > anomalie > observation mineure.',
 null, null, array[0,1,2,3]::integer[], null, null, null,
 1, array['handcrafted','ssiap3','partie2']::text[], 'challenge', 'published', true),
('ssiap3-hc-p2-q20','ssiap3-partie2','ranking','Style de management',
 'Classez les styles de management du plus directif au plus délégatif :',
 null, 'Directif > Persuasif > Participatif > Délégatif (Hersey-Blanchard).',
 null, null, array[0,1,2,3]::integer[], null, null, null,
 1, array['handcrafted','ssiap3','partie2']::text[], 'challenge', 'published', true),
('ssiap3-hc-p2-q21','ssiap3-partie2','matching','Acteur cellule ↔ rôle',
 'Associez chaque acteur à son rôle dans la cellule de crise :',
 null, 'Direction = stratégie / SSIAP 3 = opérationnel sécu / Communication = messages / Liaison pompiers = interface secours.',
 null, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie2']::text[], 'challenge', 'published', true),
('ssiap3-hc-p2-q22','ssiap3-partie2','matching','Document RH ↔ contenu',
 'Associez chaque document RH à son contenu :',
 null, 'Fiche de poste = missions / Entretien annuel = bilan + objectifs / Plan de formation = programme / Délégation = transfert.',
 null, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie2']::text[], 'challenge', 'published', true),
('ssiap3-hc-p2-q23','ssiap3-partie2','fill-blank','Recyclage SSIAP',
 'Complétez les valeurs SSIAP :',
 null, 'Recyclage tous les 3 ans. Remise à niveau au-delà de 36 mois sans activité.',
 null, null, null, array['3','36']::text[], array['1','3','5','10','12','24','36','48']::text[],
 'Le recyclage SSIAP a lieu tous les %1% ans. Une remise à niveau est obligatoire après une interruption de plus de %2% mois.',
 1, array['handcrafted','ssiap3','partie2']::text[], 'challenge', 'published', true),
('ssiap3-hc-p2-q24','ssiap3-partie2','fill-blank','Missions SSIAP 3',
 'Complétez les missions du SSIAP 3 :',
 null, 'Conseil + management + technique + budget.',
 null, null, null, array['conseil','management']::text[], array['conseil','vente','management','contrôle','sanction','budget']::text[],
 'Les 4 missions du SSIAP 3 : %1% au chef d''établissement, %2% du service, technique, budget.',
 1, array['handcrafted','ssiap3','partie2']::text[], 'challenge', 'published', true),
('ssiap3-hc-p2-q25','ssiap3-partie2','categories','Axes stratégiques',
 'Classez ces actions selon l''axe stratégique :',
 null, 'Humain (RH, formation), Technique (équipements), Organisationnel (procédures).',
 null, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie2']::text[], 'challenge', 'published', true),
('ssiap3-hc-p2-q26','ssiap3-partie2','decision','Astreinte de nuit',
 'Arbre de décision :',
 'Vous êtes SSIAP 3 d''astreinte. À 3h du matin, votre téléphone sonne : début d''incendie + 1 blessé dans une chambre d''hôtel (type O), service de nuit en sous-effectif.',
 'Confirmer l''alerte 18, recueillir info terrain, déclencher cellule de crise, accueillir secours.',
 null, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie2']::text[], 'challenge', 'published', true);

commit;
