-- SSIAP 3 — Partie 2 « Direction du service / Management stratégique » — sub-tables
begin;

insert into public.cc_question_options (question_id, option_index, option_text) values
('ssiap3-hc-p2-q1', 0, 'Tous les services de l''entreprise'),
('ssiap3-hc-p2-q1', 1, 'Le service de sécurité incendie (SSIAP 1, 2, et personnel administratif sécurité)'),
('ssiap3-hc-p2-q1', 2, 'Uniquement de lui-même'),
('ssiap3-hc-p2-q1', 3, 'Le service maintenance technique du bâtiment'),
('ssiap3-hc-p2-q2', 0, 'Sa vie privée'),
('ssiap3-hc-p2-q2', 1, 'Ses compétences techniques, comportementales et l''atteinte de ses objectifs'),
('ssiap3-hc-p2-q2', 2, 'Son apparence physique'),
('ssiap3-hc-p2-q2', 3, 'Sa popularité dans l''équipe'),
('ssiap3-hc-p2-q3', 0, 'Tous les ans'),
('ssiap3-hc-p2-q3', 1, 'Tous les 3 ans'),
('ssiap3-hc-p2-q3', 2, 'Tous les 5 ans'),
('ssiap3-hc-p2-q3', 3, 'Une seule fois en début de carrière'),
('ssiap3-hc-p2-q4', 0, 'Verbale entre collègues'),
('ssiap3-hc-p2-q4', 1, 'Écrite, datée, signée, claire et limitée à un domaine précis'),
('ssiap3-hc-p2-q4', 2, 'Implicite par l''usage'),
('ssiap3-hc-p2-q4', 3, 'Annuelle systématique sans contenu défini'),
('ssiap3-hc-p2-q5', 0, 'Vrai'),
('ssiap3-hc-p2-q5', 1, 'Faux'),
('ssiap3-hc-p2-q6', 0, 'Vrai'),
('ssiap3-hc-p2-q6', 1, 'Faux'),
('ssiap3-hc-p2-q7', 0, 'Vrai'),
('ssiap3-hc-p2-q7', 1, 'Faux'),
('ssiap3-hc-p2-q8', 0, 'Taux de conformité aux contrôles périodiques'),
('ssiap3-hc-p2-q8', 1, 'Nombre de levées de doute / faux signaux'),
('ssiap3-hc-p2-q8', 2, 'Délais d''intervention moyens sur sinistre'),
('ssiap3-hc-p2-q8', 3, 'Taux de présence aux exercices d''évacuation'),
('ssiap3-hc-p2-q8', 4, 'Nombre de pauses café par agent'),
('ssiap3-hc-p2-q9', 0, 'Direction de l''établissement'),
('ssiap3-hc-p2-q9', 1, 'Chef de service sécurité (SSIAP 3)'),
('ssiap3-hc-p2-q9', 2, 'Chargé de communication interne / externe'),
('ssiap3-hc-p2-q9', 3, 'Liaison avec les secours extérieurs'),
('ssiap3-hc-p2-q9', 4, 'Service comptabilité fournisseurs'),
('ssiap3-hc-p2-q10', 0, 'Vérification de la carte SSIAP en cours de validité'),
('ssiap3-hc-p2-q10', 1, 'Vérification des aptitudes médicales'),
('ssiap3-hc-p2-q10', 2, 'Entretien et évaluation des compétences'),
('ssiap3-hc-p2-q10', 3, 'Période d''intégration et d''habilitation au site'),
('ssiap3-hc-p2-q10', 4, 'Test en piscine'),
('ssiap3-hc-p2-q11', 0, 'Management directif'),
('ssiap3-hc-p2-q11', 1, 'Management participatif'),
('ssiap3-hc-p2-q11', 2, 'Management aléatoire'),
('ssiap3-hc-p2-q11', 3, 'Management délégatif'),
('ssiap3-hc-p2-q12', 0, 'Taux d''incidents'),
('ssiap3-hc-p2-q12', 1, 'Taux de conformité réglementaire'),
('ssiap3-hc-p2-q12', 2, 'Taux de change Euro / Dollar'),
('ssiap3-hc-p2-q12', 3, 'Taux de turn-over de l''équipe'),
('ssiap3-hc-p2-q13', 0, 'Continuer en serrant les dents'),
('ssiap3-hc-p2-q13', 1, 'Documenter, alerter par écrit la direction avec analyse de risque, proposer un plan de recrutement chiffré'),
('ssiap3-hc-p2-q13', 2, 'Démissionner immédiatement'),
('ssiap3-hc-p2-q13', 3, 'Réduire le nombre de rondes pour compenser'),
('ssiap3-hc-p2-q14', 0, 'Désactiver discrètement la zone de détection'),
('ssiap3-hc-p2-q14', 1, 'Investiguer (poussière, condensation, panne), demander intervention mainteneur, consigner les faux appels'),
('ssiap3-hc-p2-q14', 2, 'Poursuivre comme si de rien n''était'),
('ssiap3-hc-p2-q14', 3, 'Couper le contrat avec les pompiers'),
('ssiap3-hc-p2-q15', 0, 'Une zone de chantier'),
('ssiap3-hc-p2-q15', 1, 'Une obligation de port d''EPI (M002 / M008)'),
('ssiap3-hc-p2-q15', 2, 'Une interdiction'),
('ssiap3-hc-p2-q15', 3, 'Un avertissement de chute'),
('ssiap3-hc-p2-q16', 0, 'Une zone d''attente client'),
('ssiap3-hc-p2-q16', 1, 'La direction du PC sécurité incendie (poste central de sécurité)'),
('ssiap3-hc-p2-q16', 2, 'Un local administratif'),
('ssiap3-hc-p2-q16', 3, 'Une issue de secours');

insert into public.cc_question_items (question_id, item_index, item_text) values
('ssiap3-hc-p2-q17', 0, 'Recrutement et sélection'),
('ssiap3-hc-p2-q17', 1, 'Intégration et habilitation au site'),
('ssiap3-hc-p2-q17', 2, 'Mise en situation tutorée'),
('ssiap3-hc-p2-q17', 3, 'Autonomie et évaluation continue'),
('ssiap3-hc-p2-q17', 4, 'Recyclage triennal et perspectives d''évolution'),
('ssiap3-hc-p2-q18', 0, 'Activation de la cellule'),
('ssiap3-hc-p2-q18', 1, 'Recueil et analyse des informations'),
('ssiap3-hc-p2-q18', 2, 'Décision et coordination des actions'),
('ssiap3-hc-p2-q18', 3, 'Communication interne et externe'),
('ssiap3-hc-p2-q18', 4, 'Désactivation et retour d''expérience'),
('ssiap3-hc-p2-q19', 0, 'Crise majeure (victimes, fermeture site)'),
('ssiap3-hc-p2-q19', 1, 'Incident grave (intervention pompiers obligatoire)'),
('ssiap3-hc-p2-q19', 2, 'Anomalie (DAS partiellement HS, à corriger sous délai)'),
('ssiap3-hc-p2-q19', 3, 'Observation mineure (consignée, sans urgence)'),
('ssiap3-hc-p2-q20', 0, 'Directif — consignes strictes'),
('ssiap3-hc-p2-q20', 1, 'Persuasif — explications + adhésion'),
('ssiap3-hc-p2-q20', 2, 'Participatif — co-construction'),
('ssiap3-hc-p2-q20', 3, 'Délégatif — autonomie totale');

insert into public.cc_question_pairs (question_id, pair_index, left_text, right_text) values
('ssiap3-hc-p2-q21', 0, 'Direction de l''établissement', 'Décision stratégique'),
('ssiap3-hc-p2-q21', 1, 'SSIAP 3', 'Coordination opérationnelle sécurité'),
('ssiap3-hc-p2-q21', 2, 'Communication', 'Messages internes et externes'),
('ssiap3-hc-p2-q21', 3, 'Liaison pompiers', 'Interface avec les secours extérieurs'),
('ssiap3-hc-p2-q22', 0, 'Fiche de poste', 'Description des missions et compétences attendues'),
('ssiap3-hc-p2-q22', 1, 'Entretien annuel', 'Bilan de l''année + objectifs N+1'),
('ssiap3-hc-p2-q22', 2, 'Plan de formation', 'Programme annuel des actions de formation'),
('ssiap3-hc-p2-q22', 3, 'Délégation de pouvoir', 'Transfert formel et écrit d''une responsabilité');

insert into public.cc_question_categories (question_id, category_index, category_id, category_label) values
('ssiap3-hc-p2-q25', 0, 'humain', '👥 Humain (RH)'),
('ssiap3-hc-p2-q25', 1, 'technique', '🔧 Technique'),
('ssiap3-hc-p2-q25', 2, 'organisationnel', '🗂️ Organisationnel');

insert into public.cc_question_category_items (question_id, item_index, item_text, correct_category) values
('ssiap3-hc-p2-q25', 0, 'Recrutement d''un nouvel agent SSIAP 1', 'humain'),
('ssiap3-hc-p2-q25', 1, 'Renouvellement du parc d''extincteurs', 'technique'),
('ssiap3-hc-p2-q25', 2, 'Mise à jour des consignes écrites', 'organisationnel'),
('ssiap3-hc-p2-q25', 3, 'Plan de formation triennal', 'humain'),
('ssiap3-hc-p2-q25', 4, 'Audit interne du SSI', 'technique'),
('ssiap3-hc-p2-q25', 5, 'Refonte de l''organigramme du service', 'organisationnel');

insert into public.cc_question_decision_steps (question_id, step_index, step_question, options) values
('ssiap3-hc-p2-q26', 0,
 'ÉTAPE 1 — 3h du matin, appel d''astreinte : début d''incendie + 1 blessé dans une chambre. Premier réflexe au téléphone ?',
 '[{"text":"Demander la situation précise, confirmer l''appel du 18, déclencher la cellule de crise","nextStep":1},{"text":"Dire « je passerai voir demain matin »","nextStep":99},{"text":"Couper le téléphone et reprendre le sommeil","nextStep":99}]'::jsonb),
('ssiap3-hc-p2-q26', 1,
 'ÉTAPE 2 — En route vers le site. Quelles informations recueillir ?',
 '[{"text":"Décompte des occupants évacués, état du blessé, position du sinistre, secours arrivés","nextStep":2},{"text":"Liste des plats du restaurant","nextStep":99},{"text":"Comptes bancaires de l''hôtel","nextStep":99}]'::jsonb),
('ssiap3-hc-p2-q26', 2,
 'ÉTAPE 3 — Sur site, situation maîtrisée. Actions ?',
 '[{"text":"Accueil pompiers + mise en sécurité + rapport préliminaire à la direction + cellule de crise","nextStep":null},{"text":"Reprendre le sommeil","nextStep":null},{"text":"Remettre en marche le SSI sans vérification","nextStep":null}]'::jsonb);

commit;
