-- SSIAP 3 — Partie 3 « Expertise technique et ingénierie » — sub-tables
begin;

insert into public.cc_question_options (question_id, option_index, option_text) values
('ssiap3-hc-p3-q1', 0, 'Sa température d''auto-inflammation'),
('ssiap3-hc-p3-q1', 1, 'Les critères R / E / I (résistance, étanchéité, isolation) suivis d''une durée en minutes'),
('ssiap3-hc-p3-q1', 2, 'Sa charge calorifique en MJ/m²'),
('ssiap3-hc-p3-q1', 3, 'Sa réaction au feu (euroclasse)'),
('ssiap3-hc-p3-q2', 0, 'Un coupe-feu d''1 minute'),
('ssiap3-hc-p3-q2', 1, 'Une porte coupe-feu certifiée 1 heure (EI 60)'),
('ssiap3-hc-p3-q2', 2, 'Une porte communicante simple'),
('ssiap3-hc-p3-q2', 3, 'Une porte de service'),
('ssiap3-hc-p3-q3', 0, 'Très facilement combustible'),
('ssiap3-hc-p3-q3', 1, 'Incombustible'),
('ssiap3-hc-p3-q3', 2, 'Combustible difficilement inflammable'),
('ssiap3-hc-p3-q3', 3, 'Combustible projetable (gouttes incandescentes)'),
('ssiap3-hc-p3-q4', 0, 'Pour la décoration intérieure'),
('ssiap3-hc-p3-q4', 1, 'Pour démontrer une équivalence quand le règlement prescriptif ne suffit pas (atrium, projet complexe)'),
('ssiap3-hc-p3-q4', 2, 'Pour calculer le budget annuel'),
('ssiap3-hc-p3-q4', 3, 'Pour rédiger les contrats de travail'),
('ssiap3-hc-p3-q5', 0, 'Vrai'),
('ssiap3-hc-p3-q5', 1, 'Faux'),
('ssiap3-hc-p3-q6', 0, 'Vrai'),
('ssiap3-hc-p3-q6', 1, 'Faux'),
('ssiap3-hc-p3-q7', 0, 'Vrai'),
('ssiap3-hc-p3-q7', 1, 'Faux'),
('ssiap3-hc-p3-q8', 0, 'Bouches d''extraction et de soufflage'),
('ssiap3-hc-p3-q8', 1, 'Conduits coupe-feu et clapets'),
('ssiap3-hc-p3-q8', 2, 'Ventilateurs de désenfumage haute température'),
('ssiap3-hc-p3-q8', 3, 'Coffrets de relayage CMSI'),
('ssiap3-hc-p3-q8', 4, 'Onduleurs informatiques'),
('ssiap3-hc-p3-q9', 0, 'R — Résistance mécanique (capacité portante)'),
('ssiap3-hc-p3-q9', 1, 'E — Étanchéité aux flammes et fumées'),
('ssiap3-hc-p3-q9', 2, 'I — Isolation thermique de la face non exposée'),
('ssiap3-hc-p3-q9', 3, 'F — Flammes (critère inexistant en R/E/I)'),
('ssiap3-hc-p3-q10', 0, 'Notice de sécurité'),
('ssiap3-hc-p3-q10', 1, 'Plans (intervention, masse, niveaux)'),
('ssiap3-hc-p3-q10', 2, 'Calculs d''effectifs et de désenfumage'),
('ssiap3-hc-p3-q10', 3, 'Étude de stabilité et dimensionnement au feu'),
('ssiap3-hc-p3-q10', 4, 'Étude marketing'),
('ssiap3-hc-p3-q11', 0, 'NF S 61-933 (SSI règles d''installation)'),
('ssiap3-hc-p3-q11', 1, 'NF EN 671 (RIA)'),
('ssiap3-hc-p3-q11', 2, 'NF P 98-080 (chaussées routières)'),
('ssiap3-hc-p3-q11', 3, 'NF S 61-970 (SSI exploitation maintenance)'),
('ssiap3-hc-p3-q12', 0, 'A1 — incombustible'),
('ssiap3-hc-p3-q12', 1, 'B — très peu combustible'),
('ssiap3-hc-p3-q12', 2, 'G — classe inexistante'),
('ssiap3-hc-p3-q12', 3, 'F — classe la plus combustible'),
('ssiap3-hc-p3-q13', 0, 'Ne rien faire, ça tiendra le week-end'),
('ssiap3-hc-p3-q13', 1, 'Mesures compensatoires (ronde renforcée, balisage local, info direction) + consignation'),
('ssiap3-hc-p3-q13', 2, 'Évacuer tout l''établissement immédiatement'),
('ssiap3-hc-p3-q13', 3, 'Désactiver toute la détection'),
('ssiap3-hc-p3-q14', 0, 'Réaliser les travaux discrètement sans déclaration'),
('ssiap3-hc-p3-q14', 1, 'Refuser, expliquer qu''une AT + notice sont requises, accompagner la procédure'),
('ssiap3-hc-p3-q14', 2, 'Démissionner immédiatement'),
('ssiap3-hc-p3-q14', 3, 'Fermer définitivement la salle'),
('ssiap3-hc-p3-q15', 0, 'Un robinet d''eau froide'),
('ssiap3-hc-p3-q15', 1, 'Une colonne sèche / humide pour les pompiers (F005/F006)'),
('ssiap3-hc-p3-q15', 2, 'Un climatiseur'),
('ssiap3-hc-p3-q15', 3, 'Une lance d''arrosage'),
('ssiap3-hc-p3-q16', 0, 'Une marque commerciale'),
('ssiap3-hc-p3-q16', 1, 'Le classement français de réaction au feu (M0 à M4)'),
('ssiap3-hc-p3-q16', 2, 'Une mesure métrique'),
('ssiap3-hc-p3-q16', 3, 'Un avertissement médecin');

insert into public.cc_question_items (question_id, item_index, item_text) values
('ssiap3-hc-p3-q17', 0, 'Diagnostic et analyse de risques'),
('ssiap3-hc-p3-q17', 1, 'Définition des objectifs de sécurité'),
('ssiap3-hc-p3-q17', 2, 'Modélisations et simulations (FDS, CFAST)'),
('ssiap3-hc-p3-q17', 3, 'Validation par le bureau d''études et le SDIS'),
('ssiap3-hc-p3-q17', 4, 'Mise en œuvre et suivi'),
('ssiap3-hc-p3-q18', 0, 'Demande d''essai par le fabricant'),
('ssiap3-hc-p3-q18', 1, 'Essais en laboratoire agréé'),
('ssiap3-hc-p3-q18', 2, 'Délivrance d''un PV de classement'),
('ssiap3-hc-p3-q18', 3, 'Marquage CE / euroclasse sur le produit'),
('ssiap3-hc-p3-q18', 4, 'Suivi de production et renouvellement périodique'),
('ssiap3-hc-p3-q19', 0, 'A1 — incombustible'),
('ssiap3-hc-p3-q19', 1, 'A2 — très peu combustible'),
('ssiap3-hc-p3-q19', 2, 'B — combustible difficilement inflammable'),
('ssiap3-hc-p3-q19', 3, 'F — très combustible'),
('ssiap3-hc-p3-q20', 0, 'PF 15 — pare-flammes 15 min'),
('ssiap3-hc-p3-q20', 1, 'PF 60 — pare-flammes 1 h'),
('ssiap3-hc-p3-q20', 2, 'CF 60 — coupe-feu 1 h (E + I)'),
('ssiap3-hc-p3-q20', 3, 'CF 120 — coupe-feu 2 h');

insert into public.cc_question_pairs (question_id, pair_index, left_text, right_text) values
('ssiap3-hc-p3-q21', 0, 'NF EN 671', 'Robinets d''incendie armés (RIA)'),
('ssiap3-hc-p3-q21', 1, 'NF EN 12845', 'Installations de sprinklers'),
('ssiap3-hc-p3-q21', 2, 'NF EN 50172', 'Éclairage de sécurité (BAES)'),
('ssiap3-hc-p3-q21', 3, 'NF S 61-933', 'SSI — règles d''installation'),
('ssiap3-hc-p3-q22', 0, 'R 60', 'Résistance mécanique 60 minutes'),
('ssiap3-hc-p3-q22', 1, 'E 60', 'Étanchéité 60 minutes'),
('ssiap3-hc-p3-q22', 2, 'I 60', 'Isolation thermique 60 minutes'),
('ssiap3-hc-p3-q22', 3, 'W 60', 'Limitation du rayonnement thermique 60 min');

insert into public.cc_question_categories (question_id, category_index, category_id, category_label) values
('ssiap3-hc-p3-q25', 0, 'A', '🟢 Euroclasse A — incombustible'),
('ssiap3-hc-p3-q25', 1, 'B', '🟡 Euroclasse B — difficilement inflammable'),
('ssiap3-hc-p3-q25', 2, 'D-F', '🔴 Euroclasse D à F — combustible');

insert into public.cc_question_category_items (question_id, item_index, item_text, correct_category) values
('ssiap3-hc-p3-q25', 0, 'Béton brut', 'A'),
('ssiap3-hc-p3-q25', 1, 'Plaque de plâtre BA13', 'A'),
('ssiap3-hc-p3-q25', 2, 'Tissu décoratif classé M2 (B)', 'B'),
('ssiap3-hc-p3-q25', 3, 'Bois traité ignifuge classe B', 'B'),
('ssiap3-hc-p3-q25', 4, 'PVC souple non traité', 'D-F'),
('ssiap3-hc-p3-q25', 5, 'Polystyrène expansé non traité', 'D-F');

insert into public.cc_question_decision_steps (question_id, step_index, step_question, options) values
('ssiap3-hc-p3-q26', 0,
 'ÉTAPE 1 — Le directeur veut transformer un local W en escape game ouvert au public. Première analyse ?',
 '[{"text":"Étude d''usage : changement d''affectation = passage Code du travail → ERP, procédure complète","nextStep":1},{"text":"Pas grave, on garde le classement W","nextStep":99},{"text":"Refuser sans étudier","nextStep":99}]'::jsonb),
('ssiap3-hc-p3-q26', 1,
 'ÉTAPE 2 — ERP type L envisagé. Étapes administratives ?',
 '[{"text":"Notice de sécurité, plans, dépôt PC ou AT, avis de la CCDSA","nextStep":2},{"text":"Faire les travaux d''abord et déclarer après","nextStep":99},{"text":"Demande de simple information mairie","nextStep":99}]'::jsonb),
('ssiap3-hc-p3-q26', 2,
 'ÉTAPE 3 — La commission émet un avis favorable sous réserves. Suite ?',
 '[{"text":"Lever les réserves dans les délais, faire valider à la visite finale, obtenir l''arrêté du maire","nextStep":null},{"text":"Ouvrir tout de suite et s''occuper des réserves plus tard","nextStep":null},{"text":"Fermer définitivement le projet","nextStep":null}]'::jsonb);

commit;
