-- SSIAP 3 — Partie 3 « Expertise technique et ingénierie »
-- 26 challenge cc_questions covering all 12 game types — module_id = ssiap3-partie3
begin;

insert into public.cc_questions
  (id, module_id, type, title, question, scenario, explanation,
   correct_answer, correct_answers, correct_order, correct_blanks, word_bank, sentence,
   difficulty, tags, pool, status, is_active)
values
('ssiap3-hc-p3-q1','ssiap3-partie3','quiz','Critères résistance au feu',
 'La résistance au feu d''un élément est caractérisée par :',
 null, 'Critères R/E/I + durée en minutes.',
 1, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie3']::text[], 'challenge', 'published', true),
('ssiap3-hc-p3-q2','ssiap3-partie3','quiz','Porte CF1H',
 'Une porte CF 1 h désigne :',
 null, 'Coupe-feu 60 minutes (EI 60).',
 1, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie3']::text[], 'challenge', 'published', true),
('ssiap3-hc-p3-q3','ssiap3-partie3','quiz','Euroclasse A1',
 'L''euroclasse A1 correspond à :',
 null, 'A1 = incombustible.',
 1, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie3']::text[], 'challenge', 'published', true),
('ssiap3-hc-p3-q4','ssiap3-partie3','quiz','ISI',
 'L''ingénierie de la sécurité incendie (ISI) sert principalement à :',
 null, 'Démontrer une équivalence quand le règlement prescriptif ne couvre pas le projet.',
 1, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie3']::text[], 'challenge', 'published', true),
('ssiap3-hc-p3-q5','ssiap3-partie3','true-false','Application des NF',
 'Les normes NF sont d''application volontaire sauf si rendues obligatoires par un texte réglementaire.',
 null, 'VRAI — Une norme devient opposable par renvoi réglementaire.',
 0, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie3']::text[], 'challenge', 'published', true),
('ssiap3-hc-p3-q6','ssiap3-partie3','true-false','Clapet coupe-feu',
 'Un clapet coupe-feu se ferme automatiquement à 70 °C grâce à un fusible thermique.',
 null, 'VRAI — Fusible 70 °C ou commande par CMSI.',
 0, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie3']::text[], 'challenge', 'published', true),
('ssiap3-hc-p3-q7','ssiap3-partie3','true-false','ATec vs PV agréé',
 'Un avis technique CSTB (ATec) a la même valeur qu''un PV de classement délivré par un laboratoire agréé.',
 null, 'FAUX — L''ATec est un avis, le PV agréé est l''attestation officielle.',
 1, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie3']::text[], 'challenge', 'published', true),
('ssiap3-hc-p3-q8','ssiap3-partie3','multiple-select','Désenfumage mécanique',
 'Quels sont les composants d''un désenfumage mécanique ?',
 null, 'Bouches, conduits CF + clapets, ventilateurs HT, coffrets CMSI.',
 null, array[0,1,2,3]::integer[], null, null, null, null,
 1, array['handcrafted','ssiap3','partie3']::text[], 'challenge', 'published', true),
('ssiap3-hc-p3-q9','ssiap3-partie3','multiple-select','Critères R/E/I',
 'Quels critères composent la classification de résistance au feu R/E/I ?',
 null, 'R = mécanique, E = étanchéité, I = isolation.',
 null, array[0,1,2]::integer[], null, null, null, null,
 1, array['handcrafted','ssiap3','partie3']::text[], 'challenge', 'published', true),
('ssiap3-hc-p3-q10','ssiap3-partie3','multiple-select','Documents PC ERP',
 'Quels documents techniques sont requis pour un dossier de permis de construire ERP ?',
 null, 'Notice, plans, calculs effectifs/désenfumage, étude stabilité.',
 null, array[0,1,2,3]::integer[], null, null, null, null,
 1, array['handcrafted','ssiap3','partie3']::text[], 'challenge', 'published', true),
('ssiap3-hc-p3-q11','ssiap3-partie3','find-intruder','Pas une NF SSI',
 'Lequel n''est PAS une norme de sécurité incendie ?',
 null, 'NF P 98-080 concerne les chaussées routières.',
 2, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie3']::text[], 'challenge', 'published', true),
('ssiap3-hc-p3-q12','ssiap3-partie3','find-intruder','Pas une euroclasse',
 'Lequel n''est PAS une euroclasse de réaction au feu ?',
 null, 'G n''existe pas dans l''échelle euroclasse.',
 2, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie3']::text[], 'challenge', 'published', true),
('ssiap3-hc-p3-q13','ssiap3-partie3','scenario','Clapet bloqué week-end',
 'Action correcte ?',
 'Vendredi 18h, le mainteneur signale que le clapet coupe-feu de la gaine technique principale est bloqué ouvert. Aucune intervention possible avant lundi.',
 'Mesures compensatoires + consignation.',
 1, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie3']::text[], 'challenge', 'published', true),
('ssiap3-hc-p3-q14','ssiap3-partie3','scenario','Aménagement non conforme',
 'Action correcte ?',
 'Le directeur souhaite transformer un local technique en salle de repos pour le personnel sans demande d''autorisation de travaux.',
 'Refuser, exiger AT + notice, accompagner la procédure.',
 1, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie3']::text[], 'challenge', 'published', true),
('ssiap3-hc-p3-q15','ssiap3-partie3','image-identify','Colonne sèche',
 'Pictogramme rouge avec une colonne d''alimentation pompiers :',
 null, 'F005/F006 — Colonne sèche ou humide.',
 1, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie3']::text[], 'challenge', 'published', true),
('ssiap3-hc-p3-q16','ssiap3-partie3','image-identify','Classement M',
 'Sigle « M » suivi d''un chiffre sur un matériau :',
 null, 'Classement français de réaction au feu (M0 à M4).',
 1, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie3']::text[], 'challenge', 'published', true),
('ssiap3-hc-p3-q17','ssiap3-partie3','sequence','Étude ISI',
 'Classez les phases d''une étude d''ingénierie de la sécurité incendie :',
 null, 'Diagnostic → objectifs → modélisation → validation → mise en œuvre.',
 null, null, array[0,1,2,3,4]::integer[], null, null, null,
 1, array['handcrafted','ssiap3','partie3']::text[], 'challenge', 'published', true),
('ssiap3-hc-p3-q18','ssiap3-partie3','sequence','Classement réaction au feu',
 'Classez les étapes du classement de réaction au feu :',
 null, 'Demande → essais labo → PV → marquage CE → suivi production.',
 null, null, array[0,1,2,3,4]::integer[], null, null, null,
 1, array['handcrafted','ssiap3','partie3']::text[], 'challenge', 'published', true),
('ssiap3-hc-p3-q19','ssiap3-partie3','ranking','Euroclasses combustibilité',
 'Classez ces euroclasses du moins au plus combustible :',
 null, 'A1 < A2 < B < F.',
 null, null, array[0,1,2,3]::integer[], null, null, null,
 1, array['handcrafted','ssiap3','partie3']::text[], 'challenge', 'published', true),
('ssiap3-hc-p3-q20','ssiap3-partie3','ranking','Performance coupe-feu',
 'Classez ces performances du moins au plus exigeant :',
 null, 'PF15 < PF60 < CF60 < CF120.',
 null, null, array[0,1,2,3]::integer[], null, null, null,
 1, array['handcrafted','ssiap3','partie3']::text[], 'challenge', 'published', true),
('ssiap3-hc-p3-q21','ssiap3-partie3','matching','Norme ↔ domaine',
 'Associez chaque norme à son domaine :',
 null, 'NF EN 671 = RIA / 12845 = sprinklers / 50172 = BAES / NF S 61-933 = SSI install.',
 null, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie3']::text[], 'challenge', 'published', true),
('ssiap3-hc-p3-q22','ssiap3-partie3','matching','Critère ↔ signification',
 'Associez chaque critère de résistance au feu à sa signification :',
 null, 'R = mécanique / E = étanchéité / I = isolation / W = rayonnement.',
 null, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie3']::text[], 'challenge', 'published', true),
('ssiap3-hc-p3-q23','ssiap3-partie3','fill-blank','Normes BAES & RIA',
 'Complétez les normes :',
 null, 'BAES → NF EN 50172. RIA → NF EN 671.',
 null, null, null, array['50172','671']::text[], array['671','12845','50172','61933','60439','12101']::text[],
 'Le BAES est régi par la NF EN %1% et le RIA par la NF EN %2%.',
 1, array['handcrafted','ssiap3','partie3']::text[], 'challenge', 'published', true),
('ssiap3-hc-p3-q24','ssiap3-partie3','fill-blank','Porte CF',
 'Complétez les valeurs porte coupe-feu :',
 null, 'CF 1 h = 60 minutes.',
 null, null, null, array['1','60']::text[], array['1','2','30','60','120','15']::text[],
 'Une porte CF %1% h résiste pendant %2% minutes au feu normalisé.',
 1, array['handcrafted','ssiap3','partie3']::text[], 'challenge', 'published', true),
('ssiap3-hc-p3-q25','ssiap3-partie3','categories','Réaction au feu',
 'Classez ces matériaux par classe euroclasse :',
 null, 'A = incombustibles / B = ignifugés / D-F = polymères combustibles.',
 null, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie3']::text[], 'challenge', 'published', true),
('ssiap3-hc-p3-q26','ssiap3-partie3','decision','Changement d''affectation',
 'Arbre de décision :',
 'Le directeur souhaite installer une zone d''escape game dans un local jusque-là classé bureaux (W). Public attendu, sans demande administrative préalable.',
 'Changement d''affectation = passage Code travail → ERP. Procédure complète AT/PC + CCDSA.',
 null, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie3']::text[], 'challenge', 'published', true);

commit;
