-- SSIAP 3 — Partie 4 « Coordination institutionnelle » — sub-tables
begin;

insert into public.cc_question_options (question_id, option_index, option_text) values
('ssiap3-hc-p4-q1', 0, 'Les usagers'),
('ssiap3-hc-p4-q1', 1, 'La compétence technique de prévention et d''intervention sapeurs-pompiers'),
('ssiap3-hc-p4-q1', 2, 'Directement le préfet'),
('ssiap3-hc-p4-q1', 3, 'La presse locale'),
('ssiap3-hc-p4-q2', 0, 'Est public et identique partout en France'),
('ssiap3-hc-p4-q2', 1, 'Définit les missions et l''organisation opérationnelle du SDIS départemental'),
('ssiap3-hc-p4-q2', 2, 'Concerne uniquement les ambulances privées'),
('ssiap3-hc-p4-q2', 3, 'Régule la circulation routière'),
('ssiap3-hc-p4-q3', 0, 'Tous les ERP'),
('ssiap3-hc-p4-q3', 1, 'Les sites Seveso seuil haut (et certaines ICPE AS)'),
('ssiap3-hc-p4-q3', 2, 'Tous les commerces de proximité'),
('ssiap3-hc-p4-q3', 3, 'Les logements collectifs'),
('ssiap3-hc-p4-q4', 0, 'Le SDIS de sa propre initiative'),
('ssiap3-hc-p4-q4', 1, 'L''exploitant ou le maître d''ouvrage, auprès de la mairie'),
('ssiap3-hc-p4-q4', 2, 'La presse locale'),
('ssiap3-hc-p4-q4', 3, 'Le banquier finançant le projet'),
('ssiap3-hc-p4-q5', 0, 'Vrai'),
('ssiap3-hc-p4-q5', 1, 'Faux'),
('ssiap3-hc-p4-q6', 0, 'Vrai'),
('ssiap3-hc-p4-q6', 1, 'Faux'),
('ssiap3-hc-p4-q7', 0, 'Vrai'),
('ssiap3-hc-p4-q7', 1, 'Faux'),
('ssiap3-hc-p4-q8', 0, 'SDIS (sapeurs-pompiers)'),
('ssiap3-hc-p4-q8', 1, 'Police / gendarmerie'),
('ssiap3-hc-p4-q8', 2, 'Bureaux de contrôle / vérificateurs réglementaires'),
('ssiap3-hc-p4-q8', 3, 'Mainteneurs spécialisés (SSI, ascenseurs, désenfumage)'),
('ssiap3-hc-p4-q8', 4, 'Service client commercial'),
('ssiap3-hc-p4-q9', 0, 'Plan d''intervention pompiers (à jour)'),
('ssiap3-hc-p4-q9', 1, 'Clé du coffre des compteurs et coupures'),
('ssiap3-hc-p4-q9', 2, 'Inventaire matières dangereuses si ICPE'),
('ssiap3-hc-p4-q9', 3, 'Plan d''évacuation + liste des PMR'),
('ssiap3-hc-p4-q9', 4, 'Tarifs et catalogue commercial'),
('ssiap3-hc-p4-q10', 0, 'Visite de réception avant ouverture'),
('ssiap3-hc-p4-q10', 1, 'Visite périodique (selon catégorie/type)'),
('ssiap3-hc-p4-q10', 2, 'Visite inopinée (initiative maire ou préfet)'),
('ssiap3-hc-p4-q10', 3, 'Visite de levée de réserves'),
('ssiap3-hc-p4-q10', 4, 'Visite à but commercial'),
('ssiap3-hc-p4-q11', 0, 'Maire de la commune'),
('ssiap3-hc-p4-q11', 1, 'SDIS départemental'),
('ssiap3-hc-p4-q11', 2, 'Banque privée de l''exploitant'),
('ssiap3-hc-p4-q11', 3, 'Préfet du département'),
('ssiap3-hc-p4-q12', 0, 'Maire (arrêté d''autorisation d''ouverture ERP)'),
('ssiap3-hc-p4-q12', 1, 'Préfet (IGH ou recours hiérarchique)'),
('ssiap3-hc-p4-q12', 2, 'Bureau de contrôle privé (vérifie mais ne décide pas)'),
('ssiap3-hc-p4-q12', 3, 'Préfet de police de Paris (compétence ERP/IGH à Paris)'),
('ssiap3-hc-p4-q13', 0, 'Refuser et fermer le PCS'),
('ssiap3-hc-p4-q13', 1, 'Coopérer pleinement, mettre tout à disposition, le COS prend la direction des opérations'),
('ssiap3-hc-p4-q13', 2, 'Demander une rétribution'),
('ssiap3-hc-p4-q13', 3, 'Démissionner pendant l''intervention'),
('ssiap3-hc-p4-q14', 0, 'Falsifier rétroactivement le registre'),
('ssiap3-hc-p4-q14', 1, 'Reconstituer factuellement les évènements documentés, prévenir la direction, préparer un plan d''amélioration'),
('ssiap3-hc-p4-q14', 2, 'Disparaître le jour J'),
('ssiap3-hc-p4-q14', 3, 'Ne rien faire'),
('ssiap3-hc-p4-q15', 0, 'La police nationale'),
('ssiap3-hc-p4-q15', 1, 'Le SDIS (sapeurs-pompiers, étoile à 6 branches)'),
('ssiap3-hc-p4-q15', 2, 'Un service de douane'),
('ssiap3-hc-p4-q15', 3, 'Une commune'),
('ssiap3-hc-p4-q16', 0, 'Une église'),
('ssiap3-hc-p4-q16', 1, 'La sécurité civile / SAMU (étoile de vie bleue)'),
('ssiap3-hc-p4-q16', 2, 'Un mouvement politique'),
('ssiap3-hc-p4-q16', 3, 'Une voirie');

insert into public.cc_question_items (question_id, item_index, item_text) values
('ssiap3-hc-p4-q17', 0, 'Activation de la cellule de crise interne'),
('ssiap3-hc-p4-q17', 1, 'Information du COS / SDIS dès leur arrivée'),
('ssiap3-hc-p4-q17', 2, 'Coordination interne ↔ pompiers ↔ exploitant'),
('ssiap3-hc-p4-q17', 3, 'Rapport préliminaire à la direction'),
('ssiap3-hc-p4-q17', 4, 'Retour d''expérience interne + commission'),
('ssiap3-hc-p4-q18', 0, 'Constitution du dossier de permis de construire'),
('ssiap3-hc-p4-q18', 1, 'Avis de la commission de sécurité (phase projet)'),
('ssiap3-hc-p4-q18', 2, 'Travaux et levée de réserves'),
('ssiap3-hc-p4-q18', 3, 'Visite de réception par la commission'),
('ssiap3-hc-p4-q18', 4, 'Arrêté d''autorisation d''ouverture par le maire'),
('ssiap3-hc-p4-q19', 0, 'Visite imprévue après incident grave (CCDSA d''urgence)'),
('ssiap3-hc-p4-q19', 1, 'Visite de réception avant ouverture'),
('ssiap3-hc-p4-q19', 2, 'Visite périodique programmée'),
('ssiap3-hc-p4-q19', 3, 'Contrôle qualité interne'),
('ssiap3-hc-p4-q20', 0, 'Plan d''évacuation interne ERP'),
('ssiap3-hc-p4-q20', 1, 'POI — Plan d''Opération Interne (ICPE)'),
('ssiap3-hc-p4-q20', 2, 'PCS — Plan Communal de Sauvegarde'),
('ssiap3-hc-p4-q20', 3, 'ORSEC — dispositif départemental / zonal');

insert into public.cc_question_pairs (question_id, pair_index, left_text, right_text) values
('ssiap3-hc-p4-q21', 0, 'COS (SDIS)', 'Commande les opérations de secours sur site'),
('ssiap3-hc-p4-q21', 1, 'DOS (préfet ou maire)', 'Directeur des opérations de secours — autorité'),
('ssiap3-hc-p4-q21', 2, 'Exploitant', 'Met à disposition installations et moyens'),
('ssiap3-hc-p4-q21', 3, 'SSIAP 3', 'Interface technique + logistique pour les pompiers'),
('ssiap3-hc-p4-q22', 0, 'Arrêté d''ouverture ERP', 'Maire de la commune'),
('ssiap3-hc-p4-q22', 1, 'Arrêté de fermeture IGH d''urgence', 'Préfet du département'),
('ssiap3-hc-p4-q22', 2, 'Avis technique de visite', 'SDIS'),
('ssiap3-hc-p4-q22', 3, 'PV des essais SSI', 'Mainteneur certifié');

insert into public.cc_question_categories (question_id, category_index, category_id, category_label) values
('ssiap3-hc-p4-q25', 0, 'interne', '🏢 Interne (établissement)'),
('ssiap3-hc-p4-q25', 1, 'communal', '🏛️ Communal'),
('ssiap3-hc-p4-q25', 2, 'departemental', '🗺️ Départemental / zonal');

insert into public.cc_question_category_items (question_id, item_index, item_text, correct_category) values
('ssiap3-hc-p4-q25', 0, 'Plan d''évacuation ERP', 'interne'),
('ssiap3-hc-p4-q25', 1, 'POI — Plan d''opération interne (ICPE)', 'interne'),
('ssiap3-hc-p4-q25', 2, 'PCS — Plan communal de sauvegarde', 'communal'),
('ssiap3-hc-p4-q25', 3, 'DICRIM — info préventive risques majeurs', 'communal'),
('ssiap3-hc-p4-q25', 4, 'ORSEC — dispositif départemental', 'departemental'),
('ssiap3-hc-p4-q25', 5, 'PPI — Plan particulier d''intervention (Seveso)', 'departemental');

insert into public.cc_question_decision_steps (question_id, step_index, step_question, options) values
('ssiap3-hc-p4-q26', 0,
 'ÉTAPE 1 — Salle de spectacle 800 personnes, 21h, début d''incendie en coulisses. Premier réflexe ?',
 '[{"text":"Activer l''évacuation guidée + appel 18 + alerter la direction","nextStep":1},{"text":"Stopper la musique brutalement sans annonce","nextStep":99},{"text":"Garder le silence pour ne pas paniquer","nextStep":99}]'::jsonb),
('ssiap3-hc-p4-q26', 1,
 'ÉTAPE 2 — Le COS arrive sur place. Action prioritaire ?',
 '[{"text":"Briefing rapide : nombre estimé évacués, lieu, accès, coupures, remise des plans","nextStep":2},{"text":"Quitter le site pour rentrer chez moi","nextStep":99},{"text":"Ouvrir une enquête interne immédiate","nextStep":99}]'::jsonb),
('ssiap3-hc-p4-q26', 2,
 'ÉTAPE 3 — Le sinistre est éteint. Suite ?',
 '[{"text":"Rapport circonstancié + retour d''expérience + levée de réserves avant réouverture","nextStep":null},{"text":"Rouvrir le soir même","nextStep":null},{"text":"Cacher l''incident au maire","nextStep":null}]'::jsonb);

commit;
