-- SSIAP 3 — Partie 4 « Coordination institutionnelle »
-- 26 challenge cc_questions covering all 12 game types — module_id = ssiap3-partie4
begin;

insert into public.cc_questions
  (id, module_id, type, title, question, scenario, explanation,
   correct_answer, correct_answers, correct_order, correct_blanks, word_bank, sentence,
   difficulty, tags, pool, status, is_active)
values
('ssiap3-hc-p4-q1','ssiap3-partie4','quiz','Rôle SDIS commission',
 'Le SDIS dans la commission de sécurité représente :',
 null, 'Le SDIS apporte la compétence technique. Avis, non décisionnaire.',
 1, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie4']::text[], 'challenge', 'published', true),
('ssiap3-hc-p4-q2','ssiap3-partie4','quiz','RO SDIS',
 'Le règlement opérationnel (RO) du SDIS :',
 null, 'RO = missions et organisation opérationnelle du SDIS, validé par le préfet.',
 1, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie4']::text[], 'challenge', 'published', true),
('ssiap3-hc-p4-q3','ssiap3-partie4','quiz','POI obligatoire',
 'Un POI (plan d''opération interne) est obligatoire pour :',
 null, 'ICPE Seveso seuil haut et certaines AS.',
 1, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie4']::text[], 'challenge', 'published', true),
('ssiap3-hc-p4-q4','ssiap3-partie4','quiz','Demande visite réception',
 'La visite de réception d''un ERP avant ouverture est demandée par :',
 null, 'L''exploitant ou le maître d''ouvrage, auprès de la mairie.',
 1, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie4']::text[], 'challenge', 'published', true),
('ssiap3-hc-p4-q5','ssiap3-partie4','true-false','Préfet et fermeture',
 'Le préfet peut prendre un arrêté de fermeture administrative en cas de péril imminent.',
 null, 'VRAI — Police générale du préfet.',
 0, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie4']::text[], 'challenge', 'published', true),
('ssiap3-hc-p4-q6','ssiap3-partie4','true-false','Maire et avis',
 'Le maire peut refuser de suivre l''avis de la commission s''il motive sa décision.',
 null, 'VRAI — Avis simple, mais le maire engage sa responsabilité.',
 0, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie4']::text[], 'challenge', 'published', true),
('ssiap3-hc-p4-q7','ssiap3-partie4','true-false','SPP entreprise',
 'Un sapeur-pompier d''entreprise n''a aucune existence légale en France.',
 null, 'FAUX — Les équipiers de sécurité d''entreprise sont encadrés par le Code du travail et le RO.',
 1, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie4']::text[], 'challenge', 'published', true),
('ssiap3-hc-p4-q8','ssiap3-partie4','multiple-select','Acteurs externes',
 'Quels acteurs externes le SSIAP 3 doit-il coordonner ?',
 null, 'SDIS, police, vérificateurs, mainteneurs spécialisés.',
 null, array[0,1,2,3]::integer[], null, null, null, null,
 1, array['handcrafted','ssiap3','partie4']::text[], 'challenge', 'published', true),
('ssiap3-hc-p4-q9','ssiap3-partie4','multiple-select','Documents pour SDIS',
 'Quels documents doivent être disponibles pour le SDIS en cas d''intervention ?',
 null, 'Plan intervention, clé coupures, inventaire MD, plan évacuation + PMR.',
 null, array[0,1,2,3]::integer[], null, null, null, null,
 1, array['handcrafted','ssiap3','partie4']::text[], 'challenge', 'published', true),
('ssiap3-hc-p4-q10','ssiap3-partie4','multiple-select','Types de visites',
 'Quels types de visites d''une commission de sécurité existent ?',
 null, 'Réception, périodique, inopinée, levée de réserves.',
 null, array[0,1,2,3]::integer[], null, null, null, null,
 1, array['handcrafted','ssiap3','partie4']::text[], 'challenge', 'published', true),
('ssiap3-hc-p4-q11','ssiap3-partie4','find-intruder','Pas un acteur public',
 'Lequel n''est PAS un acteur public ou institutionnel de la sécurité incendie ?',
 null, 'La banque privée de l''exploitant n''est pas un acteur institutionnel.',
 2, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie4']::text[], 'challenge', 'published', true),
('ssiap3-hc-p4-q12','ssiap3-partie4','find-intruder','Pas décisionnaire ERP',
 'Lequel n''est PAS une autorité décisionnaire en matière d''ouverture d''ERP ?',
 null, 'Le bureau de contrôle privé vérifie mais ne décide pas.',
 2, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie4']::text[], 'challenge', 'published', true),
('ssiap3-hc-p4-q13','ssiap3-partie4','scenario','Coopération avec COS',
 'Action correcte ?',
 'Lors d''un sinistre important, le COS du SDIS prend la main et vous demande tous vos moyens, plans et agents.',
 'Coopérer pleinement, le COS dirige les opérations sur site.',
 1, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie4']::text[], 'challenge', 'published', true),
('ssiap3-hc-p4-q14','ssiap3-partie4','scenario','Visite inopinée préfet',
 'Action correcte ?',
 'Une visite inopinée du préfet est annoncée pour demain matin. Le registre n''est pas à jour depuis 2 mois.',
 'Reconstituer factuellement, prévenir la direction, préparer un plan d''amélioration.',
 1, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie4']::text[], 'challenge', 'published', true),
('ssiap3-hc-p4-q15','ssiap3-partie4','image-identify','Insigne SDIS',
 'Étoile à 6 branches rouge avec logo « SDIS » :',
 null, 'Insigne du Service Départemental d''Incendie et de Secours.',
 1, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie4']::text[], 'challenge', 'published', true),
('ssiap3-hc-p4-q16','ssiap3-partie4','image-identify','Étoile de vie',
 'Croix bleue à 6 branches (étoile de vie) :',
 null, 'Symbole international des services d''urgence médicale / sécurité civile.',
 1, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie4']::text[], 'challenge', 'published', true),
('ssiap3-hc-p4-q17','ssiap3-partie4','sequence','Coordination sinistre',
 'Classez les étapes de coordination après un sinistre :',
 null, 'Cellule crise → info COS → coordination ↔ pompiers → rapport direction → REX.',
 null, null, array[0,1,2,3,4]::integer[], null, null, null,
 1, array['handcrafted','ssiap3','partie4']::text[], 'challenge', 'published', true),
('ssiap3-hc-p4-q18','ssiap3-partie4','sequence','Procédure ouverture ERP',
 'Classez les étapes administratives pour un nouvel ERP :',
 null, 'PC → avis commission projet → travaux + levée → visite réception → arrêté maire.',
 null, null, array[0,1,2,3,4]::integer[], null, null, null,
 1, array['handcrafted','ssiap3','partie4']::text[], 'challenge', 'published', true),
('ssiap3-hc-p4-q19','ssiap3-partie4','ranking','Priorité des visites',
 'Classez ces visites par niveau d''urgence d''organisation (la plus urgente d''abord) :',
 null, 'Incident grave > réception > périodique > contrôle interne.',
 null, null, array[0,1,2,3]::integer[], null, null, null,
 1, array['handcrafted','ssiap3','partie4']::text[], 'challenge', 'published', true),
('ssiap3-hc-p4-q20','ssiap3-partie4','ranking','Plans emboîtés',
 'Classez ces plans de secours du plus local au plus large :',
 null, 'Évacuation ERP < POI < PCS < ORSEC.',
 null, null, array[0,1,2,3]::integer[], null, null, null,
 1, array['handcrafted','ssiap3','partie4']::text[], 'challenge', 'published', true),
('ssiap3-hc-p4-q21','ssiap3-partie4','matching','Acteur sinistre ↔ rôle',
 'Associez chaque acteur d''un sinistre majeur à son rôle :',
 null, 'COS = ops site / DOS = autorité / Exploitant = ressources / SSIAP 3 = interface.',
 null, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie4']::text[], 'challenge', 'published', true),
('ssiap3-hc-p4-q22','ssiap3-partie4','matching','Document ↔ acteur',
 'Associez chaque document à l''acteur compétent :',
 null, 'Ouverture = Maire / Fermeture IGH = Préfet / Avis visite = SDIS / PV SSI = mainteneur.',
 null, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie4']::text[], 'challenge', 'published', true),
('ssiap3-hc-p4-q23','ssiap3-partie4','fill-blank','DOS et COS',
 'Complétez les rôles :',
 null, 'DOS = directeur des opérations (préfet/maire). COS = commandant opérations sur le terrain.',
 null, null, null, array['DOS','COS']::text[], array['DOS','COS','SDIS','SSIAP','SAMU','GIPN']::text[],
 'Le %1% est le directeur des opérations de secours, le %2% est le commandant des opérations sur le terrain.',
 1, array['handcrafted','ssiap3','partie4']::text[], 'challenge', 'published', true),
('ssiap3-hc-p4-q24','ssiap3-partie4','fill-blank','POI et PPI Seveso',
 'Complétez les plans Seveso :',
 null, 'POI = interne établissement / PPI = plan particulier d''intervention préfectoral.',
 null, null, null, array['POI','PPI']::text[], array['POI','PPI','PCS','ORSEC','DICRIM','DECI']::text[],
 'Un établissement Seveso seuil haut doit disposer d''un %1% (interne) et d''un %2% (préfectoral externe).',
 1, array['handcrafted','ssiap3','partie4']::text[], 'challenge', 'published', true),
('ssiap3-hc-p4-q25','ssiap3-partie4','categories','Plans ↔ niveau',
 'Classez ces plans par niveau de gouvernance :',
 null, 'Interne (entreprise/ERP) / Communal (PCS, DICRIM) / Départemental (ORSEC, PPI).',
 null, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie4']::text[], 'challenge', 'published', true),
('ssiap3-hc-p4-q26','ssiap3-partie4','decision','Crise salle de spectacle',
 'Arbre de décision :',
 'Salle de spectacle 800 personnes, 21h, plein concert, début d''incendie en coulisses. Vous êtes SSIAP 3 sur place.',
 'Évacuation guidée + alerte 18 + accueil pompiers + REX + levée de réserve.',
 null, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie4']::text[], 'challenge', 'published', true);

commit;
