-- SSIAP 3 — Partie 5 « Analyse des risques et amélioration continue »
-- 26 challenge cc_questions covering all 12 game types — module_id = ssiap3-partie5
begin;

insert into public.cc_questions
  (id, module_id, type, title, question, scenario, explanation,
   correct_answer, correct_answers, correct_order, correct_blanks, word_bank, sentence,
   difficulty, tags, pool, status, is_active)
values
('ssiap3-hc-p5-q1','ssiap3-partie5','quiz','Définition criticité',
 'Dans l''évaluation des risques, la criticité est définie par :',
 null, 'Criticité = probabilité × gravité (× détectabilité pour AMDEC).',
 1, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie5']::text[], 'challenge', 'published', true),
('ssiap3-hc-p5-q2','ssiap3-partie5','quiz','AMDEC',
 'L''acronyme AMDEC signifie :',
 null, 'Analyse des Modes de Défaillance, de leurs Effets et de leur Criticité.',
 1, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie5']::text[], 'challenge', 'published', true),
('ssiap3-hc-p5-q3','ssiap3-partie5','quiz','DUERP obligatoire',
 'Le DUERP est obligatoire :',
 null, 'Pour tout employeur dès le 1er salarié (Code du travail).',
 1, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie5']::text[], 'challenge', 'published', true),
('ssiap3-hc-p5-q4','ssiap3-partie5','quiz','PDCA',
 'La démarche PDCA correspond à :',
 null, 'Plan / Do / Check / Act — Roue de Deming.',
 1, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie5']::text[], 'challenge', 'published', true),
('ssiap3-hc-p5-q5','ssiap3-partie5','true-false','ALARP',
 'ALARP signifie réduire un risque jusqu''à un niveau aussi bas que raisonnablement praticable.',
 null, 'VRAI — As Low As Reasonably Practicable.',
 0, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie5']::text[], 'challenge', 'published', true),
('ssiap3-hc-p5-q6','ssiap3-partie5','true-false','Risque résiduel',
 'Un risque résiduel acceptable peut être formellement documenté et accepté par la direction.',
 null, 'VRAI — Acceptation formelle après mesures de maîtrise.',
 0, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie5']::text[], 'challenge', 'published', true),
('ssiap3-hc-p5-q7','ssiap3-partie5','true-false','Barrière prévention',
 'Une barrière de prévention agit après la survenue de l''événement.',
 null, 'FAUX — Prévention = avant. Protection = après.',
 1, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie5']::text[], 'challenge', 'published', true),
('ssiap3-hc-p5-q8','ssiap3-partie5','multiple-select','Méthodes analyse',
 'Quelles méthodes sont reconnues pour l''analyse des risques ?',
 null, 'APR, AMDEC, HAZOP, Bow-tie.',
 null, array[0,1,2,3]::integer[], null, null, null, null,
 1, array['handcrafted','ssiap3','partie5']::text[], 'challenge', 'published', true),
('ssiap3-hc-p5-q9','ssiap3-partie5','multiple-select','Matrice criticité',
 'Quels paramètres composent une matrice de criticité ?',
 null, 'Probabilité, gravité, détectabilité.',
 null, array[0,1,2]::integer[], null, null, null, null,
 1, array['handcrafted','ssiap3','partie5']::text[], 'challenge', 'published', true),
('ssiap3-hc-p5-q10','ssiap3-partie5','multiple-select','Étapes REX',
 'Quelles sont les étapes d''un retour d''expérience (REX) ?',
 null, 'Collecte, analyse causes, actions correctives, suivi.',
 null, array[0,1,2,3]::integer[], null, null, null, null,
 1, array['handcrafted','ssiap3','partie5']::text[], 'challenge', 'published', true),
('ssiap3-hc-p5-q11','ssiap3-partie5','find-intruder','Pas un classement ICPE',
 'Lequel n''est PAS un régime ICPE ?',
 null, 'Régimes : D, E, A, AS. « M » n''existe pas.',
 2, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie5']::text[], 'challenge', 'published', true),
('ssiap3-hc-p5-q12','ssiap3-partie5','find-intruder','Pas un outil qualité',
 'Lequel n''est PAS un outil de management de la qualité ?',
 null, 'L''échelle de Mohs mesure la dureté des minéraux.',
 2, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie5']::text[], 'challenge', 'published', true),
('ssiap3-hc-p5-q13','ssiap3-partie5','scenario','Risque inacceptable AMDEC',
 'Action correcte ?',
 'Une analyse AMDEC met en évidence un risque de défaillance majeure du SSI avec criticité 25 (zone inacceptable).',
 'Plan d''actions immédiat + mesures de maîtrise + alerte direction.',
 1, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie5']::text[], 'challenge', 'published', true),
('ssiap3-hc-p5-q14','ssiap3-partie5','scenario','Audit interne défavorable',
 'Action correcte ?',
 'Votre audit interne révèle des écarts significatifs : registre incomplet, formations non à jour, exercices manqués.',
 'Plan d''actions priorisé, validé direction, suivi CODIR.',
 1, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie5']::text[], 'challenge', 'published', true),
('ssiap3-hc-p5-q15','ssiap3-partie5','image-identify','Matrice criticité',
 'Tableau 5×5 coloré vert / orange / rouge :',
 null, 'Matrice de criticité — probabilité × gravité.',
 1, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie5']::text[], 'challenge', 'published', true),
('ssiap3-hc-p5-q16','ssiap3-partie5','image-identify','Ishikawa',
 'Diagramme en arête de poisson :',
 null, 'Diagramme d''Ishikawa (cause-effet, 5M / 6M).',
 1, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie5']::text[], 'challenge', 'published', true),
('ssiap3-hc-p5-q17','ssiap3-partie5','sequence','Démarche PDCA',
 'Classez les étapes d''une démarche d''amélioration continue :',
 null, 'Identifier → P planifier → D faire → C vérifier → A acter.',
 null, null, array[0,1,2,3,4]::integer[], null, null, null,
 1, array['handcrafted','ssiap3','partie5']::text[], 'challenge', 'published', true),
('ssiap3-hc-p5-q18','ssiap3-partie5','sequence','Analyse de risques',
 'Classez les étapes d''une analyse de risques :',
 null, 'Identifier dangers → évaluer → hiérarchiser → mesures → suivi.',
 null, null, array[0,1,2,3,4]::integer[], null, null, null,
 1, array['handcrafted','ssiap3','partie5']::text[], 'challenge', 'published', true),
('ssiap3-hc-p5-q19','ssiap3-partie5','ranking','Niveaux de criticité',
 'Classez ces niveaux de criticité du plus au moins critique :',
 null, 'Inacceptable > majeur > modéré > acceptable.',
 null, null, array[0,1,2,3]::integer[], null, null, null,
 1, array['handcrafted','ssiap3','partie5']::text[], 'challenge', 'published', true),
('ssiap3-hc-p5-q20','ssiap3-partie5','ranking','Pyramide mesures',
 'Classez les mesures de maîtrise de la plus efficace à la moins (pyramide INRS) :',
 null, 'Suppression > Substitution > Protection collective > Procédures + EPI.',
 null, null, array[0,1,2,3]::integer[], null, null, null,
 1, array['handcrafted','ssiap3','partie5']::text[], 'challenge', 'published', true),
('ssiap3-hc-p5-q21','ssiap3-partie5','matching','Méthode ↔ usage',
 'Associez chaque méthode d''analyse à son usage privilégié :',
 null, 'APR = amont / AMDEC = défaillances / HAZOP = procédés / Bow-tie = causes/conséquences.',
 null, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie5']::text[], 'challenge', 'published', true),
('ssiap3-hc-p5-q22','ssiap3-partie5','matching','Barrière ↔ type',
 'Associez chaque barrière à son type :',
 null, 'DAI = prévention / Sprinkler = protection / Maintenance = prévention orga / Plan évacuation = protection humaine.',
 null, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie5']::text[], 'challenge', 'published', true),
('ssiap3-hc-p5-q23','ssiap3-partie5','fill-blank','Criticité',
 'Complétez la formule de la criticité :',
 null, 'Criticité = probabilité × gravité.',
 null, null, null, array['probabilité','gravité']::text[], array['probabilité','gravité','effectif','surface','coût','vitesse','détectabilité']::text[],
 'En analyse de risques, la criticité est définie par le produit %1% × %2%.',
 1, array['handcrafted','ssiap3','partie5']::text[], 'challenge', 'published', true),
('ssiap3-hc-p5-q24','ssiap3-partie5','fill-blank','Régimes ICPE',
 'Complétez les régimes ICPE :',
 null, 'D = déclaration / AS = autorisation avec servitudes.',
 null, null, null, array['Déclaration','AS']::text[], array['Déclaration','Enregistrement','Autorisation','AS','M','C']::text[],
 'Les régimes ICPE comportent les classements %1%, Enregistrement, Autorisation et %2%.',
 1, array['handcrafted','ssiap3','partie5']::text[], 'challenge', 'published', true),
('ssiap3-hc-p5-q25','ssiap3-partie5','categories','Mesures ↔ type',
 'Classez ces mesures de maîtrise par type :',
 null, 'Prévention / Protection / Organisationnel.',
 null, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie5']::text[], 'challenge', 'published', true),
('ssiap3-hc-p5-q26','ssiap3-partie5','decision','Nouveau procédé risqué',
 'Arbre de décision :',
 'La direction veut installer une imprimerie numérique avec stockage de 500 L de solvants dans un local existant. Aucune analyse de risque préalable.',
 'APR/AMDEC, plan d''actions chiffré, suivi PDCA.',
 null, null, null, null, null, null,
 1, array['handcrafted','ssiap3','partie5']::text[], 'challenge', 'published', true);

commit;
