-- SSIAP 3 — Partie 5 « Analyse des risques et amélioration continue » — sub-tables
begin;

insert into public.cc_question_options (question_id, option_index, option_text) values
('ssiap3-hc-p5-q1', 0, 'La gravité seule'),
('ssiap3-hc-p5-q1', 1, 'Probabilité × gravité (× détectabilité pour l''IPR)'),
('ssiap3-hc-p5-q1', 2, 'Le nombre d''employés exposés'),
('ssiap3-hc-p5-q1', 3, 'Le nombre de mètres carrés'),
('ssiap3-hc-p5-q2', 0, 'Analyse Mécanique Des Échantillons Chimiques'),
('ssiap3-hc-p5-q2', 1, 'Analyse des Modes de Défaillance, de leurs Effets et de leur Criticité'),
('ssiap3-hc-p5-q2', 2, 'Aide Médicale aux Détenteurs Externes Critiques'),
('ssiap3-hc-p5-q2', 3, 'Aucune signification réglementaire'),
('ssiap3-hc-p5-q3', 0, 'Pour les entreprises de plus de 250 salariés'),
('ssiap3-hc-p5-q3', 1, 'Pour tout employeur dès le 1er salarié'),
('ssiap3-hc-p5-q3', 2, 'Pour les SSIAP exclusivement'),
('ssiap3-hc-p5-q3', 3, 'Pour les particuliers'),
('ssiap3-hc-p5-q4', 0, 'Préparer / Démolir / Corriger / Acter'),
('ssiap3-hc-p5-q4', 1, 'Plan / Do / Check / Act (Roue de Deming)'),
('ssiap3-hc-p5-q4', 2, 'Procédure / Décret / Circulaire / Application'),
('ssiap3-hc-p5-q4', 3, 'Aucune signification'),
('ssiap3-hc-p5-q5', 0, 'Vrai'),
('ssiap3-hc-p5-q5', 1, 'Faux'),
('ssiap3-hc-p5-q6', 0, 'Vrai'),
('ssiap3-hc-p5-q6', 1, 'Faux'),
('ssiap3-hc-p5-q7', 0, 'Vrai'),
('ssiap3-hc-p5-q7', 1, 'Faux'),
('ssiap3-hc-p5-q8', 0, 'APR — Analyse Préliminaire des Risques'),
('ssiap3-hc-p5-q8', 1, 'AMDEC'),
('ssiap3-hc-p5-q8', 2, 'HAZOP'),
('ssiap3-hc-p5-q8', 3, 'Bow-tie (nœud papillon)'),
('ssiap3-hc-p5-q8', 4, 'Carte météo'),
('ssiap3-hc-p5-q9', 0, 'Probabilité d''occurrence'),
('ssiap3-hc-p5-q9', 1, 'Gravité des conséquences'),
('ssiap3-hc-p5-q9', 2, 'Détectabilité (parfois ajoutée — IPR)'),
('ssiap3-hc-p5-q9', 3, 'Prix d''achat des équipements'),
('ssiap3-hc-p5-q10', 0, 'Collecte factuelle des données'),
('ssiap3-hc-p5-q10', 1, 'Analyse des causes (5 pourquoi, Ishikawa)'),
('ssiap3-hc-p5-q10', 2, 'Identification des actions correctives'),
('ssiap3-hc-p5-q10', 3, 'Suivi de l''efficacité des actions'),
('ssiap3-hc-p5-q10', 4, 'Sanction des coupables'),
('ssiap3-hc-p5-q11', 0, 'D — Déclaration'),
('ssiap3-hc-p5-q11', 1, 'E — Enregistrement'),
('ssiap3-hc-p5-q11', 2, 'M — Marchand'),
('ssiap3-hc-p5-q11', 3, 'A / AS — Autorisation (avec servitudes)'),
('ssiap3-hc-p5-q12', 0, 'Diagramme d''Ishikawa (cause-effet)'),
('ssiap3-hc-p5-q12', 1, 'Roue de Deming (PDCA)'),
('ssiap3-hc-p5-q12', 2, 'Échelle de Mohs (dureté des minéraux)'),
('ssiap3-hc-p5-q12', 3, 'Méthode des 5 pourquoi'),
('ssiap3-hc-p5-q13', 0, 'Ignorer pour ne pas alarmer la direction'),
('ssiap3-hc-p5-q13', 1, 'Plan d''actions immédiat + mesures de maîtrise + alerte formelle à la direction'),
('ssiap3-hc-p5-q13', 2, 'Falsifier l''analyse de risque'),
('ssiap3-hc-p5-q13', 3, 'Démissionner'),
('ssiap3-hc-p5-q14', 0, 'Cacher les résultats de l''audit'),
('ssiap3-hc-p5-q14', 1, 'Élaborer un plan d''actions priorisé, validé par la direction, suivi en CODIR'),
('ssiap3-hc-p5-q14', 2, 'Sanctionner les agents'),
('ssiap3-hc-p5-q14', 3, 'Annuler l''audit'),
('ssiap3-hc-p5-q15', 0, 'Une grille de Sudoku'),
('ssiap3-hc-p5-q15', 1, 'Une matrice de criticité (probabilité × gravité)'),
('ssiap3-hc-p5-q15', 2, 'Un échiquier'),
('ssiap3-hc-p5-q15', 3, 'Un calendrier'),
('ssiap3-hc-p5-q16', 0, 'Le plan d''un bateau'),
('ssiap3-hc-p5-q16', 1, 'Un diagramme d''Ishikawa (cause-effet, 5M / 6M)'),
('ssiap3-hc-p5-q16', 2, 'Un schéma de désenfumage'),
('ssiap3-hc-p5-q16', 3, 'Un arbre généalogique');

insert into public.cc_question_items (question_id, item_index, item_text) values
('ssiap3-hc-p5-q17', 0, 'Identifier le problème ou l''objectif'),
('ssiap3-hc-p5-q17', 1, 'P — Planifier les actions'),
('ssiap3-hc-p5-q17', 2, 'D — Faire / mettre en œuvre'),
('ssiap3-hc-p5-q17', 3, 'C — Vérifier les résultats'),
('ssiap3-hc-p5-q17', 4, 'A — Standardiser ou ajuster (acter)'),
('ssiap3-hc-p5-q18', 0, 'Identifier les dangers'),
('ssiap3-hc-p5-q18', 1, 'Évaluer les risques (probabilité × gravité)'),
('ssiap3-hc-p5-q18', 2, 'Hiérarchiser et cartographier'),
('ssiap3-hc-p5-q18', 3, 'Définir les mesures de maîtrise (prévention + protection)'),
('ssiap3-hc-p5-q18', 4, 'Suivre l''efficacité et réviser'),
('ssiap3-hc-p5-q19', 0, 'Risque inacceptable (zone rouge — action immédiate)'),
('ssiap3-hc-p5-q19', 1, 'Risque majeur — maîtrise renforcée requise'),
('ssiap3-hc-p5-q19', 2, 'Risque modéré — surveillance et plan d''action'),
('ssiap3-hc-p5-q19', 3, 'Risque acceptable — suivi normal'),
('ssiap3-hc-p5-q20', 0, 'Suppression du danger à la source'),
('ssiap3-hc-p5-q20', 1, 'Substitution par un agent moins dangereux'),
('ssiap3-hc-p5-q20', 2, 'Mesures techniques (protection collective)'),
('ssiap3-hc-p5-q20', 3, 'Procédures + EPI individuels (en dernier ressort)');

insert into public.cc_question_pairs (question_id, pair_index, left_text, right_text) values
('ssiap3-hc-p5-q21', 0, 'APR', 'Étude amont d''identification des dangers'),
('ssiap3-hc-p5-q21', 1, 'AMDEC', 'Modes de défaillance d''un système / équipement'),
('ssiap3-hc-p5-q21', 2, 'HAZOP', 'Procédés industriels — déviation de paramètres'),
('ssiap3-hc-p5-q21', 3, 'Bow-tie', 'Visualisation causes / conséquences (nœud papillon)'),
('ssiap3-hc-p5-q22', 0, 'Détection automatique d''incendie', 'Prévention (détecter tôt)'),
('ssiap3-hc-p5-q22', 1, 'Sprinkler', 'Protection (limiter conséquences)'),
('ssiap3-hc-p5-q22', 2, 'Plan de maintenance préventive', 'Prévention organisationnelle'),
('ssiap3-hc-p5-q22', 3, 'Plan d''évacuation', 'Protection humaine');

insert into public.cc_question_categories (question_id, category_index, category_id, category_label) values
('ssiap3-hc-p5-q25', 0, 'prevention', '🛡️ Prévention (avant)'),
('ssiap3-hc-p5-q25', 1, 'protection', '🚨 Protection (limiter conséquences)'),
('ssiap3-hc-p5-q25', 2, 'organisationnel', '📋 Organisationnel (procédures)');

insert into public.cc_question_category_items (question_id, item_index, item_text, correct_category) values
('ssiap3-hc-p5-q25', 0, 'Détection automatique d''incendie', 'prevention'),
('ssiap3-hc-p5-q25', 1, 'Système sprinklers', 'protection'),
('ssiap3-hc-p5-q25', 2, 'Compartimentage coupe-feu', 'protection'),
('ssiap3-hc-p5-q25', 3, 'Permis de feu pour travaux par points chauds', 'organisationnel'),
('ssiap3-hc-p5-q25', 4, 'Procédure d''évacuation et exercices', 'organisationnel'),
('ssiap3-hc-p5-q25', 5, 'Substitution d''un solvant inflammable par un agent plus sûr', 'prevention');

insert into public.cc_question_decision_steps (question_id, step_index, step_question, options) values
('ssiap3-hc-p5-q26', 0,
 'ÉTAPE 1 — Installation d''une imprimerie numérique avec 500 L de solvants dans un local existant. Première priorité ?',
 '[{"text":"Réaliser ou commander une analyse de risques (APR / AMDEC) avant tout démarrage","nextStep":1},{"text":"Laisser faire, ce n''est pas important","nextStep":99},{"text":"Refuser sans étudier","nextStep":99}]'::jsonb),
('ssiap3-hc-p5-q26', 1,
 'ÉTAPE 2 — L''analyse classe le risque comme inacceptable. Action ?',
 '[{"text":"Proposer un plan d''actions chiffré : ICPE, ventilation, détection gaz, formation, EPI, plan de prévention","nextStep":2},{"text":"Mettre en service quand même","nextStep":99},{"text":"Ignorer et passer à autre chose","nextStep":99}]'::jsonb),
('ssiap3-hc-p5-q26', 2,
 'ÉTAPE 3 — Mesures de maîtrise déployées. Suite ?',
 '[{"text":"Audit régulier + REX + ajustements selon démarche PDCA","nextStep":null},{"text":"Considérer le risque éliminé une fois pour toutes","nextStep":null},{"text":"Cesser tout suivi","nextStep":null}]'::jsonb);

commit;
